// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: aequitas/validatorsubsidy/v1/validatorsubsidy.proto

package types

import (
	cosmossdk_io_math "cosmossdk.io/math"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type ValidatorStatus int32

const (
	ValidatorStatus_VALIDATOR_STATUS_UNSPECIFIED ValidatorStatus = 0
	ValidatorStatus_VALIDATOR_STATUS_ACTIVE      ValidatorStatus = 1
	ValidatorStatus_VALIDATOR_STATUS_INACTIVE    ValidatorStatus = 2
	ValidatorStatus_VALIDATOR_STATUS_SUSPENDED   ValidatorStatus = 3
	ValidatorStatus_VALIDATOR_STATUS_GRADUATED   ValidatorStatus = 4
)

var ValidatorStatus_name = map[int32]string{
	0: "VALIDATOR_STATUS_UNSPECIFIED",
	1: "VALIDATOR_STATUS_ACTIVE",
	2: "VALIDATOR_STATUS_INACTIVE",
	3: "VALIDATOR_STATUS_SUSPENDED",
	4: "VALIDATOR_STATUS_GRADUATED",
}

var ValidatorStatus_value = map[string]int32{
	"VALIDATOR_STATUS_UNSPECIFIED": 0,
	"VALIDATOR_STATUS_ACTIVE":      1,
	"VALIDATOR_STATUS_INACTIVE":    2,
	"VALIDATOR_STATUS_SUSPENDED":   3,
	"VALIDATOR_STATUS_GRADUATED":   4,
}

func (x ValidatorStatus) String() string {
	return proto.EnumName(ValidatorStatus_name, int32(x))
}

func (ValidatorStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_defac9f3380bb921, []int{0}
}

type PaymentType int32

const (
	PaymentType_PAYMENT_TYPE_UNSPECIFIED            PaymentType = 0
	PaymentType_PAYMENT_TYPE_MONTHLY_SUBSIDY        PaymentType = 1
	PaymentType_PAYMENT_TYPE_EMERGENCY_EXPENSE      PaymentType = 2
	PaymentType_PAYMENT_TYPE_INFRASTRUCTURE_UPGRADE PaymentType = 3
	PaymentType_PAYMENT_TYPE_BONUS_REWARD           PaymentType = 4
)

var PaymentType_name = map[int32]string{
	0: "PAYMENT_TYPE_UNSPECIFIED",
	1: "PAYMENT_TYPE_MONTHLY_SUBSIDY",
	2: "PAYMENT_TYPE_EMERGENCY_EXPENSE",
	3: "PAYMENT_TYPE_INFRASTRUCTURE_UPGRADE",
	4: "PAYMENT_TYPE_BONUS_REWARD",
}

var PaymentType_value = map[string]int32{
	"PAYMENT_TYPE_UNSPECIFIED":            0,
	"PAYMENT_TYPE_MONTHLY_SUBSIDY":        1,
	"PAYMENT_TYPE_EMERGENCY_EXPENSE":      2,
	"PAYMENT_TYPE_INFRASTRUCTURE_UPGRADE": 3,
	"PAYMENT_TYPE_BONUS_REWARD":           4,
}

func (x PaymentType) String() string {
	return proto.EnumName(PaymentType_name, int32(x))
}

func (PaymentType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_defac9f3380bb921, []int{1}
}

// ValidatorSubsidyPool manages the validator subsidy treasury
type ValidatorSubsidyPool struct {
	TotalAllocated   cosmossdk_io_math.Int `protobuf:"bytes,1,opt,name=total_allocated,json=totalAllocated,proto3,customtype=cosmossdk.io/math.Int" json:"total_allocated"`
	MonthlyBudget    cosmossdk_io_math.Int `protobuf:"bytes,2,opt,name=monthly_budget,json=monthlyBudget,proto3,customtype=cosmossdk.io/math.Int" json:"monthly_budget"`
	EmergencyReserve cosmossdk_io_math.Int `protobuf:"bytes,3,opt,name=emergency_reserve,json=emergencyReserve,proto3,customtype=cosmossdk.io/math.Int" json:"emergency_reserve"`
	LastDistribution int64                 `protobuf:"varint,4,opt,name=last_distribution,json=lastDistribution,proto3" json:"last_distribution,omitempty"`
}

func (m *ValidatorSubsidyPool) Reset()         { *m = ValidatorSubsidyPool{} }
func (m *ValidatorSubsidyPool) String() string { return proto.CompactTextString(m) }
func (*ValidatorSubsidyPool) ProtoMessage()    {}
func (*ValidatorSubsidyPool) Descriptor() ([]byte, []int) {
	return fileDescriptor_defac9f3380bb921, []int{0}
}
func (m *ValidatorSubsidyPool) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ValidatorSubsidyPool) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ValidatorSubsidyPool.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ValidatorSubsidyPool) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidatorSubsidyPool.Merge(m, src)
}
func (m *ValidatorSubsidyPool) XXX_Size() int {
	return m.Size()
}
func (m *ValidatorSubsidyPool) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidatorSubsidyPool.DiscardUnknown(m)
}

var xxx_messageInfo_ValidatorSubsidyPool proto.InternalMessageInfo

// ValidatorSubsidyRecord tracks individual validator subsidies
type ValidatorSubsidyRecord struct {
	ValidatorAddress      string                `protobuf:"bytes,1,opt,name=validator_address,json=validatorAddress,proto3" json:"validator_address,omitempty"`
	OperatorAddress       string                `protobuf:"bytes,2,opt,name=operator_address,json=operatorAddress,proto3" json:"operator_address,omitempty"`
	MonthlyAllocation     cosmossdk_io_math.Int `protobuf:"bytes,3,opt,name=monthly_allocation,json=monthlyAllocation,proto3,customtype=cosmossdk.io/math.Int" json:"monthly_allocation"`
	TotalReceived         cosmossdk_io_math.Int `protobuf:"bytes,4,opt,name=total_received,json=totalReceived,proto3,customtype=cosmossdk.io/math.Int" json:"total_received"`
	RegisteredAt          int64                 `protobuf:"varint,5,opt,name=registered_at,json=registeredAt,proto3" json:"registered_at,omitempty"`
	LastPayment           int64                 `protobuf:"varint,6,opt,name=last_payment,json=lastPayment,proto3" json:"last_payment,omitempty"`
	Status                ValidatorStatus       `protobuf:"varint,7,opt,name=status,proto3,enum=aequitas.validatorsubsidy.v1.ValidatorStatus" json:"status,omitempty"`
	InfrastructureCostUsd string                `protobuf:"bytes,8,opt,name=infrastructure_cost_usd,json=infrastructureCostUsd,proto3" json:"infrastructure_cost_usd,omitempty"`
	EmergencyBufferUsd    string                `protobuf:"bytes,9,opt,name=emergency_buffer_usd,json=emergencyBufferUsd,proto3" json:"emergency_buffer_usd,omitempty"`
}

func (m *ValidatorSubsidyRecord) Reset()         { *m = ValidatorSubsidyRecord{} }
func (m *ValidatorSubsidyRecord) String() string { return proto.CompactTextString(m) }
func (*ValidatorSubsidyRecord) ProtoMessage()    {}
func (*ValidatorSubsidyRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_defac9f3380bb921, []int{1}
}
func (m *ValidatorSubsidyRecord) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ValidatorSubsidyRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ValidatorSubsidyRecord.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ValidatorSubsidyRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidatorSubsidyRecord.Merge(m, src)
}
func (m *ValidatorSubsidyRecord) XXX_Size() int {
	return m.Size()
}
func (m *ValidatorSubsidyRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidatorSubsidyRecord.DiscardUnknown(m)
}

var xxx_messageInfo_ValidatorSubsidyRecord proto.InternalMessageInfo

// SubsidyPayment represents a subsidy distribution event
type SubsidyPayment struct {
	Id               string                `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ValidatorAddress string                `protobuf:"bytes,2,opt,name=validator_address,json=validatorAddress,proto3" json:"validator_address,omitempty"`
	Amount           cosmossdk_io_math.Int `protobuf:"bytes,3,opt,name=amount,proto3,customtype=cosmossdk.io/math.Int" json:"amount"`
	Timestamp        int64                 `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Type             PaymentType           `protobuf:"varint,5,opt,name=type,proto3,enum=aequitas.validatorsubsidy.v1.PaymentType" json:"type,omitempty"`
	TxHash           string                `protobuf:"bytes,6,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	Notes            string                `protobuf:"bytes,7,opt,name=notes,proto3" json:"notes,omitempty"`
}

func (m *SubsidyPayment) Reset()         { *m = SubsidyPayment{} }
func (m *SubsidyPayment) String() string { return proto.CompactTextString(m) }
func (*SubsidyPayment) ProtoMessage()    {}
func (*SubsidyPayment) Descriptor() ([]byte, []int) {
	return fileDescriptor_defac9f3380bb921, []int{2}
}
func (m *SubsidyPayment) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SubsidyPayment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SubsidyPayment.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SubsidyPayment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubsidyPayment.Merge(m, src)
}
func (m *SubsidyPayment) XXX_Size() int {
	return m.Size()
}
func (m *SubsidyPayment) XXX_DiscardUnknown() {
	xxx_messageInfo_SubsidyPayment.DiscardUnknown(m)
}

var xxx_messageInfo_SubsidyPayment proto.InternalMessageInfo

// SubsidyDistributionSchedule defines when subsidies are distributed
type SubsidyDistributionSchedule struct {
	DistributionIntervalSeconds int64  `protobuf:"varint,1,opt,name=distribution_interval_seconds,json=distributionIntervalSeconds,proto3" json:"distribution_interval_seconds,omitempty"`
	NextDistribution            int64  `protobuf:"varint,2,opt,name=next_distribution,json=nextDistribution,proto3" json:"next_distribution,omitempty"`
	AutoDistribute              bool   `protobuf:"varint,3,opt,name=auto_distribute,json=autoDistribute,proto3" json:"auto_distribute,omitempty"`
	MinValidatorUptimePercent   string `protobuf:"bytes,4,opt,name=min_validator_uptime_percent,json=minValidatorUptimePercent,proto3" json:"min_validator_uptime_percent,omitempty"`
}

func (m *SubsidyDistributionSchedule) Reset()         { *m = SubsidyDistributionSchedule{} }
func (m *SubsidyDistributionSchedule) String() string { return proto.CompactTextString(m) }
func (*SubsidyDistributionSchedule) ProtoMessage()    {}
func (*SubsidyDistributionSchedule) Descriptor() ([]byte, []int) {
	return fileDescriptor_defac9f3380bb921, []int{3}
}
func (m *SubsidyDistributionSchedule) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SubsidyDistributionSchedule) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SubsidyDistributionSchedule.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SubsidyDistributionSchedule) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubsidyDistributionSchedule.Merge(m, src)
}
func (m *SubsidyDistributionSchedule) XXX_Size() int {
	return m.Size()
}
func (m *SubsidyDistributionSchedule) XXX_DiscardUnknown() {
	xxx_messageInfo_SubsidyDistributionSchedule.DiscardUnknown(m)
}

var xxx_messageInfo_SubsidyDistributionSchedule proto.InternalMessageInfo

func init() {
	proto.RegisterEnum("aequitas.validatorsubsidy.v1.ValidatorStatus", ValidatorStatus_name, ValidatorStatus_value)
	proto.RegisterEnum("aequitas.validatorsubsidy.v1.PaymentType", PaymentType_name, PaymentType_value)
	proto.RegisterType((*ValidatorSubsidyPool)(nil), "aequitas.validatorsubsidy.v1.ValidatorSubsidyPool")
	proto.RegisterType((*ValidatorSubsidyRecord)(nil), "aequitas.validatorsubsidy.v1.ValidatorSubsidyRecord")
	proto.RegisterType((*SubsidyPayment)(nil), "aequitas.validatorsubsidy.v1.SubsidyPayment")
	proto.RegisterType((*SubsidyDistributionSchedule)(nil), "aequitas.validatorsubsidy.v1.SubsidyDistributionSchedule")
}

func init() {
	proto.RegisterFile("aequitas/validatorsubsidy/v1/validatorsubsidy.proto", fileDescriptor_defac9f3380bb921)
}

var fileDescriptor_defac9f3380bb921 = []byte{
	// 995 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x56, 0xbf, 0x6f, 0xdb, 0x46,
	0x14, 0x16, 0x65, 0xc7, 0x89, 0x2f, 0x89, 0x4c, 0x1f, 0x9c, 0x5a, 0xb6, 0x15, 0xd9, 0x75, 0x86,
	0xb8, 0x09, 0x2c, 0x35, 0x09, 0xd0, 0xa1, 0x45, 0x51, 0x50, 0x22, 0x93, 0x10, 0x88, 0x65, 0xe2,
	0x48, 0xba, 0x71, 0x96, 0xc3, 0x89, 0x3c, 0x4b, 0x44, 0x45, 0x9e, 0x7a, 0x77, 0x14, 0xac, 0xb5,
	0x53, 0xc7, 0xfe, 0x09, 0xf9, 0x0f, 0xba, 0x64, 0xe9, 0xda, 0x29, 0x63, 0x9a, 0xa5, 0x45, 0x87,
	0xa0, 0xb0, 0x97, 0xfe, 0x19, 0x05, 0x7f, 0xe8, 0x97, 0xd5, 0xa6, 0xb0, 0x37, 0xf1, 0x7d, 0xdf,
	0xfb, 0x78, 0xef, 0x7d, 0xef, 0x9d, 0x08, 0x9e, 0x10, 0xfa, 0x7d, 0x1c, 0x48, 0x22, 0xea, 0x03,
	0xd2, 0x0b, 0x7c, 0x22, 0x19, 0x17, 0x71, 0x5b, 0x04, 0xfe, 0xb0, 0x3e, 0x78, 0x34, 0x17, 0xab,
	0xf5, 0x39, 0x93, 0x0c, 0x56, 0x46, 0x49, 0xb5, 0x39, 0xc2, 0xe0, 0xd1, 0xe6, 0x5a, 0x87, 0x75,
	0x58, 0x4a, 0xac, 0x27, 0xbf, 0xb2, 0x9c, 0xcd, 0x0d, 0x8f, 0x89, 0x90, 0x09, 0x9c, 0x01, 0xd9,
	0x43, 0x06, 0xed, 0xfe, 0x56, 0x04, 0x6b, 0x47, 0x23, 0x21, 0x3b, 0x13, 0xb2, 0x18, 0xeb, 0x41,
	0x07, 0xac, 0x48, 0x26, 0x49, 0x0f, 0x93, 0x5e, 0x8f, 0x79, 0x44, 0x52, 0xbf, 0xac, 0xec, 0x28,
	0x7b, 0xcb, 0x8d, 0x87, 0x6f, 0x3f, 0x6c, 0x17, 0xfe, 0xfc, 0xb0, 0x7d, 0x27, 0xd3, 0x11, 0xfe,
	0x77, 0xb5, 0x80, 0xd5, 0x43, 0x22, 0xbb, 0x35, 0x33, 0x92, 0xef, 0xdf, 0xec, 0x83, 0xfc, 0x05,
	0x66, 0x24, 0x51, 0x29, 0xd5, 0xd0, 0x46, 0x12, 0x10, 0x81, 0x52, 0xc8, 0x22, 0xd9, 0xed, 0x0d,
	0x71, 0x3b, 0xf6, 0x3b, 0x54, 0x96, 0x8b, 0x97, 0x17, 0xbd, 0x9d, 0x4b, 0x34, 0x52, 0x05, 0xf8,
	0x12, 0xac, 0xd2, 0x90, 0xf2, 0x0e, 0x8d, 0xbc, 0x21, 0xe6, 0x54, 0x50, 0x3e, 0xa0, 0xe5, 0x85,
	0xcb, 0xcb, 0xaa, 0x63, 0x15, 0x94, 0x89, 0xc0, 0x87, 0x60, 0xb5, 0x47, 0x84, 0xc4, 0x7e, 0x20,
	0x24, 0x0f, 0xda, 0xb1, 0x0c, 0x58, 0x54, 0x5e, 0xdc, 0x51, 0xf6, 0x16, 0x90, 0x9a, 0x00, 0xfa,
	0x54, 0xfc, 0xcb, 0x1b, 0x3f, 0xbe, 0xde, 0x2e, 0xfc, 0xfd, 0x7a, 0x5b, 0xd9, 0xfd, 0x7d, 0x11,
	0x7c, 0x72, 0xb1, 0xa7, 0x88, 0x7a, 0x8c, 0xfb, 0xd0, 0x00, 0xab, 0x63, 0xdb, 0x30, 0xf1, 0x7d,
	0x4e, 0x85, 0xc8, 0xfb, 0x5a, 0x7e, 0xff, 0x66, 0x7f, 0x2d, 0x3f, 0x8e, 0x96, 0x21, 0xb6, 0xe4,
	0x41, 0xd4, 0x41, 0xea, 0x38, 0x25, 0x8f, 0xc3, 0x26, 0x50, 0x59, 0x9f, 0xf2, 0x19, 0x95, 0xe2,
	0xff, 0xa8, 0xac, 0x8c, 0x32, 0x46, 0x22, 0xaf, 0x00, 0x1c, 0x79, 0x91, 0x7b, 0x9c, 0x94, 0x77,
	0x85, 0xc6, 0xad, 0xe6, 0x32, 0xda, 0x58, 0x25, 0xf1, 0x39, 0x9b, 0x1e, 0x4e, 0x3d, 0x1a, 0x0c,
	0xa8, 0x9f, 0xb6, 0xed, 0xb2, 0x3e, 0xa7, 0x12, 0x28, 0x57, 0x80, 0xf7, 0xc0, 0x6d, 0x4e, 0x3b,
	0x81, 0x90, 0x94, 0x53, 0x1f, 0x13, 0x59, 0xbe, 0x96, 0x3a, 0x71, 0x6b, 0x12, 0xd4, 0x24, 0xfc,
	0x14, 0xdc, 0x4a, 0x2d, 0xeb, 0x93, 0x61, 0x48, 0x23, 0x59, 0x5e, 0x4a, 0x39, 0x37, 0x93, 0x98,
	0x95, 0x85, 0xa0, 0x01, 0x96, 0x84, 0x24, 0x32, 0x16, 0xe5, 0xeb, 0x3b, 0xca, 0x5e, 0xe9, 0xf1,
	0x7e, 0xed, 0x63, 0x2b, 0x55, 0x9b, 0x38, 0x99, 0x26, 0xa1, 0x3c, 0x19, 0x7e, 0x01, 0xd6, 0x83,
	0xe8, 0x84, 0x13, 0x21, 0x79, 0xec, 0xc9, 0x98, 0x53, 0xec, 0x31, 0x21, 0x71, 0x2c, 0xfc, 0xf2,
	0x8d, 0xa4, 0x56, 0x74, 0x67, 0x16, 0x6e, 0x32, 0x21, 0x5d, 0xe1, 0xc3, 0xcf, 0xc1, 0xda, 0x64,
	0x5c, 0xdb, 0xf1, 0xc9, 0x09, 0xe5, 0x69, 0xd2, 0x72, 0x9a, 0x04, 0xc7, 0x58, 0x23, 0x85, 0x5c,
	0xe1, 0x4f, 0x4d, 0xd6, 0xaf, 0x45, 0x50, 0x1a, 0x2d, 0x69, 0x5e, 0x4d, 0x09, 0x14, 0x83, 0x7c,
	0x35, 0x51, 0x31, 0xf8, 0x8f, 0x09, 0x2b, 0x5e, 0x61, 0xc2, 0x96, 0x48, 0xc8, 0xe2, 0x48, 0x5e,
	0x65, 0x20, 0xf2, 0x54, 0x58, 0x01, 0xcb, 0x32, 0x08, 0xa9, 0x90, 0x24, 0xec, 0xe7, 0x7b, 0x33,
	0x09, 0xc0, 0xaf, 0xc1, 0xa2, 0x1c, 0xf6, 0x69, 0x6a, 0x63, 0xe9, 0xf1, 0x67, 0x1f, 0x77, 0x21,
	0x2f, 0xd7, 0x19, 0xf6, 0x29, 0x4a, 0xd3, 0xe0, 0x3a, 0xb8, 0x2e, 0x4f, 0x71, 0x97, 0x88, 0x6e,
	0x6a, 0xf2, 0x32, 0x5a, 0x92, 0xa7, 0xcf, 0x89, 0xe8, 0xc2, 0x35, 0x70, 0x2d, 0x62, 0x92, 0x66,
	0xf6, 0x2e, 0xa3, 0xec, 0x61, 0xaa, 0x89, 0x3f, 0x14, 0xc1, 0x56, 0xde, 0xc4, 0xe9, 0x05, 0xb6,
	0xbd, 0x2e, 0xf5, 0xe3, 0x1e, 0x85, 0x0d, 0x70, 0x77, 0x7a, 0xe1, 0x71, 0x10, 0x49, 0xca, 0x07,
	0xa4, 0x87, 0x05, 0xf5, 0x58, 0xe4, 0x67, 0xfb, 0xba, 0x80, 0xb6, 0xa6, 0x49, 0x66, 0xce, 0xb1,
	0x33, 0x4a, 0x72, 0x73, 0x44, 0xf4, 0xf4, 0xc2, 0xcd, 0x51, 0xcc, 0x6e, 0x8e, 0x04, 0x98, 0x7e,
	0x31, 0xbc, 0x0f, 0x56, 0x48, 0x2c, 0xd9, 0x84, 0x9c, 0x5d, 0x5f, 0x37, 0x50, 0x29, 0x09, 0x8f,
	0xa9, 0x14, 0x7e, 0x03, 0x2a, 0x61, 0x10, 0xe1, 0x89, 0xbf, 0x71, 0x3f, 0x69, 0x27, 0xee, 0x53,
	0xee, 0x25, 0xc3, 0x9e, 0xee, 0x18, 0xda, 0x08, 0x83, 0x68, 0x3c, 0xb4, 0x6e, 0xca, 0xb0, 0x32,
	0xc2, 0xa4, 0x09, 0x0f, 0x7e, 0x56, 0xc0, 0xca, 0x85, 0xc9, 0x86, 0x3b, 0xa0, 0x72, 0xa4, 0xbd,
	0x30, 0x75, 0xcd, 0x39, 0x44, 0xd8, 0x76, 0x34, 0xc7, 0xb5, 0xb1, 0xdb, 0xb2, 0x2d, 0xa3, 0x69,
	0x3e, 0x35, 0x0d, 0x5d, 0x2d, 0xc0, 0x2d, 0xb0, 0x3e, 0xc7, 0xd0, 0x9a, 0x8e, 0x79, 0x64, 0xa8,
	0x0a, 0xbc, 0x0b, 0x36, 0xe6, 0x40, 0xb3, 0x95, 0xc3, 0x45, 0x58, 0x05, 0x9b, 0x73, 0xb0, 0xed,
	0xda, 0x96, 0xd1, 0xd2, 0x0d, 0x5d, 0x5d, 0xf8, 0x57, 0xfc, 0x19, 0xd2, 0x74, 0x57, 0x73, 0x0c,
	0x5d, 0x5d, 0x7c, 0xf0, 0x8b, 0x02, 0x6e, 0x4e, 0x4d, 0x01, 0xac, 0x80, 0xb2, 0xa5, 0x1d, 0x1f,
	0x18, 0x2d, 0x07, 0x3b, 0xc7, 0x96, 0x71, 0xe1, 0xa4, 0x3b, 0xa0, 0x32, 0x83, 0x1e, 0x1c, 0xb6,
	0x9c, 0xe7, 0x2f, 0x8e, 0xb1, 0xed, 0x36, 0x6c, 0x53, 0x3f, 0x56, 0x15, 0xb8, 0x0b, 0xaa, 0x33,
	0x0c, 0xe3, 0xc0, 0x40, 0xcf, 0x8c, 0x56, 0xf3, 0x18, 0x1b, 0x2f, 0x2d, 0xa3, 0x65, 0x27, 0x67,
	0xbe, 0x0f, 0xee, 0xcd, 0x70, 0xcc, 0xd6, 0x53, 0xa4, 0xd9, 0x0e, 0x72, 0x9b, 0x8e, 0x8b, 0x0c,
	0xec, 0x5a, 0xc9, 0x01, 0x0d, 0x75, 0x21, 0xa9, 0x7d, 0x86, 0xd8, 0x38, 0x6c, 0xb9, 0x36, 0x46,
	0xc6, 0xb7, 0x1a, 0xd2, 0xd5, 0xc5, 0x86, 0xfb, 0xf6, 0xac, 0xaa, 0xbc, 0x3b, 0xab, 0x2a, 0x7f,
	0x9d, 0x55, 0x95, 0x9f, 0xce, 0xab, 0x85, 0x77, 0xe7, 0xd5, 0xc2, 0x1f, 0xe7, 0xd5, 0xc2, 0xab,
	0xaf, 0x3a, 0x81, 0xec, 0xc6, 0xed, 0x9a, 0xc7, 0xc2, 0x7a, 0x93, 0x53, 0xa6, 0x6b, 0x07, 0x87,
	0x75, 0x64, 0x58, 0x1a, 0xaa, 0x8f, 0xbf, 0x0e, 0x4e, 0xe7, 0xbf, 0x0f, 0x92, 0x0d, 0x10, 0xed,
	0xa5, 0xf4, 0x3f, 0xfc, 0xc9, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x1e, 0xcc, 0x35, 0x6b, 0x49,
	0x08, 0x00, 0x00,
}

func (this *ValidatorSubsidyPool) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*ValidatorSubsidyPool)
	if !ok {
		that2, ok := that.(ValidatorSubsidyPool)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.TotalAllocated.Equal(that1.TotalAllocated) {
		return false
	}
	if !this.MonthlyBudget.Equal(that1.MonthlyBudget) {
		return false
	}
	if !this.EmergencyReserve.Equal(that1.EmergencyReserve) {
		return false
	}
	if this.LastDistribution != that1.LastDistribution {
		return false
	}
	return true
}
func (this *ValidatorSubsidyRecord) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*ValidatorSubsidyRecord)
	if !ok {
		that2, ok := that.(ValidatorSubsidyRecord)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.ValidatorAddress != that1.ValidatorAddress {
		return false
	}
	if this.OperatorAddress != that1.OperatorAddress {
		return false
	}
	if !this.MonthlyAllocation.Equal(that1.MonthlyAllocation) {
		return false
	}
	if !this.TotalReceived.Equal(that1.TotalReceived) {
		return false
	}
	if this.RegisteredAt != that1.RegisteredAt {
		return false
	}
	if this.LastPayment != that1.LastPayment {
		return false
	}
	if this.Status != that1.Status {
		return false
	}
	if this.InfrastructureCostUsd != that1.InfrastructureCostUsd {
		return false
	}
	if this.EmergencyBufferUsd != that1.EmergencyBufferUsd {
		return false
	}
	return true
}
func (this *SubsidyPayment) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*SubsidyPayment)
	if !ok {
		that2, ok := that.(SubsidyPayment)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Id != that1.Id {
		return false
	}
	if this.ValidatorAddress != that1.ValidatorAddress {
		return false
	}
	if !this.Amount.Equal(that1.Amount) {
		return false
	}
	if this.Timestamp != that1.Timestamp {
		return false
	}
	if this.Type != that1.Type {
		return false
	}
	if this.TxHash != that1.TxHash {
		return false
	}
	if this.Notes != that1.Notes {
		return false
	}
	return true
}
func (this *SubsidyDistributionSchedule) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*SubsidyDistributionSchedule)
	if !ok {
		that2, ok := that.(SubsidyDistributionSchedule)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.DistributionIntervalSeconds != that1.DistributionIntervalSeconds {
		return false
	}
	if this.NextDistribution != that1.NextDistribution {
		return false
	}
	if this.AutoDistribute != that1.AutoDistribute {
		return false
	}
	if this.MinValidatorUptimePercent != that1.MinValidatorUptimePercent {
		return false
	}
	return true
}
func (m *ValidatorSubsidyPool) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ValidatorSubsidyPool) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ValidatorSubsidyPool) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.LastDistribution != 0 {
		i = encodeVarintValidatorsubsidy(dAtA, i, uint64(m.LastDistribution))
		i--
		dAtA[i] = 0x20
	}
	{
		size := m.EmergencyReserve.Size()
		i -= size
		if _, err := m.EmergencyReserve.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintValidatorsubsidy(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	{
		size := m.MonthlyBudget.Size()
		i -= size
		if _, err := m.MonthlyBudget.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintValidatorsubsidy(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	{
		size := m.TotalAllocated.Size()
		i -= size
		if _, err := m.TotalAllocated.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintValidatorsubsidy(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *ValidatorSubsidyRecord) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ValidatorSubsidyRecord) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ValidatorSubsidyRecord) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.EmergencyBufferUsd) > 0 {
		i -= len(m.EmergencyBufferUsd)
		copy(dAtA[i:], m.EmergencyBufferUsd)
		i = encodeVarintValidatorsubsidy(dAtA, i, uint64(len(m.EmergencyBufferUsd)))
		i--
		dAtA[i] = 0x4a
	}
	if len(m.InfrastructureCostUsd) > 0 {
		i -= len(m.InfrastructureCostUsd)
		copy(dAtA[i:], m.InfrastructureCostUsd)
		i = encodeVarintValidatorsubsidy(dAtA, i, uint64(len(m.InfrastructureCostUsd)))
		i--
		dAtA[i] = 0x42
	}
	if m.Status != 0 {
		i = encodeVarintValidatorsubsidy(dAtA, i, uint64(m.Status))
		i--
		dAtA[i] = 0x38
	}
	if m.LastPayment != 0 {
		i = encodeVarintValidatorsubsidy(dAtA, i, uint64(m.LastPayment))
		i--
		dAtA[i] = 0x30
	}
	if m.RegisteredAt != 0 {
		i = encodeVarintValidatorsubsidy(dAtA, i, uint64(m.RegisteredAt))
		i--
		dAtA[i] = 0x28
	}
	{
		size := m.TotalReceived.Size()
		i -= size
		if _, err := m.TotalReceived.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintValidatorsubsidy(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	{
		size := m.MonthlyAllocation.Size()
		i -= size
		if _, err := m.MonthlyAllocation.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintValidatorsubsidy(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	if len(m.OperatorAddress) > 0 {
		i -= len(m.OperatorAddress)
		copy(dAtA[i:], m.OperatorAddress)
		i = encodeVarintValidatorsubsidy(dAtA, i, uint64(len(m.OperatorAddress)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.ValidatorAddress) > 0 {
		i -= len(m.ValidatorAddress)
		copy(dAtA[i:], m.ValidatorAddress)
		i = encodeVarintValidatorsubsidy(dAtA, i, uint64(len(m.ValidatorAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *SubsidyPayment) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SubsidyPayment) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SubsidyPayment) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Notes) > 0 {
		i -= len(m.Notes)
		copy(dAtA[i:], m.Notes)
		i = encodeVarintValidatorsubsidy(dAtA, i, uint64(len(m.Notes)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.TxHash) > 0 {
		i -= len(m.TxHash)
		copy(dAtA[i:], m.TxHash)
		i = encodeVarintValidatorsubsidy(dAtA, i, uint64(len(m.TxHash)))
		i--
		dAtA[i] = 0x32
	}
	if m.Type != 0 {
		i = encodeVarintValidatorsubsidy(dAtA, i, uint64(m.Type))
		i--
		dAtA[i] = 0x28
	}
	if m.Timestamp != 0 {
		i = encodeVarintValidatorsubsidy(dAtA, i, uint64(m.Timestamp))
		i--
		dAtA[i] = 0x20
	}
	{
		size := m.Amount.Size()
		i -= size
		if _, err := m.Amount.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintValidatorsubsidy(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	if len(m.ValidatorAddress) > 0 {
		i -= len(m.ValidatorAddress)
		copy(dAtA[i:], m.ValidatorAddress)
		i = encodeVarintValidatorsubsidy(dAtA, i, uint64(len(m.ValidatorAddress)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Id) > 0 {
		i -= len(m.Id)
		copy(dAtA[i:], m.Id)
		i = encodeVarintValidatorsubsidy(dAtA, i, uint64(len(m.Id)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *SubsidyDistributionSchedule) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SubsidyDistributionSchedule) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SubsidyDistributionSchedule) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.MinValidatorUptimePercent) > 0 {
		i -= len(m.MinValidatorUptimePercent)
		copy(dAtA[i:], m.MinValidatorUptimePercent)
		i = encodeVarintValidatorsubsidy(dAtA, i, uint64(len(m.MinValidatorUptimePercent)))
		i--
		dAtA[i] = 0x22
	}
	if m.AutoDistribute {
		i--
		if m.AutoDistribute {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x18
	}
	if m.NextDistribution != 0 {
		i = encodeVarintValidatorsubsidy(dAtA, i, uint64(m.NextDistribution))
		i--
		dAtA[i] = 0x10
	}
	if m.DistributionIntervalSeconds != 0 {
		i = encodeVarintValidatorsubsidy(dAtA, i, uint64(m.DistributionIntervalSeconds))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintValidatorsubsidy(dAtA []byte, offset int, v uint64) int {
	offset -= sovValidatorsubsidy(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *ValidatorSubsidyPool) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.TotalAllocated.Size()
	n += 1 + l + sovValidatorsubsidy(uint64(l))
	l = m.MonthlyBudget.Size()
	n += 1 + l + sovValidatorsubsidy(uint64(l))
	l = m.EmergencyReserve.Size()
	n += 1 + l + sovValidatorsubsidy(uint64(l))
	if m.LastDistribution != 0 {
		n += 1 + sovValidatorsubsidy(uint64(m.LastDistribution))
	}
	return n
}

func (m *ValidatorSubsidyRecord) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ValidatorAddress)
	if l > 0 {
		n += 1 + l + sovValidatorsubsidy(uint64(l))
	}
	l = len(m.OperatorAddress)
	if l > 0 {
		n += 1 + l + sovValidatorsubsidy(uint64(l))
	}
	l = m.MonthlyAllocation.Size()
	n += 1 + l + sovValidatorsubsidy(uint64(l))
	l = m.TotalReceived.Size()
	n += 1 + l + sovValidatorsubsidy(uint64(l))
	if m.RegisteredAt != 0 {
		n += 1 + sovValidatorsubsidy(uint64(m.RegisteredAt))
	}
	if m.LastPayment != 0 {
		n += 1 + sovValidatorsubsidy(uint64(m.LastPayment))
	}
	if m.Status != 0 {
		n += 1 + sovValidatorsubsidy(uint64(m.Status))
	}
	l = len(m.InfrastructureCostUsd)
	if l > 0 {
		n += 1 + l + sovValidatorsubsidy(uint64(l))
	}
	l = len(m.EmergencyBufferUsd)
	if l > 0 {
		n += 1 + l + sovValidatorsubsidy(uint64(l))
	}
	return n
}

func (m *SubsidyPayment) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Id)
	if l > 0 {
		n += 1 + l + sovValidatorsubsidy(uint64(l))
	}
	l = len(m.ValidatorAddress)
	if l > 0 {
		n += 1 + l + sovValidatorsubsidy(uint64(l))
	}
	l = m.Amount.Size()
	n += 1 + l + sovValidatorsubsidy(uint64(l))
	if m.Timestamp != 0 {
		n += 1 + sovValidatorsubsidy(uint64(m.Timestamp))
	}
	if m.Type != 0 {
		n += 1 + sovValidatorsubsidy(uint64(m.Type))
	}
	l = len(m.TxHash)
	if l > 0 {
		n += 1 + l + sovValidatorsubsidy(uint64(l))
	}
	l = len(m.Notes)
	if l > 0 {
		n += 1 + l + sovValidatorsubsidy(uint64(l))
	}
	return n
}

func (m *SubsidyDistributionSchedule) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.DistributionIntervalSeconds != 0 {
		n += 1 + sovValidatorsubsidy(uint64(m.DistributionIntervalSeconds))
	}
	if m.NextDistribution != 0 {
		n += 1 + sovValidatorsubsidy(uint64(m.NextDistribution))
	}
	if m.AutoDistribute {
		n += 2
	}
	l = len(m.MinValidatorUptimePercent)
	if l > 0 {
		n += 1 + l + sovValidatorsubsidy(uint64(l))
	}
	return n
}

func sovValidatorsubsidy(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozValidatorsubsidy(x uint64) (n int) {
	return sovValidatorsubsidy(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *ValidatorSubsidyPool) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowValidatorsubsidy
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ValidatorSubsidyPool: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ValidatorSubsidyPool: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalAllocated", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowValidatorsubsidy
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthValidatorsubsidy
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthValidatorsubsidy
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.TotalAllocated.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MonthlyBudget", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowValidatorsubsidy
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthValidatorsubsidy
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthValidatorsubsidy
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.MonthlyBudget.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EmergencyReserve", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowValidatorsubsidy
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthValidatorsubsidy
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthValidatorsubsidy
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.EmergencyReserve.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastDistribution", wireType)
			}
			m.LastDistribution = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowValidatorsubsidy
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LastDistribution |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipValidatorsubsidy(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthValidatorsubsidy
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ValidatorSubsidyRecord) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowValidatorsubsidy
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ValidatorSubsidyRecord: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ValidatorSubsidyRecord: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValidatorAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowValidatorsubsidy
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthValidatorsubsidy
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthValidatorsubsidy
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ValidatorAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OperatorAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowValidatorsubsidy
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthValidatorsubsidy
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthValidatorsubsidy
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OperatorAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MonthlyAllocation", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowValidatorsubsidy
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthValidatorsubsidy
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthValidatorsubsidy
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.MonthlyAllocation.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalReceived", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowValidatorsubsidy
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthValidatorsubsidy
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthValidatorsubsidy
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.TotalReceived.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RegisteredAt", wireType)
			}
			m.RegisteredAt = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowValidatorsubsidy
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RegisteredAt |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastPayment", wireType)
			}
			m.LastPayment = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowValidatorsubsidy
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LastPayment |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			m.Status = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowValidatorsubsidy
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Status |= ValidatorStatus(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field InfrastructureCostUsd", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowValidatorsubsidy
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthValidatorsubsidy
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthValidatorsubsidy
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.InfrastructureCostUsd = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EmergencyBufferUsd", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowValidatorsubsidy
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthValidatorsubsidy
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthValidatorsubsidy
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.EmergencyBufferUsd = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipValidatorsubsidy(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthValidatorsubsidy
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SubsidyPayment) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowValidatorsubsidy
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SubsidyPayment: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SubsidyPayment: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowValidatorsubsidy
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthValidatorsubsidy
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthValidatorsubsidy
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValidatorAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowValidatorsubsidy
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthValidatorsubsidy
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthValidatorsubsidy
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ValidatorAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowValidatorsubsidy
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthValidatorsubsidy
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthValidatorsubsidy
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Amount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Timestamp", wireType)
			}
			m.Timestamp = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowValidatorsubsidy
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Timestamp |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Type", wireType)
			}
			m.Type = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowValidatorsubsidy
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Type |= PaymentType(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TxHash", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowValidatorsubsidy
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthValidatorsubsidy
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthValidatorsubsidy
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TxHash = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Notes", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowValidatorsubsidy
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthValidatorsubsidy
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthValidatorsubsidy
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Notes = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipValidatorsubsidy(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthValidatorsubsidy
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SubsidyDistributionSchedule) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowValidatorsubsidy
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SubsidyDistributionSchedule: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SubsidyDistributionSchedule: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DistributionIntervalSeconds", wireType)
			}
			m.DistributionIntervalSeconds = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowValidatorsubsidy
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DistributionIntervalSeconds |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field NextDistribution", wireType)
			}
			m.NextDistribution = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowValidatorsubsidy
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.NextDistribution |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AutoDistribute", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowValidatorsubsidy
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.AutoDistribute = bool(v != 0)
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinValidatorUptimePercent", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowValidatorsubsidy
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthValidatorsubsidy
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthValidatorsubsidy
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MinValidatorUptimePercent = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipValidatorsubsidy(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthValidatorsubsidy
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipValidatorsubsidy(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowValidatorsubsidy
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowValidatorsubsidy
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowValidatorsubsidy
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthValidatorsubsidy
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupValidatorsubsidy
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthValidatorsubsidy
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthValidatorsubsidy        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowValidatorsubsidy          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupValidatorsubsidy = fmt.Errorf("proto: unexpected end of group")
)
