[supervisord]
nodaemon=true
logfile=/var/log/aequitas/supervisord.log
pidfile=/var/run/supervisord.pid

[program:aequitas-node]
command=/usr/local/bin/docker-entrypoint.sh start
autostart=true
autorestart=true
stdout_logfile=/var/log/aequitas/node-stdout.log
stderr_logfile=/var/log/aequitas/node-stderr.log
user=aequitas
environment=HOME="/home/aequitas",AEQUITAS_HOME="/var/lib/aequitas"
