// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: aequitas/defendant/v1/tx.proto

package types

import (
	context "context"
	cosmossdk_io_math "cosmossdk.io/math"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MsgRecordPayment struct {
	Authority   string                `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	DefendantId string                `protobuf:"bytes,2,opt,name=defendant_id,json=defendantId,proto3" json:"defendant_id,omitempty"`
	Amount      cosmossdk_io_math.Int `protobuf:"bytes,3,opt,name=amount,proto3,customtype=cosmossdk.io/math.Int" json:"amount"`
	Method      PaymentMethod         `protobuf:"varint,4,opt,name=method,proto3,enum=aequitas.defendant.v1.PaymentMethod" json:"method,omitempty"`
	EvidenceCid string                `protobuf:"bytes,5,opt,name=evidence_cid,json=evidenceCid,proto3" json:"evidence_cid,omitempty"`
	Description string                `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
}

func (m *MsgRecordPayment) Reset()         { *m = MsgRecordPayment{} }
func (m *MsgRecordPayment) String() string { return proto.CompactTextString(m) }
func (*MsgRecordPayment) ProtoMessage()    {}
func (*MsgRecordPayment) Descriptor() ([]byte, []int) {
	return fileDescriptor_e86248913b07edf6, []int{0}
}
func (m *MsgRecordPayment) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRecordPayment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRecordPayment.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRecordPayment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRecordPayment.Merge(m, src)
}
func (m *MsgRecordPayment) XXX_Size() int {
	return m.Size()
}
func (m *MsgRecordPayment) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRecordPayment.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRecordPayment proto.InternalMessageInfo

type MsgRecordPaymentResponse struct {
	PaymentId     string                `protobuf:"bytes,1,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	RemainingDebt cosmossdk_io_math.Int `protobuf:"bytes,2,opt,name=remaining_debt,json=remainingDebt,proto3,customtype=cosmossdk.io/math.Int" json:"remaining_debt"`
}

func (m *MsgRecordPaymentResponse) Reset()         { *m = MsgRecordPaymentResponse{} }
func (m *MsgRecordPaymentResponse) String() string { return proto.CompactTextString(m) }
func (*MsgRecordPaymentResponse) ProtoMessage()    {}
func (*MsgRecordPaymentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e86248913b07edf6, []int{1}
}
func (m *MsgRecordPaymentResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRecordPaymentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRecordPaymentResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRecordPaymentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRecordPaymentResponse.Merge(m, src)
}
func (m *MsgRecordPaymentResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgRecordPaymentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRecordPaymentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRecordPaymentResponse proto.InternalMessageInfo

func (m *MsgRecordPaymentResponse) GetPaymentId() string {
	if m != nil {
		return m.PaymentId
	}
	return ""
}

type MsgRecordNonMonetaryContribution struct {
	Authority        string                `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	DefendantId      string                `protobuf:"bytes,2,opt,name=defendant_id,json=defendantId,proto3" json:"defendant_id,omitempty"`
	ContributionType string                `protobuf:"bytes,3,opt,name=contribution_type,json=contributionType,proto3" json:"contribution_type,omitempty"`
	EstimatedValue   cosmossdk_io_math.Int `protobuf:"bytes,4,opt,name=estimated_value,json=estimatedValue,proto3,customtype=cosmossdk.io/math.Int" json:"estimated_value"`
	EvidenceCid      string                `protobuf:"bytes,5,opt,name=evidence_cid,json=evidenceCid,proto3" json:"evidence_cid,omitempty"`
	Description      string                `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
}

func (m *MsgRecordNonMonetaryContribution) Reset()         { *m = MsgRecordNonMonetaryContribution{} }
func (m *MsgRecordNonMonetaryContribution) String() string { return proto.CompactTextString(m) }
func (*MsgRecordNonMonetaryContribution) ProtoMessage()    {}
func (*MsgRecordNonMonetaryContribution) Descriptor() ([]byte, []int) {
	return fileDescriptor_e86248913b07edf6, []int{2}
}
func (m *MsgRecordNonMonetaryContribution) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRecordNonMonetaryContribution) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRecordNonMonetaryContribution.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRecordNonMonetaryContribution) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRecordNonMonetaryContribution.Merge(m, src)
}
func (m *MsgRecordNonMonetaryContribution) XXX_Size() int {
	return m.Size()
}
func (m *MsgRecordNonMonetaryContribution) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRecordNonMonetaryContribution.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRecordNonMonetaryContribution proto.InternalMessageInfo

type MsgRecordNonMonetaryContributionResponse struct {
	ContributionId string `protobuf:"bytes,1,opt,name=contribution_id,json=contributionId,proto3" json:"contribution_id,omitempty"`
}

func (m *MsgRecordNonMonetaryContributionResponse) Reset() {
	*m = MsgRecordNonMonetaryContributionResponse{}
}
func (m *MsgRecordNonMonetaryContributionResponse) String() string { return proto.CompactTextString(m) }
func (*MsgRecordNonMonetaryContributionResponse) ProtoMessage()    {}
func (*MsgRecordNonMonetaryContributionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e86248913b07edf6, []int{3}
}
func (m *MsgRecordNonMonetaryContributionResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRecordNonMonetaryContributionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRecordNonMonetaryContributionResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRecordNonMonetaryContributionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRecordNonMonetaryContributionResponse.Merge(m, src)
}
func (m *MsgRecordNonMonetaryContributionResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgRecordNonMonetaryContributionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRecordNonMonetaryContributionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRecordNonMonetaryContributionResponse proto.InternalMessageInfo

func (m *MsgRecordNonMonetaryContributionResponse) GetContributionId() string {
	if m != nil {
		return m.ContributionId
	}
	return ""
}

type MsgUpdateDefendantStatus struct {
	Authority   string          `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	DefendantId string          `protobuf:"bytes,2,opt,name=defendant_id,json=defendantId,proto3" json:"defendant_id,omitempty"`
	Status      DefendantStatus `protobuf:"varint,3,opt,name=status,proto3,enum=aequitas.defendant.v1.DefendantStatus" json:"status,omitempty"`
}

func (m *MsgUpdateDefendantStatus) Reset()         { *m = MsgUpdateDefendantStatus{} }
func (m *MsgUpdateDefendantStatus) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateDefendantStatus) ProtoMessage()    {}
func (*MsgUpdateDefendantStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_e86248913b07edf6, []int{4}
}
func (m *MsgUpdateDefendantStatus) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateDefendantStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateDefendantStatus.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateDefendantStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateDefendantStatus.Merge(m, src)
}
func (m *MsgUpdateDefendantStatus) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateDefendantStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateDefendantStatus.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateDefendantStatus proto.InternalMessageInfo

type MsgUpdateDefendantStatusResponse struct {
}

func (m *MsgUpdateDefendantStatusResponse) Reset()         { *m = MsgUpdateDefendantStatusResponse{} }
func (m *MsgUpdateDefendantStatusResponse) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateDefendantStatusResponse) ProtoMessage()    {}
func (*MsgUpdateDefendantStatusResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e86248913b07edf6, []int{5}
}
func (m *MsgUpdateDefendantStatusResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateDefendantStatusResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateDefendantStatusResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateDefendantStatusResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateDefendantStatusResponse.Merge(m, src)
}
func (m *MsgUpdateDefendantStatusResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateDefendantStatusResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateDefendantStatusResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateDefendantStatusResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgRecordPayment)(nil), "aequitas.defendant.v1.MsgRecordPayment")
	proto.RegisterType((*MsgRecordPaymentResponse)(nil), "aequitas.defendant.v1.MsgRecordPaymentResponse")
	proto.RegisterType((*MsgRecordNonMonetaryContribution)(nil), "aequitas.defendant.v1.MsgRecordNonMonetaryContribution")
	proto.RegisterType((*MsgRecordNonMonetaryContributionResponse)(nil), "aequitas.defendant.v1.MsgRecordNonMonetaryContributionResponse")
	proto.RegisterType((*MsgUpdateDefendantStatus)(nil), "aequitas.defendant.v1.MsgUpdateDefendantStatus")
	proto.RegisterType((*MsgUpdateDefendantStatusResponse)(nil), "aequitas.defendant.v1.MsgUpdateDefendantStatusResponse")
}

func init() { proto.RegisterFile("aequitas/defendant/v1/tx.proto", fileDescriptor_e86248913b07edf6) }

var fileDescriptor_e86248913b07edf6 = []byte{
	// 680 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x55, 0xcf, 0x4f, 0x13, 0x41,
	0x14, 0xee, 0x82, 0x34, 0x61, 0x90, 0x82, 0x1b, 0xd0, 0xb5, 0x09, 0xdb, 0xda, 0xa8, 0x10, 0x08,
	0xbb, 0x01, 0x8d, 0x24, 0xc6, 0x68, 0xa0, 0x78, 0xe8, 0xa1, 0x48, 0x16, 0xf4, 0xe0, 0xa5, 0x99,
	0xee, 0x8c, 0xdb, 0x89, 0xee, 0xcc, 0xba, 0xf3, 0xb6, 0xa1, 0x37, 0xf5, 0xe4, 0xc5, 0xc4, 0x9b,
	0xf1, 0xc6, 0x9f, 0xc0, 0x81, 0x3f, 0x82, 0x0b, 0x09, 0xe1, 0x64, 0x4c, 0x24, 0x06, 0x0e, 0xf8,
	0x67, 0x98, 0xfd, 0xd1, 0xa5, 0x90, 0x16, 0xc4, 0x84, 0xdb, 0xf6, 0xbd, 0xf7, 0xbd, 0xf7, 0xbd,
	0xef, 0x9b, 0xe9, 0x20, 0x1d, 0xd3, 0xf7, 0x01, 0x03, 0x2c, 0x4d, 0x42, 0xdf, 0x50, 0x4e, 0x30,
	0x07, 0xb3, 0x39, 0x67, 0xc2, 0x86, 0xe1, 0xf9, 0x02, 0x84, 0x3a, 0xde, 0xce, 0x1b, 0x69, 0xde,
	0x68, 0xce, 0xe5, 0x6f, 0xd9, 0x42, 0xba, 0x42, 0x9a, 0xae, 0x74, 0xc2, 0x72, 0x57, 0x3a, 0x71,
	0x7d, 0x7e, 0xcc, 0x11, 0x8e, 0x88, 0x3e, 0xcd, 0xf0, 0x2b, 0x89, 0xde, 0x8e, 0xcb, 0x6b, 0x71,
	0x22, 0xfe, 0x91, 0xa4, 0xee, 0x75, 0x27, 0x70, 0x32, 0x2d, 0x2a, 0x2b, 0xed, 0xf6, 0xa1, 0xd1,
	0xaa, 0x74, 0x2c, 0x6a, 0x0b, 0x9f, 0xac, 0xe2, 0x96, 0x4b, 0x39, 0xa8, 0x8f, 0xd0, 0x20, 0x0e,
	0xa0, 0x21, 0x7c, 0x06, 0x2d, 0x4d, 0x29, 0x2a, 0x53, 0x83, 0x4b, 0xda, 0xfe, 0xf6, 0xec, 0x58,
	0x32, 0x60, 0x91, 0x10, 0x9f, 0x4a, 0xb9, 0x06, 0x3e, 0xe3, 0x8e, 0x75, 0x52, 0xaa, 0xde, 0x41,
	0xd7, 0xd3, 0xfe, 0x35, 0x46, 0xb4, 0xbe, 0x10, 0x6a, 0x0d, 0xa5, 0xb1, 0x0a, 0x51, 0xcb, 0x28,
	0x8b, 0x5d, 0x11, 0x70, 0xd0, 0xfa, 0xa3, 0xbe, 0x33, 0x3b, 0x07, 0x85, 0xcc, 0xcf, 0x83, 0xc2,
	0x78, 0xdc, 0x5b, 0x92, 0xb7, 0x06, 0x13, 0xa6, 0x8b, 0xa1, 0x61, 0x54, 0x38, 0xec, 0x6f, 0xcf,
	0xa2, 0x64, 0x68, 0x85, 0x83, 0x95, 0x40, 0xd5, 0x27, 0x28, 0xeb, 0x52, 0x68, 0x08, 0xa2, 0x5d,
	0x2b, 0x2a, 0x53, 0xb9, 0xf9, 0xbb, 0x46, 0x57, 0x35, 0x8d, 0x64, 0x9f, 0x6a, 0x54, 0x6b, 0x25,
	0x98, 0x90, 0x25, 0x6d, 0x32, 0x42, 0xb9, 0x4d, 0x6b, 0x36, 0x23, 0xda, 0x40, 0xcc, 0xb2, 0x1d,
	0x2b, 0x33, 0xa2, 0x16, 0xd1, 0x10, 0xa1, 0xd2, 0xf6, 0x99, 0x07, 0x4c, 0x70, 0x2d, 0xdb, 0xde,
	0x23, 0x0d, 0x3d, 0xbe, 0xf9, 0x79, 0xb3, 0x90, 0xf9, 0xb3, 0x59, 0xc8, 0x7c, 0x3a, 0xde, 0x9a,
	0x3e, 0x91, 0xa0, 0xf4, 0x45, 0x41, 0xda, 0x59, 0x3d, 0x2d, 0x2a, 0x3d, 0xc1, 0x25, 0x55, 0x27,
	0x10, 0xf2, 0xe2, 0x50, 0xa8, 0x4e, 0x24, 0xac, 0x35, 0x98, 0x44, 0x2a, 0x44, 0xb5, 0x50, 0xce,
	0xa7, 0x2e, 0x66, 0x9c, 0x71, 0xa7, 0x46, 0x68, 0x1d, 0x62, 0x01, 0x2f, 0xa7, 0xd1, 0x70, 0xda,
	0x62, 0x99, 0xd6, 0xa1, 0xf4, 0xab, 0x0f, 0x15, 0x53, 0x3e, 0x2b, 0x82, 0x57, 0x05, 0xa7, 0x80,
	0xfd, 0x56, 0x59, 0x70, 0xf0, 0x59, 0x3d, 0x08, 0x97, 0xb9, 0x4a, 0xbf, 0x67, 0xd0, 0x0d, 0xbb,
	0x63, 0x54, 0x0d, 0x5a, 0x1e, 0x8d, 0xad, 0xb7, 0x46, 0x3b, 0x13, 0xeb, 0x2d, 0x8f, 0xaa, 0xeb,
	0x68, 0x84, 0x4a, 0x60, 0x2e, 0x06, 0x4a, 0x6a, 0x4d, 0xfc, 0x2e, 0xa0, 0x91, 0xc1, 0x97, 0x54,
	0x20, 0x97, 0xf6, 0x78, 0x15, 0xb6, 0xb8, 0x5a, 0xbf, 0xd7, 0xd0, 0xd4, 0x45, 0xf2, 0xa6, 0xf6,
	0x4f, 0xa2, 0x91, 0x53, 0x5a, 0xa4, 0x67, 0x20, 0xd7, 0x19, 0xae, 0x90, 0xd2, 0x6e, 0x7c, 0x88,
	0x5e, 0x7a, 0x04, 0x03, 0x5d, 0x6e, 0xab, 0xb9, 0x06, 0x18, 0x02, 0x79, 0x95, 0x66, 0x3d, 0x45,
	0x59, 0x19, 0x0d, 0x89, 0x1c, 0xca, 0xcd, 0xdf, 0xef, 0x71, 0xaf, 0xce, 0x50, 0xb2, 0x12, 0x54,
	0x4f, 0x91, 0x4a, 0xd1, 0x19, 0xec, 0xba, 0x4e, 0x5b, 0x9c, 0xf9, 0x6f, 0xfd, 0xa8, 0xbf, 0x2a,
	0x1d, 0x95, 0xa1, 0xe1, 0xd3, 0x7f, 0x46, 0x93, 0x3d, 0x48, 0x9c, 0xbd, 0x65, 0x79, 0xf3, 0x1f,
	0x0b, 0x53, 0x3f, 0xbe, 0x2b, 0x68, 0xe2, 0xfc, 0x8b, 0xb1, 0x70, 0x51, 0xcb, 0x1e, 0xc0, 0xfc,
	0xb3, 0xff, 0x04, 0xa6, 0xdc, 0x3e, 0x2a, 0x68, 0xbc, 0xbb, 0xff, 0xe7, 0xac, 0xd9, 0x15, 0x90,
	0x5f, 0xb8, 0x24, 0xa0, 0xcd, 0x21, 0x3f, 0xf0, 0xe1, 0x78, 0x6b, 0x5a, 0x59, 0x5a, 0xd9, 0x39,
	0xd4, 0x95, 0xbd, 0x43, 0x5d, 0xf9, 0x7d, 0xa8, 0x2b, 0x5f, 0x8f, 0xf4, 0xcc, 0xde, 0x91, 0x9e,
	0xf9, 0x71, 0xa4, 0x67, 0x5e, 0x3f, 0x74, 0x18, 0x34, 0x82, 0xba, 0x61, 0x0b, 0xd7, 0x2c, 0xfb,
	0x54, 0x2c, 0x2f, 0x56, 0x5f, 0x98, 0xd6, 0xf3, 0xd5, 0x45, 0xcb, 0x4c, 0x5f, 0x9f, 0x8d, 0x8e,
	0xf7, 0x27, 0xbc, 0xfc, 0xb2, 0x9e, 0x8d, 0x5e, 0x9e, 0x07, 0x7f, 0x03, 0x00, 0x00, 0xff, 0xff,
	0xc1, 0xc8, 0xb2, 0x84, 0x23, 0x07, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	// RecordPayment records a payment from a defendant
	RecordPayment(ctx context.Context, in *MsgRecordPayment, opts ...grpc.CallOption) (*MsgRecordPaymentResponse, error)
	// RecordNonMonetaryContribution records a non-monetary contribution (African nations)
	RecordNonMonetaryContribution(ctx context.Context, in *MsgRecordNonMonetaryContribution, opts ...grpc.CallOption) (*MsgRecordNonMonetaryContributionResponse, error)
	// UpdateDefendantStatus updates a defendant's status
	UpdateDefendantStatus(ctx context.Context, in *MsgUpdateDefendantStatus, opts ...grpc.CallOption) (*MsgUpdateDefendantStatusResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) RecordPayment(ctx context.Context, in *MsgRecordPayment, opts ...grpc.CallOption) (*MsgRecordPaymentResponse, error) {
	out := new(MsgRecordPaymentResponse)
	err := c.cc.Invoke(ctx, "/aequitas.defendant.v1.Msg/RecordPayment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) RecordNonMonetaryContribution(ctx context.Context, in *MsgRecordNonMonetaryContribution, opts ...grpc.CallOption) (*MsgRecordNonMonetaryContributionResponse, error) {
	out := new(MsgRecordNonMonetaryContributionResponse)
	err := c.cc.Invoke(ctx, "/aequitas.defendant.v1.Msg/RecordNonMonetaryContribution", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) UpdateDefendantStatus(ctx context.Context, in *MsgUpdateDefendantStatus, opts ...grpc.CallOption) (*MsgUpdateDefendantStatusResponse, error) {
	out := new(MsgUpdateDefendantStatusResponse)
	err := c.cc.Invoke(ctx, "/aequitas.defendant.v1.Msg/UpdateDefendantStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	// RecordPayment records a payment from a defendant
	RecordPayment(context.Context, *MsgRecordPayment) (*MsgRecordPaymentResponse, error)
	// RecordNonMonetaryContribution records a non-monetary contribution (African nations)
	RecordNonMonetaryContribution(context.Context, *MsgRecordNonMonetaryContribution) (*MsgRecordNonMonetaryContributionResponse, error)
	// UpdateDefendantStatus updates a defendant's status
	UpdateDefendantStatus(context.Context, *MsgUpdateDefendantStatus) (*MsgUpdateDefendantStatusResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) RecordPayment(ctx context.Context, req *MsgRecordPayment) (*MsgRecordPaymentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RecordPayment not implemented")
}
func (*UnimplementedMsgServer) RecordNonMonetaryContribution(ctx context.Context, req *MsgRecordNonMonetaryContribution) (*MsgRecordNonMonetaryContributionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RecordNonMonetaryContribution not implemented")
}
func (*UnimplementedMsgServer) UpdateDefendantStatus(ctx context.Context, req *MsgUpdateDefendantStatus) (*MsgUpdateDefendantStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateDefendantStatus not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_RecordPayment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgRecordPayment)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).RecordPayment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/aequitas.defendant.v1.Msg/RecordPayment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).RecordPayment(ctx, req.(*MsgRecordPayment))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_RecordNonMonetaryContribution_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgRecordNonMonetaryContribution)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).RecordNonMonetaryContribution(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/aequitas.defendant.v1.Msg/RecordNonMonetaryContribution",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).RecordNonMonetaryContribution(ctx, req.(*MsgRecordNonMonetaryContribution))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_UpdateDefendantStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateDefendantStatus)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateDefendantStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/aequitas.defendant.v1.Msg/UpdateDefendantStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateDefendantStatus(ctx, req.(*MsgUpdateDefendantStatus))
	}
	return interceptor(ctx, in, info, handler)
}

var Msg_serviceDesc = _Msg_serviceDesc
var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "aequitas.defendant.v1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RecordPayment",
			Handler:    _Msg_RecordPayment_Handler,
		},
		{
			MethodName: "RecordNonMonetaryContribution",
			Handler:    _Msg_RecordNonMonetaryContribution_Handler,
		},
		{
			MethodName: "UpdateDefendantStatus",
			Handler:    _Msg_UpdateDefendantStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "aequitas/defendant/v1/tx.proto",
}

func (m *MsgRecordPayment) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRecordPayment) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRecordPayment) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Description) > 0 {
		i -= len(m.Description)
		copy(dAtA[i:], m.Description)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Description)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.EvidenceCid) > 0 {
		i -= len(m.EvidenceCid)
		copy(dAtA[i:], m.EvidenceCid)
		i = encodeVarintTx(dAtA, i, uint64(len(m.EvidenceCid)))
		i--
		dAtA[i] = 0x2a
	}
	if m.Method != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Method))
		i--
		dAtA[i] = 0x20
	}
	{
		size := m.Amount.Size()
		i -= size
		if _, err := m.Amount.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	if len(m.DefendantId) > 0 {
		i -= len(m.DefendantId)
		copy(dAtA[i:], m.DefendantId)
		i = encodeVarintTx(dAtA, i, uint64(len(m.DefendantId)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Authority) > 0 {
		i -= len(m.Authority)
		copy(dAtA[i:], m.Authority)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Authority)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgRecordPaymentResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRecordPaymentResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRecordPaymentResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.RemainingDebt.Size()
		i -= size
		if _, err := m.RemainingDebt.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.PaymentId) > 0 {
		i -= len(m.PaymentId)
		copy(dAtA[i:], m.PaymentId)
		i = encodeVarintTx(dAtA, i, uint64(len(m.PaymentId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgRecordNonMonetaryContribution) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRecordNonMonetaryContribution) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRecordNonMonetaryContribution) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Description) > 0 {
		i -= len(m.Description)
		copy(dAtA[i:], m.Description)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Description)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.EvidenceCid) > 0 {
		i -= len(m.EvidenceCid)
		copy(dAtA[i:], m.EvidenceCid)
		i = encodeVarintTx(dAtA, i, uint64(len(m.EvidenceCid)))
		i--
		dAtA[i] = 0x2a
	}
	{
		size := m.EstimatedValue.Size()
		i -= size
		if _, err := m.EstimatedValue.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	if len(m.ContributionType) > 0 {
		i -= len(m.ContributionType)
		copy(dAtA[i:], m.ContributionType)
		i = encodeVarintTx(dAtA, i, uint64(len(m.ContributionType)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.DefendantId) > 0 {
		i -= len(m.DefendantId)
		copy(dAtA[i:], m.DefendantId)
		i = encodeVarintTx(dAtA, i, uint64(len(m.DefendantId)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Authority) > 0 {
		i -= len(m.Authority)
		copy(dAtA[i:], m.Authority)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Authority)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgRecordNonMonetaryContributionResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRecordNonMonetaryContributionResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRecordNonMonetaryContributionResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ContributionId) > 0 {
		i -= len(m.ContributionId)
		copy(dAtA[i:], m.ContributionId)
		i = encodeVarintTx(dAtA, i, uint64(len(m.ContributionId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgUpdateDefendantStatus) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateDefendantStatus) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateDefendantStatus) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Status != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Status))
		i--
		dAtA[i] = 0x18
	}
	if len(m.DefendantId) > 0 {
		i -= len(m.DefendantId)
		copy(dAtA[i:], m.DefendantId)
		i = encodeVarintTx(dAtA, i, uint64(len(m.DefendantId)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Authority) > 0 {
		i -= len(m.Authority)
		copy(dAtA[i:], m.Authority)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Authority)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgUpdateDefendantStatusResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateDefendantStatusResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateDefendantStatusResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgRecordPayment) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Authority)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.DefendantId)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = m.Amount.Size()
	n += 1 + l + sovTx(uint64(l))
	if m.Method != 0 {
		n += 1 + sovTx(uint64(m.Method))
	}
	l = len(m.EvidenceCid)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Description)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgRecordPaymentResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.PaymentId)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = m.RemainingDebt.Size()
	n += 1 + l + sovTx(uint64(l))
	return n
}

func (m *MsgRecordNonMonetaryContribution) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Authority)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.DefendantId)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.ContributionType)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = m.EstimatedValue.Size()
	n += 1 + l + sovTx(uint64(l))
	l = len(m.EvidenceCid)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Description)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgRecordNonMonetaryContributionResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ContributionId)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgUpdateDefendantStatus) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Authority)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.DefendantId)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Status != 0 {
		n += 1 + sovTx(uint64(m.Status))
	}
	return n
}

func (m *MsgUpdateDefendantStatusResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgRecordPayment) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRecordPayment: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRecordPayment: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Authority", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Authority = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DefendantId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DefendantId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Amount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Method", wireType)
			}
			m.Method = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Method |= PaymentMethod(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EvidenceCid", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.EvidenceCid = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Description", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Description = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgRecordPaymentResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRecordPaymentResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRecordPaymentResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PaymentId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PaymentId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RemainingDebt", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.RemainingDebt.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgRecordNonMonetaryContribution) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRecordNonMonetaryContribution: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRecordNonMonetaryContribution: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Authority", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Authority = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DefendantId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DefendantId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ContributionType", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ContributionType = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EstimatedValue", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.EstimatedValue.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EvidenceCid", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.EvidenceCid = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Description", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Description = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgRecordNonMonetaryContributionResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRecordNonMonetaryContributionResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRecordNonMonetaryContributionResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ContributionId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ContributionId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateDefendantStatus) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateDefendantStatus: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateDefendantStatus: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Authority", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Authority = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DefendantId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DefendantId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			m.Status = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Status |= DefendantStatus(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateDefendantStatusResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateDefendantStatusResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateDefendantStatusResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
