// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: aequitas/endowment/v1/genesis.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type GenesisState struct {
	Params          Params               `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
	Endowments      []Endowment          `protobuf:"bytes,2,rep,name=endowments,proto3" json:"endowments"`
	Strategies      []InvestmentStrategy `protobuf:"bytes,3,rep,name=strategies,proto3" json:"strategies"`
	SocialPrograms  []SocialProgram      `protobuf:"bytes,4,rep,name=social_programs,json=socialPrograms,proto3" json:"social_programs"`
	NextEndowmentId uint64               `protobuf:"varint,5,opt,name=next_endowment_id,json=nextEndowmentId,proto3" json:"next_endowment_id,omitempty"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_e98cce11c595555f, []int{0}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

func (m *GenesisState) GetEndowments() []Endowment {
	if m != nil {
		return m.Endowments
	}
	return nil
}

func (m *GenesisState) GetStrategies() []InvestmentStrategy {
	if m != nil {
		return m.Strategies
	}
	return nil
}

func (m *GenesisState) GetSocialPrograms() []SocialProgram {
	if m != nil {
		return m.SocialPrograms
	}
	return nil
}

func (m *GenesisState) GetNextEndowmentId() uint64 {
	if m != nil {
		return m.NextEndowmentId
	}
	return 0
}

type Params struct {
	LpLockPeriodYears      uint64 `protobuf:"varint,1,opt,name=lp_lock_period_years,json=lpLockPeriodYears,proto3" json:"lp_lock_period_years,omitempty"`
	SocialLockPeriodYears  uint64 `protobuf:"varint,2,opt,name=social_lock_period_years,json=socialLockPeriodYears,proto3" json:"social_lock_period_years,omitempty"`
	TargetApyBps           uint64 `protobuf:"varint,3,opt,name=target_apy_bps,json=targetApyBps,proto3" json:"target_apy_bps,omitempty"`
	LpAllocationBps        uint64 `protobuf:"varint,4,opt,name=lp_allocation_bps,json=lpAllocationBps,proto3" json:"lp_allocation_bps,omitempty"`
	SocialAllocationBps    uint64 `protobuf:"varint,5,opt,name=social_allocation_bps,json=socialAllocationBps,proto3" json:"social_allocation_bps,omitempty"`
	CommunityAllocationBps uint64 `protobuf:"varint,6,opt,name=community_allocation_bps,json=communityAllocationBps,proto3" json:"community_allocation_bps,omitempty"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_e98cce11c595555f, []int{1}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetLpLockPeriodYears() uint64 {
	if m != nil {
		return m.LpLockPeriodYears
	}
	return 0
}

func (m *Params) GetSocialLockPeriodYears() uint64 {
	if m != nil {
		return m.SocialLockPeriodYears
	}
	return 0
}

func (m *Params) GetTargetApyBps() uint64 {
	if m != nil {
		return m.TargetApyBps
	}
	return 0
}

func (m *Params) GetLpAllocationBps() uint64 {
	if m != nil {
		return m.LpAllocationBps
	}
	return 0
}

func (m *Params) GetSocialAllocationBps() uint64 {
	if m != nil {
		return m.SocialAllocationBps
	}
	return 0
}

func (m *Params) GetCommunityAllocationBps() uint64 {
	if m != nil {
		return m.CommunityAllocationBps
	}
	return 0
}

func init() {
	proto.RegisterType((*GenesisState)(nil), "aequitas.endowment.v1.GenesisState")
	proto.RegisterType((*Params)(nil), "aequitas.endowment.v1.Params")
}

func init() {
	proto.RegisterFile("aequitas/endowment/v1/genesis.proto", fileDescriptor_e98cce11c595555f)
}

var fileDescriptor_e98cce11c595555f = []byte{
	// 470 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x92, 0xc1, 0x6e, 0xd3, 0x30,
	0x1c, 0xc6, 0x9b, 0x2e, 0xf4, 0xe0, 0x4d, 0x9b, 0x66, 0x36, 0x14, 0x4d, 0x22, 0x54, 0x63, 0x48,
	0x85, 0x43, 0xac, 0x15, 0x24, 0x90, 0x38, 0xb5, 0x30, 0xd0, 0x24, 0x60, 0x55, 0x7a, 0x82, 0x8b,
	0xe5, 0xa6, 0x56, 0xb0, 0xe6, 0xc4, 0xc6, 0x76, 0xcb, 0xf2, 0x16, 0x3c, 0x0b, 0x4f, 0xb1, 0xe3,
	0x8e, 0x9c, 0x10, 0x6a, 0xc5, 0x7b, 0xa0, 0xd8, 0x69, 0xd6, 0x95, 0xf6, 0x16, 0xfb, 0xfb, 0xfd,
	0x3e, 0xe7, 0x6f, 0x19, 0x3c, 0x26, 0xf4, 0xdb, 0x84, 0x19, 0xa2, 0x11, 0xcd, 0xc7, 0xe2, 0x7b,
	0x46, 0x73, 0x83, 0xa6, 0xa7, 0x28, 0xa5, 0x39, 0xd5, 0x4c, 0x47, 0x52, 0x09, 0x23, 0xe0, 0xe1,
	0x02, 0x8a, 0x6a, 0x28, 0x9a, 0x9e, 0x1e, 0x1d, 0xa4, 0x22, 0x15, 0x96, 0x40, 0xe5, 0x97, 0x83,
	0x8f, 0x9e, 0xac, 0x6f, 0xbc, 0x35, 0x2d, 0x76, 0xfc, 0xb7, 0x09, 0x76, 0xde, 0xbb, 0x53, 0x86,
	0x86, 0x18, 0x0a, 0x5f, 0x83, 0x96, 0x24, 0x8a, 0x64, 0x3a, 0xf0, 0xda, 0x5e, 0x67, 0xbb, 0xfb,
	0x30, 0x5a, 0x7b, 0x6a, 0x34, 0xb0, 0x50, 0xdf, 0xbf, 0xfe, 0xfd, 0xa8, 0x11, 0x57, 0x0a, 0x7c,
	0x07, 0x40, 0x0d, 0xe9, 0xa0, 0xd9, 0xde, 0xea, 0x6c, 0x77, 0xdb, 0x1b, 0x0a, 0xce, 0x16, 0x8b,
	0xaa, 0x63, 0xc9, 0x84, 0x17, 0x00, 0x68, 0xa3, 0x88, 0xa1, 0x29, 0xa3, 0x3a, 0xd8, 0xb2, 0x3d,
	0x4f, 0x37, 0xf4, 0x9c, 0xe7, 0x53, 0xaa, 0x4d, 0xb9, 0x1a, 0x3a, 0xa5, 0x58, 0x14, 0xde, 0x56,
	0xc0, 0x21, 0xd8, 0xd3, 0x22, 0x61, 0x84, 0x63, 0xa9, 0x44, 0x6a, 0xc7, 0xf3, 0x6d, 0xeb, 0xc9,
	0x86, 0xd6, 0xa1, 0xa5, 0x07, 0x0e, 0xae, 0x0a, 0x77, 0xf5, 0xf2, 0xa6, 0x86, 0xcf, 0xc0, 0x7e,
	0x4e, 0xaf, 0x0c, 0xae, 0x45, 0xcc, 0xc6, 0xc1, 0xbd, 0xb6, 0xd7, 0xf1, 0xe3, 0xbd, 0x32, 0xa8,
	0x27, 0x3c, 0x1f, 0x1f, 0xff, 0x6c, 0x82, 0x96, 0xbb, 0x32, 0x88, 0xc0, 0x01, 0x97, 0x98, 0x8b,
	0xe4, 0x12, 0x4b, 0xaa, 0x98, 0x18, 0xe3, 0x82, 0x12, 0xe5, 0xee, 0xdb, 0x8f, 0xf7, 0xb9, 0xfc,
	0x20, 0x92, 0xcb, 0x81, 0x4d, 0x3e, 0x97, 0x01, 0x7c, 0x09, 0x82, 0xea, 0xe7, 0xff, 0x97, 0x9a,
	0x56, 0x3a, 0x74, 0xf9, 0xaa, 0x78, 0x02, 0x76, 0x0d, 0x51, 0x29, 0x35, 0x98, 0xc8, 0x02, 0x8f,
	0x64, 0x79, 0x95, 0x25, 0xbe, 0xe3, 0x76, 0x7b, 0xb2, 0xe8, 0x4b, 0x3b, 0x06, 0x97, 0x98, 0x70,
	0x2e, 0x12, 0x62, 0x98, 0xc8, 0x2d, 0xe8, 0xbb, 0x31, 0xb8, 0xec, 0xd5, 0xfb, 0x25, 0xdb, 0x05,
	0xd5, 0x51, 0xab, 0xbc, 0x1b, 0xfb, 0xbe, 0x0b, 0xef, 0x3a, 0xaf, 0x40, 0x90, 0x88, 0x2c, 0x9b,
	0xe4, 0xcc, 0x14, 0xab, 0x5a, 0xcb, 0x6a, 0x0f, 0xea, 0xfc, 0x8e, 0xd9, 0xff, 0x74, 0x3d, 0x0b,
	0xbd, 0x9b, 0x59, 0xe8, 0xfd, 0x99, 0x85, 0xde, 0x8f, 0x79, 0xd8, 0xb8, 0x99, 0x87, 0x8d, 0x5f,
	0xf3, 0xb0, 0xf1, 0xe5, 0x45, 0xca, 0xcc, 0xd7, 0xc9, 0x28, 0x4a, 0x44, 0x86, 0xde, 0x28, 0x2a,
	0xde, 0xf6, 0x3e, 0x5e, 0xa0, 0xf8, 0x6c, 0xd0, 0x8b, 0x51, 0xfd, 0xee, 0xaf, 0x96, 0x5e, 0xbe,
	0x29, 0x24, 0xd5, 0xa3, 0x96, 0x7d, 0xf3, 0xcf, 0xff, 0x05, 0x00, 0x00, 0xff, 0xff, 0xec, 0x5e,
	0x59, 0xc6, 0x6e, 0x03, 0x00, 0x00,
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.NextEndowmentId != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.NextEndowmentId))
		i--
		dAtA[i] = 0x28
	}
	if len(m.SocialPrograms) > 0 {
		for iNdEx := len(m.SocialPrograms) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.SocialPrograms[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x22
		}
	}
	if len(m.Strategies) > 0 {
		for iNdEx := len(m.Strategies) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Strategies[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.Endowments) > 0 {
		for iNdEx := len(m.Endowments) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Endowments[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.CommunityAllocationBps != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.CommunityAllocationBps))
		i--
		dAtA[i] = 0x30
	}
	if m.SocialAllocationBps != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.SocialAllocationBps))
		i--
		dAtA[i] = 0x28
	}
	if m.LpAllocationBps != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.LpAllocationBps))
		i--
		dAtA[i] = 0x20
	}
	if m.TargetApyBps != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.TargetApyBps))
		i--
		dAtA[i] = 0x18
	}
	if m.SocialLockPeriodYears != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.SocialLockPeriodYears))
		i--
		dAtA[i] = 0x10
	}
	if m.LpLockPeriodYears != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.LpLockPeriodYears))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintGenesis(dAtA []byte, offset int, v uint64) int {
	offset -= sovGenesis(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovGenesis(uint64(l))
	if len(m.Endowments) > 0 {
		for _, e := range m.Endowments {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.Strategies) > 0 {
		for _, e := range m.Strategies {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.SocialPrograms) > 0 {
		for _, e := range m.SocialPrograms {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if m.NextEndowmentId != 0 {
		n += 1 + sovGenesis(uint64(m.NextEndowmentId))
	}
	return n
}

func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.LpLockPeriodYears != 0 {
		n += 1 + sovGenesis(uint64(m.LpLockPeriodYears))
	}
	if m.SocialLockPeriodYears != 0 {
		n += 1 + sovGenesis(uint64(m.SocialLockPeriodYears))
	}
	if m.TargetApyBps != 0 {
		n += 1 + sovGenesis(uint64(m.TargetApyBps))
	}
	if m.LpAllocationBps != 0 {
		n += 1 + sovGenesis(uint64(m.LpAllocationBps))
	}
	if m.SocialAllocationBps != 0 {
		n += 1 + sovGenesis(uint64(m.SocialAllocationBps))
	}
	if m.CommunityAllocationBps != 0 {
		n += 1 + sovGenesis(uint64(m.CommunityAllocationBps))
	}
	return n
}

func sovGenesis(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGenesis(x uint64) (n int) {
	return sovGenesis(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Endowments", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Endowments = append(m.Endowments, Endowment{})
			if err := m.Endowments[len(m.Endowments)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Strategies", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Strategies = append(m.Strategies, InvestmentStrategy{})
			if err := m.Strategies[len(m.Strategies)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SocialPrograms", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SocialPrograms = append(m.SocialPrograms, SocialProgram{})
			if err := m.SocialPrograms[len(m.SocialPrograms)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field NextEndowmentId", wireType)
			}
			m.NextEndowmentId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.NextEndowmentId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LpLockPeriodYears", wireType)
			}
			m.LpLockPeriodYears = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LpLockPeriodYears |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SocialLockPeriodYears", wireType)
			}
			m.SocialLockPeriodYears = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SocialLockPeriodYears |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TargetApyBps", wireType)
			}
			m.TargetApyBps = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TargetApyBps |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LpAllocationBps", wireType)
			}
			m.LpAllocationBps = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LpAllocationBps |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SocialAllocationBps", wireType)
			}
			m.SocialAllocationBps = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SocialAllocationBps |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CommunityAllocationBps", wireType)
			}
			m.CommunityAllocationBps = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CommunityAllocationBps |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenesis(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGenesis
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGenesis
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGenesis
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGenesis        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenesis          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenesis = fmt.Errorf("proto: unexpected end of group")
)
