// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: aequitas/endowment/v1/tx.proto

package types

import (
	context "context"
	cosmossdk_io_math "cosmossdk.io/math"
	fmt "fmt"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MsgDepositToEndowment struct {
	Authority   string     `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	EndowmentId string     `protobuf:"bytes,2,opt,name=endowment_id,json=endowmentId,proto3" json:"endowment_id,omitempty"`
	Amount      types.Coin `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount"`
}

func (m *MsgDepositToEndowment) Reset()         { *m = MsgDepositToEndowment{} }
func (m *MsgDepositToEndowment) String() string { return proto.CompactTextString(m) }
func (*MsgDepositToEndowment) ProtoMessage()    {}
func (*MsgDepositToEndowment) Descriptor() ([]byte, []int) {
	return fileDescriptor_35e7c6ec1c6c3c81, []int{0}
}
func (m *MsgDepositToEndowment) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgDepositToEndowment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgDepositToEndowment.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgDepositToEndowment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgDepositToEndowment.Merge(m, src)
}
func (m *MsgDepositToEndowment) XXX_Size() int {
	return m.Size()
}
func (m *MsgDepositToEndowment) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgDepositToEndowment.DiscardUnknown(m)
}

var xxx_messageInfo_MsgDepositToEndowment proto.InternalMessageInfo

func (m *MsgDepositToEndowment) GetAuthority() string {
	if m != nil {
		return m.Authority
	}
	return ""
}

func (m *MsgDepositToEndowment) GetEndowmentId() string {
	if m != nil {
		return m.EndowmentId
	}
	return ""
}

func (m *MsgDepositToEndowment) GetAmount() types.Coin {
	if m != nil {
		return m.Amount
	}
	return types.Coin{}
}

type MsgDepositToEndowmentResponse struct {
}

func (m *MsgDepositToEndowmentResponse) Reset()         { *m = MsgDepositToEndowmentResponse{} }
func (m *MsgDepositToEndowmentResponse) String() string { return proto.CompactTextString(m) }
func (*MsgDepositToEndowmentResponse) ProtoMessage()    {}
func (*MsgDepositToEndowmentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_35e7c6ec1c6c3c81, []int{1}
}
func (m *MsgDepositToEndowmentResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgDepositToEndowmentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgDepositToEndowmentResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgDepositToEndowmentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgDepositToEndowmentResponse.Merge(m, src)
}
func (m *MsgDepositToEndowmentResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgDepositToEndowmentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgDepositToEndowmentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgDepositToEndowmentResponse proto.InternalMessageInfo

type MsgDistributeYield struct {
	Authority   string `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	EndowmentId string `protobuf:"bytes,2,opt,name=endowment_id,json=endowmentId,proto3" json:"endowment_id,omitempty"`
}

func (m *MsgDistributeYield) Reset()         { *m = MsgDistributeYield{} }
func (m *MsgDistributeYield) String() string { return proto.CompactTextString(m) }
func (*MsgDistributeYield) ProtoMessage()    {}
func (*MsgDistributeYield) Descriptor() ([]byte, []int) {
	return fileDescriptor_35e7c6ec1c6c3c81, []int{2}
}
func (m *MsgDistributeYield) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgDistributeYield) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgDistributeYield.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgDistributeYield) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgDistributeYield.Merge(m, src)
}
func (m *MsgDistributeYield) XXX_Size() int {
	return m.Size()
}
func (m *MsgDistributeYield) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgDistributeYield.DiscardUnknown(m)
}

var xxx_messageInfo_MsgDistributeYield proto.InternalMessageInfo

func (m *MsgDistributeYield) GetAuthority() string {
	if m != nil {
		return m.Authority
	}
	return ""
}

func (m *MsgDistributeYield) GetEndowmentId() string {
	if m != nil {
		return m.EndowmentId
	}
	return ""
}

type MsgDistributeYieldResponse struct {
	AmountDistributed cosmossdk_io_math.Int `protobuf:"bytes,1,opt,name=amount_distributed,json=amountDistributed,proto3,customtype=cosmossdk.io/math.Int" json:"amount_distributed"`
}

func (m *MsgDistributeYieldResponse) Reset()         { *m = MsgDistributeYieldResponse{} }
func (m *MsgDistributeYieldResponse) String() string { return proto.CompactTextString(m) }
func (*MsgDistributeYieldResponse) ProtoMessage()    {}
func (*MsgDistributeYieldResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_35e7c6ec1c6c3c81, []int{3}
}
func (m *MsgDistributeYieldResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgDistributeYieldResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgDistributeYieldResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgDistributeYieldResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgDistributeYieldResponse.Merge(m, src)
}
func (m *MsgDistributeYieldResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgDistributeYieldResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgDistributeYieldResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgDistributeYieldResponse proto.InternalMessageInfo

type MsgRebalanceStrategies struct {
	Authority   string `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	EndowmentId string `protobuf:"bytes,2,opt,name=endowment_id,json=endowmentId,proto3" json:"endowment_id,omitempty"`
}

func (m *MsgRebalanceStrategies) Reset()         { *m = MsgRebalanceStrategies{} }
func (m *MsgRebalanceStrategies) String() string { return proto.CompactTextString(m) }
func (*MsgRebalanceStrategies) ProtoMessage()    {}
func (*MsgRebalanceStrategies) Descriptor() ([]byte, []int) {
	return fileDescriptor_35e7c6ec1c6c3c81, []int{4}
}
func (m *MsgRebalanceStrategies) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRebalanceStrategies) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRebalanceStrategies.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRebalanceStrategies) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRebalanceStrategies.Merge(m, src)
}
func (m *MsgRebalanceStrategies) XXX_Size() int {
	return m.Size()
}
func (m *MsgRebalanceStrategies) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRebalanceStrategies.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRebalanceStrategies proto.InternalMessageInfo

func (m *MsgRebalanceStrategies) GetAuthority() string {
	if m != nil {
		return m.Authority
	}
	return ""
}

func (m *MsgRebalanceStrategies) GetEndowmentId() string {
	if m != nil {
		return m.EndowmentId
	}
	return ""
}

type MsgRebalanceStrategiesResponse struct {
}

func (m *MsgRebalanceStrategiesResponse) Reset()         { *m = MsgRebalanceStrategiesResponse{} }
func (m *MsgRebalanceStrategiesResponse) String() string { return proto.CompactTextString(m) }
func (*MsgRebalanceStrategiesResponse) ProtoMessage()    {}
func (*MsgRebalanceStrategiesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_35e7c6ec1c6c3c81, []int{5}
}
func (m *MsgRebalanceStrategiesResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRebalanceStrategiesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRebalanceStrategiesResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRebalanceStrategiesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRebalanceStrategiesResponse.Merge(m, src)
}
func (m *MsgRebalanceStrategiesResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgRebalanceStrategiesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRebalanceStrategiesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRebalanceStrategiesResponse proto.InternalMessageInfo

type MsgUpdateStrategyAllocation struct {
	Authority               string `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	StrategyId              string `protobuf:"bytes,2,opt,name=strategy_id,json=strategyId,proto3" json:"strategy_id,omitempty"`
	NewAllocationPercentage uint64 `protobuf:"varint,3,opt,name=new_allocation_percentage,json=newAllocationPercentage,proto3" json:"new_allocation_percentage,omitempty"`
}

func (m *MsgUpdateStrategyAllocation) Reset()         { *m = MsgUpdateStrategyAllocation{} }
func (m *MsgUpdateStrategyAllocation) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateStrategyAllocation) ProtoMessage()    {}
func (*MsgUpdateStrategyAllocation) Descriptor() ([]byte, []int) {
	return fileDescriptor_35e7c6ec1c6c3c81, []int{6}
}
func (m *MsgUpdateStrategyAllocation) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateStrategyAllocation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateStrategyAllocation.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateStrategyAllocation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateStrategyAllocation.Merge(m, src)
}
func (m *MsgUpdateStrategyAllocation) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateStrategyAllocation) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateStrategyAllocation.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateStrategyAllocation proto.InternalMessageInfo

func (m *MsgUpdateStrategyAllocation) GetAuthority() string {
	if m != nil {
		return m.Authority
	}
	return ""
}

func (m *MsgUpdateStrategyAllocation) GetStrategyId() string {
	if m != nil {
		return m.StrategyId
	}
	return ""
}

func (m *MsgUpdateStrategyAllocation) GetNewAllocationPercentage() uint64 {
	if m != nil {
		return m.NewAllocationPercentage
	}
	return 0
}

type MsgUpdateStrategyAllocationResponse struct {
}

func (m *MsgUpdateStrategyAllocationResponse) Reset()         { *m = MsgUpdateStrategyAllocationResponse{} }
func (m *MsgUpdateStrategyAllocationResponse) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateStrategyAllocationResponse) ProtoMessage()    {}
func (*MsgUpdateStrategyAllocationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_35e7c6ec1c6c3c81, []int{7}
}
func (m *MsgUpdateStrategyAllocationResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateStrategyAllocationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateStrategyAllocationResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateStrategyAllocationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateStrategyAllocationResponse.Merge(m, src)
}
func (m *MsgUpdateStrategyAllocationResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateStrategyAllocationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateStrategyAllocationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateStrategyAllocationResponse proto.InternalMessageInfo

type MsgDistributeToSocialPrograms struct {
	Authority string `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
}

func (m *MsgDistributeToSocialPrograms) Reset()         { *m = MsgDistributeToSocialPrograms{} }
func (m *MsgDistributeToSocialPrograms) String() string { return proto.CompactTextString(m) }
func (*MsgDistributeToSocialPrograms) ProtoMessage()    {}
func (*MsgDistributeToSocialPrograms) Descriptor() ([]byte, []int) {
	return fileDescriptor_35e7c6ec1c6c3c81, []int{8}
}
func (m *MsgDistributeToSocialPrograms) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgDistributeToSocialPrograms) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgDistributeToSocialPrograms.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgDistributeToSocialPrograms) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgDistributeToSocialPrograms.Merge(m, src)
}
func (m *MsgDistributeToSocialPrograms) XXX_Size() int {
	return m.Size()
}
func (m *MsgDistributeToSocialPrograms) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgDistributeToSocialPrograms.DiscardUnknown(m)
}

var xxx_messageInfo_MsgDistributeToSocialPrograms proto.InternalMessageInfo

func (m *MsgDistributeToSocialPrograms) GetAuthority() string {
	if m != nil {
		return m.Authority
	}
	return ""
}

type MsgDistributeToSocialProgramsResponse struct {
	TotalDistributed cosmossdk_io_math.Int `protobuf:"bytes,1,opt,name=total_distributed,json=totalDistributed,proto3,customtype=cosmossdk.io/math.Int" json:"total_distributed"`
}

func (m *MsgDistributeToSocialProgramsResponse) Reset()         { *m = MsgDistributeToSocialProgramsResponse{} }
func (m *MsgDistributeToSocialProgramsResponse) String() string { return proto.CompactTextString(m) }
func (*MsgDistributeToSocialProgramsResponse) ProtoMessage()    {}
func (*MsgDistributeToSocialProgramsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_35e7c6ec1c6c3c81, []int{9}
}
func (m *MsgDistributeToSocialProgramsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgDistributeToSocialProgramsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgDistributeToSocialProgramsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgDistributeToSocialProgramsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgDistributeToSocialProgramsResponse.Merge(m, src)
}
func (m *MsgDistributeToSocialProgramsResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgDistributeToSocialProgramsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgDistributeToSocialProgramsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgDistributeToSocialProgramsResponse proto.InternalMessageInfo

type MsgUpdateParams struct {
	Authority string `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	Params    Params `protobuf:"bytes,2,opt,name=params,proto3" json:"params"`
}

func (m *MsgUpdateParams) Reset()         { *m = MsgUpdateParams{} }
func (m *MsgUpdateParams) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateParams) ProtoMessage()    {}
func (*MsgUpdateParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_35e7c6ec1c6c3c81, []int{10}
}
func (m *MsgUpdateParams) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateParams.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateParams.Merge(m, src)
}
func (m *MsgUpdateParams) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateParams) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateParams.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateParams proto.InternalMessageInfo

func (m *MsgUpdateParams) GetAuthority() string {
	if m != nil {
		return m.Authority
	}
	return ""
}

func (m *MsgUpdateParams) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

type MsgUpdateParamsResponse struct {
}

func (m *MsgUpdateParamsResponse) Reset()         { *m = MsgUpdateParamsResponse{} }
func (m *MsgUpdateParamsResponse) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateParamsResponse) ProtoMessage()    {}
func (*MsgUpdateParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_35e7c6ec1c6c3c81, []int{11}
}
func (m *MsgUpdateParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateParamsResponse.Merge(m, src)
}
func (m *MsgUpdateParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateParamsResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgDepositToEndowment)(nil), "aequitas.endowment.v1.MsgDepositToEndowment")
	proto.RegisterType((*MsgDepositToEndowmentResponse)(nil), "aequitas.endowment.v1.MsgDepositToEndowmentResponse")
	proto.RegisterType((*MsgDistributeYield)(nil), "aequitas.endowment.v1.MsgDistributeYield")
	proto.RegisterType((*MsgDistributeYieldResponse)(nil), "aequitas.endowment.v1.MsgDistributeYieldResponse")
	proto.RegisterType((*MsgRebalanceStrategies)(nil), "aequitas.endowment.v1.MsgRebalanceStrategies")
	proto.RegisterType((*MsgRebalanceStrategiesResponse)(nil), "aequitas.endowment.v1.MsgRebalanceStrategiesResponse")
	proto.RegisterType((*MsgUpdateStrategyAllocation)(nil), "aequitas.endowment.v1.MsgUpdateStrategyAllocation")
	proto.RegisterType((*MsgUpdateStrategyAllocationResponse)(nil), "aequitas.endowment.v1.MsgUpdateStrategyAllocationResponse")
	proto.RegisterType((*MsgDistributeToSocialPrograms)(nil), "aequitas.endowment.v1.MsgDistributeToSocialPrograms")
	proto.RegisterType((*MsgDistributeToSocialProgramsResponse)(nil), "aequitas.endowment.v1.MsgDistributeToSocialProgramsResponse")
	proto.RegisterType((*MsgUpdateParams)(nil), "aequitas.endowment.v1.MsgUpdateParams")
	proto.RegisterType((*MsgUpdateParamsResponse)(nil), "aequitas.endowment.v1.MsgUpdateParamsResponse")
}

func init() { proto.RegisterFile("aequitas/endowment/v1/tx.proto", fileDescriptor_35e7c6ec1c6c3c81) }

var fileDescriptor_35e7c6ec1c6c3c81 = []byte{
	// 710 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x55, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0x8d, 0xe9, 0x87, 0xd4, 0x49, 0x45, 0xa9, 0xa1, 0x34, 0x35, 0xd4, 0x29, 0xa9, 0x8a, 0x4a,
	0x05, 0xb6, 0x12, 0x8a, 0x90, 0x0a, 0x97, 0x7e, 0x1d, 0x8a, 0x08, 0x44, 0x6e, 0x39, 0xc0, 0x25,
	0xda, 0xd8, 0x8b, 0xbb, 0x10, 0xef, 0x1a, 0xef, 0xa6, 0x1f, 0x82, 0x03, 0xe2, 0xc8, 0xa9, 0x7f,
	0x81, 0x1b, 0xc7, 0xfe, 0x8c, 0x1e, 0x7b, 0x44, 0x1c, 0x2a, 0xd4, 0x1e, 0xfa, 0x27, 0x38, 0xa0,
	0xd8, 0xf1, 0xa6, 0x6d, 0x9c, 0xa4, 0x01, 0x6e, 0xd6, 0xce, 0x9b, 0x79, 0xef, 0x8d, 0x67, 0x76,
	0x41, 0x47, 0xf8, 0x43, 0x8d, 0x08, 0xc4, 0x4d, 0x4c, 0x1d, 0xb6, 0xed, 0x61, 0x2a, 0xcc, 0xad,
	0xbc, 0x29, 0x76, 0x0c, 0x3f, 0x60, 0x82, 0xa9, 0x63, 0x71, 0xdc, 0x90, 0x71, 0x63, 0x2b, 0xaf,
	0xdd, 0x70, 0x99, 0xcb, 0x42, 0x84, 0x59, 0xff, 0x8a, 0xc0, 0xda, 0xb8, 0xcd, 0xb8, 0xc7, 0xb8,
	0xe9, 0x71, 0xb7, 0x5e, 0xc4, 0xe3, 0x6e, 0x23, 0xa0, 0x37, 0x02, 0x15, 0xc4, 0xb1, 0xb9, 0x95,
	0xaf, 0x60, 0x81, 0xf2, 0xa6, 0xcd, 0x08, 0x6d, 0xc4, 0xa7, 0x93, 0x55, 0xb8, 0x98, 0x62, 0x4e,
	0x78, 0x04, 0xca, 0x7d, 0x53, 0x60, 0xac, 0xc8, 0xdd, 0x15, 0xec, 0x33, 0x4e, 0xc4, 0x06, 0x5b,
	0x8d, 0xa1, 0xea, 0x6d, 0x18, 0x42, 0x35, 0xb1, 0xc9, 0x02, 0x22, 0x76, 0x33, 0xca, 0x94, 0x32,
	0x3b, 0x64, 0x35, 0x0f, 0xd4, 0x3b, 0x30, 0x2c, 0xab, 0x96, 0x89, 0x93, 0xb9, 0x12, 0x02, 0xd2,
	0xf2, 0x6c, 0xcd, 0x51, 0x1f, 0xc3, 0x20, 0xf2, 0x58, 0x8d, 0x8a, 0x4c, 0xdf, 0x94, 0x32, 0x9b,
	0x2e, 0x4c, 0x18, 0x91, 0x60, 0xa3, 0x2e, 0xd8, 0x68, 0x08, 0x36, 0x96, 0x19, 0xa1, 0x4b, 0xfd,
	0x07, 0x47, 0xd9, 0x94, 0xd5, 0x80, 0x2f, 0x5c, 0xfd, 0x72, 0xba, 0x3f, 0xd7, 0xe4, 0xca, 0x65,
	0x61, 0x32, 0x51, 0xa2, 0x85, 0xb9, 0xcf, 0x28, 0xc7, 0x39, 0x0c, 0x6a, 0x1d, 0x40, 0xb8, 0x08,
	0x48, 0xa5, 0x26, 0xf0, 0x6b, 0x82, 0xab, 0xce, 0x3f, 0x1b, 0x68, 0xd1, 0xf1, 0x0e, 0xb4, 0x56,
	0x9a, 0x58, 0x84, 0xfa, 0x1c, 0xd4, 0x48, 0x7f, 0xd9, 0x91, 0x08, 0x27, 0xe2, 0x5d, 0x9a, 0xac,
	0xfb, 0xfb, 0x79, 0x94, 0x1d, 0x8b, 0x3a, 0xc0, 0x9d, 0xf7, 0x06, 0x61, 0xa6, 0x87, 0xc4, 0xa6,
	0xb1, 0x46, 0x85, 0x35, 0x1a, 0x25, 0x36, 0x2b, 0x3b, 0x39, 0x02, 0x37, 0x8b, 0xdc, 0xb5, 0x70,
	0x05, 0x55, 0x11, 0xb5, 0xf1, 0xba, 0x08, 0x90, 0xc0, 0x2e, 0xc1, 0xfc, 0xff, 0xdb, 0x9a, 0x02,
	0x3d, 0x99, 0x4a, 0xf6, 0xf7, 0xbb, 0x02, 0xb7, 0x8a, 0xdc, 0x7d, 0xe5, 0x3b, 0x48, 0xc4, 0xf1,
	0xdd, 0xc5, 0x6a, 0x95, 0xd9, 0x48, 0x10, 0x46, 0xbb, 0x48, 0xca, 0x42, 0x9a, 0x37, 0x72, 0x9a,
	0x8a, 0x20, 0x3e, 0x5a, 0x73, 0xd4, 0x05, 0x98, 0xa0, 0x78, 0xbb, 0x8c, 0x64, 0xc1, 0xb2, 0x8f,
	0x03, 0x1b, 0x53, 0x81, 0x5c, 0x1c, 0xce, 0x4e, 0xbf, 0x35, 0x4e, 0xf1, 0x76, 0x93, 0xb0, 0x24,
	0xc3, 0x2d, 0x66, 0x66, 0x60, 0xba, 0x83, 0x52, 0xe9, 0xa8, 0x18, 0x8d, 0x94, 0x6c, 0xf8, 0x06,
	0x5b, 0x67, 0x36, 0x41, 0xd5, 0x52, 0xc0, 0xdc, 0x00, 0x79, 0x5d, 0xba, 0xdc, 0xc2, 0xca, 0x61,
	0xa6, 0x63, 0x39, 0x39, 0x24, 0xcf, 0x60, 0x54, 0x30, 0x81, 0xaa, 0xbd, 0xcf, 0xc8, 0xb5, 0x30,
	0xef, 0xec, 0x88, 0x7c, 0x82, 0x11, 0x69, 0xb5, 0x84, 0xba, 0xab, 0x56, 0x9f, 0xc0, 0xa0, 0x1f,
	0xe2, 0xc2, 0x7f, 0x90, 0x2e, 0x4c, 0x1a, 0x89, 0xf7, 0x90, 0x11, 0x15, 0x8b, 0x97, 0x32, 0x4a,
	0x69, 0xb1, 0x3c, 0x01, 0xe3, 0x17, 0xd8, 0x63, 0x93, 0x85, 0xdf, 0x03, 0xd0, 0x57, 0xe4, 0xae,
	0xba, 0x03, 0x6a, 0xc2, 0xbd, 0x72, 0xbf, 0x0d, 0x6b, 0xe2, 0x8a, 0x6b, 0xf3, 0xbd, 0xa0, 0x65,
	0x9b, 0x19, 0x8c, 0x5c, 0xbc, 0x0d, 0xee, 0x75, 0x28, 0x74, 0x1e, 0xaa, 0xe5, 0x2f, 0x0d, 0x95,
	0x84, 0x1f, 0xe1, 0x7a, 0xd2, 0xae, 0x3e, 0x68, 0x5f, 0x29, 0x01, 0xae, 0x3d, 0xea, 0x09, 0x2e,
	0xc9, 0xbf, 0x2a, 0x90, 0x69, 0xbb, 0x9b, 0x85, 0xf6, 0x35, 0xdb, 0xe5, 0x68, 0x0b, 0xbd, 0xe7,
	0x48, 0x31, 0x7b, 0x0a, 0x68, 0x1d, 0xf6, 0x6a, 0xfe, 0x32, 0xbd, 0xbd, 0x98, 0xa5, 0x3d, 0xfd,
	0x9b, 0x2c, 0x29, 0xe9, 0x2d, 0x0c, 0x9f, 0xdb, 0x92, 0xbb, 0xdd, 0xec, 0x45, 0x38, 0xcd, 0xb8,
	0x1c, 0x2e, 0xe6, 0xd1, 0x06, 0x3e, 0x9f, 0xee, 0xcf, 0x29, 0x4b, 0x2f, 0x0e, 0x8e, 0x75, 0xe5,
	0xf0, 0x58, 0x57, 0x7e, 0x1d, 0xeb, 0xca, 0xde, 0x89, 0x9e, 0x3a, 0x3c, 0xd1, 0x53, 0x3f, 0x4e,
	0xf4, 0xd4, 0x9b, 0x79, 0x97, 0x88, 0xcd, 0x5a, 0xc5, 0xb0, 0x99, 0x67, 0x2e, 0x07, 0x98, 0xad,
	0x2c, 0x16, 0x5f, 0x9a, 0xd6, 0x6a, 0x69, 0xd1, 0x32, 0xe5, 0x5b, 0xbd, 0x73, 0xe6, 0xb5, 0x16,
	0xbb, 0x3e, 0xe6, 0x95, 0xc1, 0xf0, 0xa5, 0x7e, 0xf8, 0x27, 0x00, 0x00, 0xff, 0xff, 0x1b, 0xd5,
	0xff, 0x04, 0x56, 0x08, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	DepositToEndowment(ctx context.Context, in *MsgDepositToEndowment, opts ...grpc.CallOption) (*MsgDepositToEndowmentResponse, error)
	DistributeYield(ctx context.Context, in *MsgDistributeYield, opts ...grpc.CallOption) (*MsgDistributeYieldResponse, error)
	RebalanceStrategies(ctx context.Context, in *MsgRebalanceStrategies, opts ...grpc.CallOption) (*MsgRebalanceStrategiesResponse, error)
	UpdateStrategyAllocation(ctx context.Context, in *MsgUpdateStrategyAllocation, opts ...grpc.CallOption) (*MsgUpdateStrategyAllocationResponse, error)
	DistributeToSocialPrograms(ctx context.Context, in *MsgDistributeToSocialPrograms, opts ...grpc.CallOption) (*MsgDistributeToSocialProgramsResponse, error)
	UpdateParams(ctx context.Context, in *MsgUpdateParams, opts ...grpc.CallOption) (*MsgUpdateParamsResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) DepositToEndowment(ctx context.Context, in *MsgDepositToEndowment, opts ...grpc.CallOption) (*MsgDepositToEndowmentResponse, error) {
	out := new(MsgDepositToEndowmentResponse)
	err := c.cc.Invoke(ctx, "/aequitas.endowment.v1.Msg/DepositToEndowment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) DistributeYield(ctx context.Context, in *MsgDistributeYield, opts ...grpc.CallOption) (*MsgDistributeYieldResponse, error) {
	out := new(MsgDistributeYieldResponse)
	err := c.cc.Invoke(ctx, "/aequitas.endowment.v1.Msg/DistributeYield", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) RebalanceStrategies(ctx context.Context, in *MsgRebalanceStrategies, opts ...grpc.CallOption) (*MsgRebalanceStrategiesResponse, error) {
	out := new(MsgRebalanceStrategiesResponse)
	err := c.cc.Invoke(ctx, "/aequitas.endowment.v1.Msg/RebalanceStrategies", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) UpdateStrategyAllocation(ctx context.Context, in *MsgUpdateStrategyAllocation, opts ...grpc.CallOption) (*MsgUpdateStrategyAllocationResponse, error) {
	out := new(MsgUpdateStrategyAllocationResponse)
	err := c.cc.Invoke(ctx, "/aequitas.endowment.v1.Msg/UpdateStrategyAllocation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) DistributeToSocialPrograms(ctx context.Context, in *MsgDistributeToSocialPrograms, opts ...grpc.CallOption) (*MsgDistributeToSocialProgramsResponse, error) {
	out := new(MsgDistributeToSocialProgramsResponse)
	err := c.cc.Invoke(ctx, "/aequitas.endowment.v1.Msg/DistributeToSocialPrograms", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) UpdateParams(ctx context.Context, in *MsgUpdateParams, opts ...grpc.CallOption) (*MsgUpdateParamsResponse, error) {
	out := new(MsgUpdateParamsResponse)
	err := c.cc.Invoke(ctx, "/aequitas.endowment.v1.Msg/UpdateParams", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	DepositToEndowment(context.Context, *MsgDepositToEndowment) (*MsgDepositToEndowmentResponse, error)
	DistributeYield(context.Context, *MsgDistributeYield) (*MsgDistributeYieldResponse, error)
	RebalanceStrategies(context.Context, *MsgRebalanceStrategies) (*MsgRebalanceStrategiesResponse, error)
	UpdateStrategyAllocation(context.Context, *MsgUpdateStrategyAllocation) (*MsgUpdateStrategyAllocationResponse, error)
	DistributeToSocialPrograms(context.Context, *MsgDistributeToSocialPrograms) (*MsgDistributeToSocialProgramsResponse, error)
	UpdateParams(context.Context, *MsgUpdateParams) (*MsgUpdateParamsResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) DepositToEndowment(ctx context.Context, req *MsgDepositToEndowment) (*MsgDepositToEndowmentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DepositToEndowment not implemented")
}
func (*UnimplementedMsgServer) DistributeYield(ctx context.Context, req *MsgDistributeYield) (*MsgDistributeYieldResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DistributeYield not implemented")
}
func (*UnimplementedMsgServer) RebalanceStrategies(ctx context.Context, req *MsgRebalanceStrategies) (*MsgRebalanceStrategiesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RebalanceStrategies not implemented")
}
func (*UnimplementedMsgServer) UpdateStrategyAllocation(ctx context.Context, req *MsgUpdateStrategyAllocation) (*MsgUpdateStrategyAllocationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateStrategyAllocation not implemented")
}
func (*UnimplementedMsgServer) DistributeToSocialPrograms(ctx context.Context, req *MsgDistributeToSocialPrograms) (*MsgDistributeToSocialProgramsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DistributeToSocialPrograms not implemented")
}
func (*UnimplementedMsgServer) UpdateParams(ctx context.Context, req *MsgUpdateParams) (*MsgUpdateParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateParams not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_DepositToEndowment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgDepositToEndowment)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).DepositToEndowment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/aequitas.endowment.v1.Msg/DepositToEndowment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).DepositToEndowment(ctx, req.(*MsgDepositToEndowment))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_DistributeYield_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgDistributeYield)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).DistributeYield(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/aequitas.endowment.v1.Msg/DistributeYield",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).DistributeYield(ctx, req.(*MsgDistributeYield))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_RebalanceStrategies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgRebalanceStrategies)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).RebalanceStrategies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/aequitas.endowment.v1.Msg/RebalanceStrategies",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).RebalanceStrategies(ctx, req.(*MsgRebalanceStrategies))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_UpdateStrategyAllocation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateStrategyAllocation)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateStrategyAllocation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/aequitas.endowment.v1.Msg/UpdateStrategyAllocation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateStrategyAllocation(ctx, req.(*MsgUpdateStrategyAllocation))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_DistributeToSocialPrograms_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgDistributeToSocialPrograms)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).DistributeToSocialPrograms(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/aequitas.endowment.v1.Msg/DistributeToSocialPrograms",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).DistributeToSocialPrograms(ctx, req.(*MsgDistributeToSocialPrograms))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_UpdateParams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateParams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/aequitas.endowment.v1.Msg/UpdateParams",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateParams(ctx, req.(*MsgUpdateParams))
	}
	return interceptor(ctx, in, info, handler)
}

var Msg_serviceDesc = _Msg_serviceDesc
var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "aequitas.endowment.v1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DepositToEndowment",
			Handler:    _Msg_DepositToEndowment_Handler,
		},
		{
			MethodName: "DistributeYield",
			Handler:    _Msg_DistributeYield_Handler,
		},
		{
			MethodName: "RebalanceStrategies",
			Handler:    _Msg_RebalanceStrategies_Handler,
		},
		{
			MethodName: "UpdateStrategyAllocation",
			Handler:    _Msg_UpdateStrategyAllocation_Handler,
		},
		{
			MethodName: "DistributeToSocialPrograms",
			Handler:    _Msg_DistributeToSocialPrograms_Handler,
		},
		{
			MethodName: "UpdateParams",
			Handler:    _Msg_UpdateParams_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "aequitas/endowment/v1/tx.proto",
}

func (m *MsgDepositToEndowment) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgDepositToEndowment) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgDepositToEndowment) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Amount.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	if len(m.EndowmentId) > 0 {
		i -= len(m.EndowmentId)
		copy(dAtA[i:], m.EndowmentId)
		i = encodeVarintTx(dAtA, i, uint64(len(m.EndowmentId)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Authority) > 0 {
		i -= len(m.Authority)
		copy(dAtA[i:], m.Authority)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Authority)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgDepositToEndowmentResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgDepositToEndowmentResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgDepositToEndowmentResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgDistributeYield) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgDistributeYield) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgDistributeYield) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.EndowmentId) > 0 {
		i -= len(m.EndowmentId)
		copy(dAtA[i:], m.EndowmentId)
		i = encodeVarintTx(dAtA, i, uint64(len(m.EndowmentId)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Authority) > 0 {
		i -= len(m.Authority)
		copy(dAtA[i:], m.Authority)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Authority)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgDistributeYieldResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgDistributeYieldResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgDistributeYieldResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.AmountDistributed.Size()
		i -= size
		if _, err := m.AmountDistributed.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *MsgRebalanceStrategies) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRebalanceStrategies) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRebalanceStrategies) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.EndowmentId) > 0 {
		i -= len(m.EndowmentId)
		copy(dAtA[i:], m.EndowmentId)
		i = encodeVarintTx(dAtA, i, uint64(len(m.EndowmentId)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Authority) > 0 {
		i -= len(m.Authority)
		copy(dAtA[i:], m.Authority)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Authority)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgRebalanceStrategiesResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRebalanceStrategiesResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRebalanceStrategiesResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgUpdateStrategyAllocation) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateStrategyAllocation) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateStrategyAllocation) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.NewAllocationPercentage != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.NewAllocationPercentage))
		i--
		dAtA[i] = 0x18
	}
	if len(m.StrategyId) > 0 {
		i -= len(m.StrategyId)
		copy(dAtA[i:], m.StrategyId)
		i = encodeVarintTx(dAtA, i, uint64(len(m.StrategyId)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Authority) > 0 {
		i -= len(m.Authority)
		copy(dAtA[i:], m.Authority)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Authority)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgUpdateStrategyAllocationResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateStrategyAllocationResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateStrategyAllocationResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgDistributeToSocialPrograms) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgDistributeToSocialPrograms) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgDistributeToSocialPrograms) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Authority) > 0 {
		i -= len(m.Authority)
		copy(dAtA[i:], m.Authority)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Authority)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgDistributeToSocialProgramsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgDistributeToSocialProgramsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgDistributeToSocialProgramsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.TotalDistributed.Size()
		i -= size
		if _, err := m.TotalDistributed.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *MsgUpdateParams) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateParams) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateParams) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.Authority) > 0 {
		i -= len(m.Authority)
		copy(dAtA[i:], m.Authority)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Authority)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgUpdateParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgDepositToEndowment) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Authority)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.EndowmentId)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = m.Amount.Size()
	n += 1 + l + sovTx(uint64(l))
	return n
}

func (m *MsgDepositToEndowmentResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgDistributeYield) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Authority)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.EndowmentId)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgDistributeYieldResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.AmountDistributed.Size()
	n += 1 + l + sovTx(uint64(l))
	return n
}

func (m *MsgRebalanceStrategies) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Authority)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.EndowmentId)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgRebalanceStrategiesResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgUpdateStrategyAllocation) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Authority)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.StrategyId)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.NewAllocationPercentage != 0 {
		n += 1 + sovTx(uint64(m.NewAllocationPercentage))
	}
	return n
}

func (m *MsgUpdateStrategyAllocationResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgDistributeToSocialPrograms) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Authority)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgDistributeToSocialProgramsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.TotalDistributed.Size()
	n += 1 + l + sovTx(uint64(l))
	return n
}

func (m *MsgUpdateParams) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Authority)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = m.Params.Size()
	n += 1 + l + sovTx(uint64(l))
	return n
}

func (m *MsgUpdateParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgDepositToEndowment) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgDepositToEndowment: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgDepositToEndowment: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Authority", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Authority = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EndowmentId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.EndowmentId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Amount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgDepositToEndowmentResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgDepositToEndowmentResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgDepositToEndowmentResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgDistributeYield) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgDistributeYield: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgDistributeYield: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Authority", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Authority = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EndowmentId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.EndowmentId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgDistributeYieldResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgDistributeYieldResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgDistributeYieldResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AmountDistributed", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.AmountDistributed.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgRebalanceStrategies) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRebalanceStrategies: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRebalanceStrategies: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Authority", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Authority = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EndowmentId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.EndowmentId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgRebalanceStrategiesResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRebalanceStrategiesResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRebalanceStrategiesResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateStrategyAllocation) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateStrategyAllocation: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateStrategyAllocation: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Authority", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Authority = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StrategyId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.StrategyId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field NewAllocationPercentage", wireType)
			}
			m.NewAllocationPercentage = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.NewAllocationPercentage |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateStrategyAllocationResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateStrategyAllocationResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateStrategyAllocationResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgDistributeToSocialPrograms) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgDistributeToSocialPrograms: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgDistributeToSocialPrograms: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Authority", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Authority = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgDistributeToSocialProgramsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgDistributeToSocialProgramsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgDistributeToSocialProgramsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalDistributed", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.TotalDistributed.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateParams) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateParams: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateParams: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Authority", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Authority = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
