// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: aequitas/agentkit/v1/agentkit.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	github_com_cosmos_gogoproto_types "github.com/cosmos/gogoproto/types"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Agent status constants
type AgentStatus int32

const (
	AgentStatus_AGENT_STATUS_UNSPECIFIED AgentStatus = 0
	AgentStatus_AGENT_STATUS_ACTIVE      AgentStatus = 1
	AgentStatus_AGENT_STATUS_PAUSED      AgentStatus = 2
	AgentStatus_AGENT_STATUS_COMPLETED   AgentStatus = 3
)

var AgentStatus_name = map[int32]string{
	0: "AGENT_STATUS_UNSPECIFIED",
	1: "AGENT_STATUS_ACTIVE",
	2: "AGENT_STATUS_PAUSED",
	3: "AGENT_STATUS_COMPLETED",
}

var AgentStatus_value = map[string]int32{
	"AGENT_STATUS_UNSPECIFIED": 0,
	"AGENT_STATUS_ACTIVE":      1,
	"AGENT_STATUS_PAUSED":      2,
	"AGENT_STATUS_COMPLETED":   3,
}

func (x AgentStatus) String() string {
	return proto.EnumName(AgentStatus_name, int32(x))
}

func (AgentStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_7e55eb067abd5245, []int{0}
}

// Agent represents an autonomous Justice Agent
type Agent struct {
	Id         string                                   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Creator    string                                   `protobuf:"bytes,2,opt,name=creator,proto3" json:"creator,omitempty"`
	Wallet     string                                   `protobuf:"bytes,3,opt,name=wallet,proto3" json:"wallet,omitempty"`
	Objective  string                                   `protobuf:"bytes,4,opt,name=objective,proto3" json:"objective,omitempty"`
	Budget     github_com_cosmos_cosmos_sdk_types.Coins `protobuf:"bytes,5,rep,name=budget,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.Coins" json:"budget"`
	Rules      []string                                 `protobuf:"bytes,6,rep,name=rules,proto3" json:"rules,omitempty"`
	Status     string                                   `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt  time.Time                                `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3,stdtime" json:"created_at"`
	LastAction time.Time                                `protobuf:"bytes,9,opt,name=last_action,json=lastAction,proto3,stdtime" json:"last_action"`
	MissionLog []MissionEntry                           `protobuf:"bytes,10,rep,name=mission_log,json=missionLog,proto3" json:"mission_log"`
}

func (m *Agent) Reset()         { *m = Agent{} }
func (m *Agent) String() string { return proto.CompactTextString(m) }
func (*Agent) ProtoMessage()    {}
func (*Agent) Descriptor() ([]byte, []int) {
	return fileDescriptor_7e55eb067abd5245, []int{0}
}
func (m *Agent) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Agent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Agent.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Agent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Agent.Merge(m, src)
}
func (m *Agent) XXX_Size() int {
	return m.Size()
}
func (m *Agent) XXX_DiscardUnknown() {
	xxx_messageInfo_Agent.DiscardUnknown(m)
}

var xxx_messageInfo_Agent proto.InternalMessageInfo

// MissionEntry logs agent actions
type MissionEntry struct {
	Timestamp time.Time `protobuf:"bytes,1,opt,name=timestamp,proto3,stdtime" json:"timestamp"`
	Tool      string    `protobuf:"bytes,2,opt,name=tool,proto3" json:"tool,omitempty"`
	Action    string    `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"`
	Result    string    `protobuf:"bytes,4,opt,name=result,proto3" json:"result,omitempty"`
}

func (m *MissionEntry) Reset()         { *m = MissionEntry{} }
func (m *MissionEntry) String() string { return proto.CompactTextString(m) }
func (*MissionEntry) ProtoMessage()    {}
func (*MissionEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_7e55eb067abd5245, []int{1}
}
func (m *MissionEntry) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MissionEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MissionEntry.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MissionEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MissionEntry.Merge(m, src)
}
func (m *MissionEntry) XXX_Size() int {
	return m.Size()
}
func (m *MissionEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_MissionEntry.DiscardUnknown(m)
}

var xxx_messageInfo_MissionEntry proto.InternalMessageInfo

func init() {
	proto.RegisterEnum("aequitas.agentkit.v1.AgentStatus", AgentStatus_name, AgentStatus_value)
	proto.RegisterType((*Agent)(nil), "aequitas.agentkit.v1.Agent")
	proto.RegisterType((*MissionEntry)(nil), "aequitas.agentkit.v1.MissionEntry")
}

func init() {
	proto.RegisterFile("aequitas/agentkit/v1/agentkit.proto", fileDescriptor_7e55eb067abd5245)
}

var fileDescriptor_7e55eb067abd5245 = []byte{
	// 623 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0x41, 0x6f, 0xd3, 0x30,
	0x18, 0x6d, 0xda, 0xae, 0x5b, 0x5d, 0x84, 0x2a, 0x53, 0x8d, 0xac, 0x9a, 0xd2, 0x6a, 0x5c, 0x2a,
	0xa4, 0x25, 0xeb, 0x76, 0xe3, 0x96, 0xb6, 0x01, 0x55, 0x5a, 0xb7, 0x2a, 0xed, 0x38, 0x70, 0x89,
	0x9c, 0xc4, 0x04, 0xb3, 0x34, 0x1e, 0xb1, 0x53, 0xd8, 0x3f, 0xe0, 0xc6, 0x7e, 0xc2, 0xce, 0x9c,
	0xf9, 0x11, 0x3b, 0x4e, 0x9c, 0x38, 0x31, 0xb4, 0x5d, 0xf8, 0x19, 0x28, 0xb6, 0xdb, 0x6d, 0x02,
	0x09, 0x38, 0xd5, 0x9f, 0xdf, 0x7b, 0x5f, 0xbe, 0xef, 0xf5, 0xc9, 0xe0, 0x09, 0xc2, 0xef, 0x32,
	0xc2, 0x11, 0xb3, 0x50, 0x84, 0x13, 0x7e, 0x4c, 0xb8, 0x35, 0xef, 0x2e, 0xcf, 0xe6, 0x49, 0x4a,
	0x39, 0x85, 0x8d, 0x05, 0xc9, 0x5c, 0x02, 0xf3, 0x6e, 0xb3, 0x11, 0xd1, 0x88, 0x0a, 0x82, 0x95,
	0x9f, 0x24, 0xb7, 0xb9, 0x11, 0x50, 0x36, 0xa3, 0xcc, 0x93, 0x80, 0x2c, 0x14, 0x64, 0xc8, 0xca,
	0xf2, 0x11, 0xc3, 0xd6, 0xbc, 0xeb, 0x63, 0x8e, 0xba, 0x56, 0x40, 0x49, 0xa2, 0xf0, 0x56, 0x44,
	0x69, 0x14, 0x63, 0x4b, 0x54, 0x7e, 0xf6, 0xda, 0xe2, 0x64, 0x86, 0x19, 0x47, 0xb3, 0x13, 0x49,
	0xd8, 0xfa, 0x54, 0x06, 0x2b, 0x76, 0x3e, 0x01, 0x7c, 0x08, 0x8a, 0x24, 0xd4, 0xb5, 0xb6, 0xd6,
	0xa9, 0xba, 0x45, 0x12, 0xc2, 0x5d, 0xb0, 0x1a, 0xa4, 0x18, 0x71, 0x9a, 0xea, 0xc5, 0xfc, 0xb2,
	0xa7, 0x7f, 0xfd, 0xb2, 0xdd, 0x50, 0x5f, 0xb7, 0xc3, 0x30, 0xc5, 0x8c, 0x4d, 0x78, 0x4a, 0x92,
	0xc8, 0x5d, 0x10, 0xe1, 0x0e, 0xa8, 0xbc, 0x47, 0x71, 0x8c, 0xb9, 0x5e, 0xfa, 0x8b, 0x44, 0xf1,
	0xe0, 0x26, 0xa8, 0x52, 0xff, 0x2d, 0x0e, 0x38, 0x99, 0x63, 0xbd, 0x2c, 0x3e, 0x7e, 0x7b, 0x01,
	0x03, 0x50, 0xf1, 0xb3, 0x30, 0xc2, 0x5c, 0x5f, 0x69, 0x97, 0x3a, 0xb5, 0xdd, 0x0d, 0x53, 0x35,
	0xcb, 0xf7, 0x35, 0xd5, 0xbe, 0x66, 0x9f, 0x92, 0xa4, 0xb7, 0x73, 0xf1, 0xbd, 0x55, 0xf8, 0x7c,
	0xd5, 0xea, 0x44, 0x84, 0xbf, 0xc9, 0x7c, 0x33, 0xa0, 0x33, 0x65, 0x95, 0xfa, 0xd9, 0x66, 0xe1,
	0xb1, 0xc5, 0x4f, 0x4f, 0x30, 0x13, 0x02, 0xe6, 0xaa, 0xd6, 0xb0, 0x01, 0x56, 0xd2, 0x2c, 0xc6,
	0x4c, 0xaf, 0xb4, 0x4b, 0x9d, 0xaa, 0x2b, 0x0b, 0xb8, 0x0e, 0x2a, 0x8c, 0x23, 0x9e, 0x31, 0x7d,
	0x55, 0x4c, 0xa5, 0x2a, 0xd8, 0x07, 0x40, 0x6c, 0x8b, 0x43, 0x0f, 0x71, 0x7d, 0xad, 0xad, 0x75,
	0x6a, 0xbb, 0x4d, 0x53, 0xda, 0x6c, 0x2e, 0x6c, 0x36, 0xa7, 0x0b, 0x9b, 0x7b, 0x6b, 0xf9, 0x5c,
	0x67, 0x57, 0x2d, 0xcd, 0xad, 0x2a, 0x9d, 0xcd, 0xa1, 0x03, 0x6a, 0x31, 0x62, 0xdc, 0x43, 0x01,
	0x27, 0x34, 0xd1, 0xab, 0xff, 0xd1, 0x05, 0xe4, 0x42, 0x5b, 0xe8, 0xe0, 0x10, 0xd4, 0x66, 0x84,
	0x31, 0x42, 0x13, 0x2f, 0xa6, 0x91, 0x0e, 0x84, 0x47, 0x5b, 0xe6, 0x9f, 0xa2, 0x65, 0x8e, 0x24,
	0xd1, 0x49, 0x78, 0x7a, 0xda, 0x2b, 0xe7, 0xed, 0x5c, 0xa0, 0xc4, 0xfb, 0x34, 0x7a, 0xb6, 0xf6,
	0xf1, 0xbc, 0x55, 0xf8, 0x79, 0xde, 0xd2, 0xb6, 0xce, 0x35, 0xf0, 0xe0, 0x2e, 0x19, 0xf6, 0x40,
	0x75, 0x99, 0x1a, 0x91, 0x8f, 0x7f, 0x5e, 0x78, 0x29, 0x83, 0x10, 0x94, 0x39, 0xa5, 0xb1, 0x4c,
	0x92, 0x2b, 0xce, 0xb9, 0xc3, 0x6a, 0xff, 0x92, 0x74, 0x58, 0x56, 0xf9, 0x7d, 0x8a, 0x59, 0x16,
	0x73, 0x95, 0x07, 0x55, 0xdd, 0x8e, 0xf8, 0xf4, 0x14, 0xd4, 0x44, 0x66, 0x27, 0xf2, 0x2f, 0xd9,
	0x04, 0xba, 0xfd, 0xc2, 0x39, 0x98, 0x7a, 0x93, 0xa9, 0x3d, 0x3d, 0x9a, 0x78, 0x47, 0x07, 0x93,
	0xb1, 0xd3, 0x1f, 0x3e, 0x1f, 0x3a, 0x83, 0x7a, 0x01, 0x3e, 0x06, 0x8f, 0xee, 0xa1, 0x76, 0x7f,
	0x3a, 0x7c, 0xe9, 0xd4, 0xb5, 0xdf, 0x80, 0xb1, 0x7d, 0x34, 0x71, 0x06, 0xf5, 0x22, 0x6c, 0x82,
	0xf5, 0x7b, 0x40, 0xff, 0x70, 0x34, 0xde, 0x77, 0xa6, 0xce, 0xa0, 0x5e, 0xea, 0x8d, 0x2e, 0xae,
	0x0d, 0xed, 0xf2, 0xda, 0xd0, 0x7e, 0x5c, 0x1b, 0xda, 0xd9, 0x8d, 0x51, 0xb8, 0xbc, 0x31, 0x0a,
	0xdf, 0x6e, 0x8c, 0xc2, 0xab, 0xbd, 0x3b, 0xc1, 0xeb, 0xa7, 0x98, 0x0e, 0xec, 0xd1, 0xa1, 0xe5,
	0x3a, 0x63, 0xdb, 0xb5, 0x96, 0x0f, 0xc2, 0x87, 0xdb, 0x27, 0x41, 0x24, 0xd1, 0xaf, 0x08, 0x03,
	0xf7, 0x7e, 0x05, 0x00, 0x00, 0xff, 0xff, 0x46, 0x33, 0x37, 0x11, 0x34, 0x04, 0x00, 0x00,
}

func (this *Agent) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Agent)
	if !ok {
		that2, ok := that.(Agent)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Id != that1.Id {
		return false
	}
	if this.Creator != that1.Creator {
		return false
	}
	if this.Wallet != that1.Wallet {
		return false
	}
	if this.Objective != that1.Objective {
		return false
	}
	if len(this.Budget) != len(that1.Budget) {
		return false
	}
	for i := range this.Budget {
		if !this.Budget[i].Equal(&that1.Budget[i]) {
			return false
		}
	}
	if len(this.Rules) != len(that1.Rules) {
		return false
	}
	for i := range this.Rules {
		if this.Rules[i] != that1.Rules[i] {
			return false
		}
	}
	if this.Status != that1.Status {
		return false
	}
	if !this.CreatedAt.Equal(that1.CreatedAt) {
		return false
	}
	if !this.LastAction.Equal(that1.LastAction) {
		return false
	}
	if len(this.MissionLog) != len(that1.MissionLog) {
		return false
	}
	for i := range this.MissionLog {
		if !this.MissionLog[i].Equal(&that1.MissionLog[i]) {
			return false
		}
	}
	return true
}
func (this *MissionEntry) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*MissionEntry)
	if !ok {
		that2, ok := that.(MissionEntry)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.Timestamp.Equal(that1.Timestamp) {
		return false
	}
	if this.Tool != that1.Tool {
		return false
	}
	if this.Action != that1.Action {
		return false
	}
	if this.Result != that1.Result {
		return false
	}
	return true
}
func (m *Agent) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Agent) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Agent) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.MissionLog) > 0 {
		for iNdEx := len(m.MissionLog) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.MissionLog[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintAgentkit(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x52
		}
	}
	n1, err1 := github_com_cosmos_gogoproto_types.StdTimeMarshalTo(m.LastAction, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdTime(m.LastAction):])
	if err1 != nil {
		return 0, err1
	}
	i -= n1
	i = encodeVarintAgentkit(dAtA, i, uint64(n1))
	i--
	dAtA[i] = 0x4a
	n2, err2 := github_com_cosmos_gogoproto_types.StdTimeMarshalTo(m.CreatedAt, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdTime(m.CreatedAt):])
	if err2 != nil {
		return 0, err2
	}
	i -= n2
	i = encodeVarintAgentkit(dAtA, i, uint64(n2))
	i--
	dAtA[i] = 0x42
	if len(m.Status) > 0 {
		i -= len(m.Status)
		copy(dAtA[i:], m.Status)
		i = encodeVarintAgentkit(dAtA, i, uint64(len(m.Status)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.Rules) > 0 {
		for iNdEx := len(m.Rules) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Rules[iNdEx])
			copy(dAtA[i:], m.Rules[iNdEx])
			i = encodeVarintAgentkit(dAtA, i, uint64(len(m.Rules[iNdEx])))
			i--
			dAtA[i] = 0x32
		}
	}
	if len(m.Budget) > 0 {
		for iNdEx := len(m.Budget) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Budget[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintAgentkit(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x2a
		}
	}
	if len(m.Objective) > 0 {
		i -= len(m.Objective)
		copy(dAtA[i:], m.Objective)
		i = encodeVarintAgentkit(dAtA, i, uint64(len(m.Objective)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Wallet) > 0 {
		i -= len(m.Wallet)
		copy(dAtA[i:], m.Wallet)
		i = encodeVarintAgentkit(dAtA, i, uint64(len(m.Wallet)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintAgentkit(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Id) > 0 {
		i -= len(m.Id)
		copy(dAtA[i:], m.Id)
		i = encodeVarintAgentkit(dAtA, i, uint64(len(m.Id)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MissionEntry) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MissionEntry) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MissionEntry) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Result) > 0 {
		i -= len(m.Result)
		copy(dAtA[i:], m.Result)
		i = encodeVarintAgentkit(dAtA, i, uint64(len(m.Result)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Action) > 0 {
		i -= len(m.Action)
		copy(dAtA[i:], m.Action)
		i = encodeVarintAgentkit(dAtA, i, uint64(len(m.Action)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Tool) > 0 {
		i -= len(m.Tool)
		copy(dAtA[i:], m.Tool)
		i = encodeVarintAgentkit(dAtA, i, uint64(len(m.Tool)))
		i--
		dAtA[i] = 0x12
	}
	n3, err3 := github_com_cosmos_gogoproto_types.StdTimeMarshalTo(m.Timestamp, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdTime(m.Timestamp):])
	if err3 != nil {
		return 0, err3
	}
	i -= n3
	i = encodeVarintAgentkit(dAtA, i, uint64(n3))
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintAgentkit(dAtA []byte, offset int, v uint64) int {
	offset -= sovAgentkit(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Agent) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Id)
	if l > 0 {
		n += 1 + l + sovAgentkit(uint64(l))
	}
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovAgentkit(uint64(l))
	}
	l = len(m.Wallet)
	if l > 0 {
		n += 1 + l + sovAgentkit(uint64(l))
	}
	l = len(m.Objective)
	if l > 0 {
		n += 1 + l + sovAgentkit(uint64(l))
	}
	if len(m.Budget) > 0 {
		for _, e := range m.Budget {
			l = e.Size()
			n += 1 + l + sovAgentkit(uint64(l))
		}
	}
	if len(m.Rules) > 0 {
		for _, s := range m.Rules {
			l = len(s)
			n += 1 + l + sovAgentkit(uint64(l))
		}
	}
	l = len(m.Status)
	if l > 0 {
		n += 1 + l + sovAgentkit(uint64(l))
	}
	l = github_com_cosmos_gogoproto_types.SizeOfStdTime(m.CreatedAt)
	n += 1 + l + sovAgentkit(uint64(l))
	l = github_com_cosmos_gogoproto_types.SizeOfStdTime(m.LastAction)
	n += 1 + l + sovAgentkit(uint64(l))
	if len(m.MissionLog) > 0 {
		for _, e := range m.MissionLog {
			l = e.Size()
			n += 1 + l + sovAgentkit(uint64(l))
		}
	}
	return n
}

func (m *MissionEntry) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = github_com_cosmos_gogoproto_types.SizeOfStdTime(m.Timestamp)
	n += 1 + l + sovAgentkit(uint64(l))
	l = len(m.Tool)
	if l > 0 {
		n += 1 + l + sovAgentkit(uint64(l))
	}
	l = len(m.Action)
	if l > 0 {
		n += 1 + l + sovAgentkit(uint64(l))
	}
	l = len(m.Result)
	if l > 0 {
		n += 1 + l + sovAgentkit(uint64(l))
	}
	return n
}

func sovAgentkit(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozAgentkit(x uint64) (n int) {
	return sovAgentkit(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Agent) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAgentkit
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Agent: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Agent: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAgentkit
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAgentkit
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAgentkit
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAgentkit
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAgentkit
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAgentkit
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Wallet", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAgentkit
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAgentkit
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAgentkit
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Wallet = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Objective", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAgentkit
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAgentkit
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAgentkit
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Objective = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Budget", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAgentkit
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthAgentkit
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthAgentkit
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Budget = append(m.Budget, types.Coin{})
			if err := m.Budget[len(m.Budget)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Rules", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAgentkit
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAgentkit
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAgentkit
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Rules = append(m.Rules, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAgentkit
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAgentkit
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAgentkit
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Status = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreatedAt", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAgentkit
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthAgentkit
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthAgentkit
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdTimeUnmarshal(&m.CreatedAt, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastAction", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAgentkit
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthAgentkit
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthAgentkit
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdTimeUnmarshal(&m.LastAction, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MissionLog", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAgentkit
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthAgentkit
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthAgentkit
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MissionLog = append(m.MissionLog, MissionEntry{})
			if err := m.MissionLog[len(m.MissionLog)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipAgentkit(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthAgentkit
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MissionEntry) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAgentkit
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MissionEntry: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MissionEntry: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Timestamp", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAgentkit
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthAgentkit
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthAgentkit
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdTimeUnmarshal(&m.Timestamp, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Tool", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAgentkit
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAgentkit
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAgentkit
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Tool = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Action", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAgentkit
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAgentkit
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAgentkit
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Action = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Result", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAgentkit
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAgentkit
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAgentkit
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Result = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipAgentkit(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthAgentkit
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipAgentkit(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowAgentkit
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowAgentkit
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowAgentkit
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthAgentkit
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupAgentkit
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthAgentkit
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthAgentkit        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowAgentkit          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupAgentkit = fmt.Errorf("proto: unexpected end of group")
)
