// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: aequitas/claims/v1/query.proto

package types

import (
	context "context"
	fmt "fmt"
	query "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type QueryGetClaimRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *QueryGetClaimRequest) Reset()         { *m = QueryGetClaimRequest{} }
func (m *QueryGetClaimRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetClaimRequest) ProtoMessage()    {}
func (*QueryGetClaimRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_66d8745efa1200b5, []int{0}
}
func (m *QueryGetClaimRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetClaimRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetClaimRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetClaimRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetClaimRequest.Merge(m, src)
}
func (m *QueryGetClaimRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetClaimRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetClaimRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetClaimRequest proto.InternalMessageInfo

func (m *QueryGetClaimRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type QueryGetClaimResponse struct {
	Claim ArbitrationClaim `protobuf:"bytes,1,opt,name=claim,proto3" json:"claim"`
}

func (m *QueryGetClaimResponse) Reset()         { *m = QueryGetClaimResponse{} }
func (m *QueryGetClaimResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetClaimResponse) ProtoMessage()    {}
func (*QueryGetClaimResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_66d8745efa1200b5, []int{1}
}
func (m *QueryGetClaimResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetClaimResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetClaimResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetClaimResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetClaimResponse.Merge(m, src)
}
func (m *QueryGetClaimResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetClaimResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetClaimResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetClaimResponse proto.InternalMessageInfo

func (m *QueryGetClaimResponse) GetClaim() ArbitrationClaim {
	if m != nil {
		return m.Claim
	}
	return ArbitrationClaim{}
}

type QueryListClaimsRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryListClaimsRequest) Reset()         { *m = QueryListClaimsRequest{} }
func (m *QueryListClaimsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryListClaimsRequest) ProtoMessage()    {}
func (*QueryListClaimsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_66d8745efa1200b5, []int{2}
}
func (m *QueryListClaimsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryListClaimsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryListClaimsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryListClaimsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryListClaimsRequest.Merge(m, src)
}
func (m *QueryListClaimsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryListClaimsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryListClaimsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryListClaimsRequest proto.InternalMessageInfo

func (m *QueryListClaimsRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryListClaimsResponse struct {
	Claims     []ArbitrationClaim  `protobuf:"bytes,1,rep,name=claims,proto3" json:"claims"`
	Pagination *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryListClaimsResponse) Reset()         { *m = QueryListClaimsResponse{} }
func (m *QueryListClaimsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryListClaimsResponse) ProtoMessage()    {}
func (*QueryListClaimsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_66d8745efa1200b5, []int{3}
}
func (m *QueryListClaimsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryListClaimsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryListClaimsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryListClaimsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryListClaimsResponse.Merge(m, src)
}
func (m *QueryListClaimsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryListClaimsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryListClaimsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryListClaimsResponse proto.InternalMessageInfo

func (m *QueryListClaimsResponse) GetClaims() []ArbitrationClaim {
	if m != nil {
		return m.Claims
	}
	return nil
}

func (m *QueryListClaimsResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryListClaimsByDefendantRequest struct {
	DefendantId string             `protobuf:"bytes,1,opt,name=defendant_id,json=defendantId,proto3" json:"defendant_id,omitempty"`
	Pagination  *query.PageRequest `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryListClaimsByDefendantRequest) Reset()         { *m = QueryListClaimsByDefendantRequest{} }
func (m *QueryListClaimsByDefendantRequest) String() string { return proto.CompactTextString(m) }
func (*QueryListClaimsByDefendantRequest) ProtoMessage()    {}
func (*QueryListClaimsByDefendantRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_66d8745efa1200b5, []int{4}
}
func (m *QueryListClaimsByDefendantRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryListClaimsByDefendantRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryListClaimsByDefendantRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryListClaimsByDefendantRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryListClaimsByDefendantRequest.Merge(m, src)
}
func (m *QueryListClaimsByDefendantRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryListClaimsByDefendantRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryListClaimsByDefendantRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryListClaimsByDefendantRequest proto.InternalMessageInfo

func (m *QueryListClaimsByDefendantRequest) GetDefendantId() string {
	if m != nil {
		return m.DefendantId
	}
	return ""
}

func (m *QueryListClaimsByDefendantRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryListClaimsByDefendantResponse struct {
	Claims     []ArbitrationClaim  `protobuf:"bytes,1,rep,name=claims,proto3" json:"claims"`
	Pagination *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryListClaimsByDefendantResponse) Reset()         { *m = QueryListClaimsByDefendantResponse{} }
func (m *QueryListClaimsByDefendantResponse) String() string { return proto.CompactTextString(m) }
func (*QueryListClaimsByDefendantResponse) ProtoMessage()    {}
func (*QueryListClaimsByDefendantResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_66d8745efa1200b5, []int{5}
}
func (m *QueryListClaimsByDefendantResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryListClaimsByDefendantResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryListClaimsByDefendantResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryListClaimsByDefendantResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryListClaimsByDefendantResponse.Merge(m, src)
}
func (m *QueryListClaimsByDefendantResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryListClaimsByDefendantResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryListClaimsByDefendantResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryListClaimsByDefendantResponse proto.InternalMessageInfo

func (m *QueryListClaimsByDefendantResponse) GetClaims() []ArbitrationClaim {
	if m != nil {
		return m.Claims
	}
	return nil
}

func (m *QueryListClaimsByDefendantResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryListClaimsByClaimantRequest struct {
	Claimant   string             `protobuf:"bytes,1,opt,name=claimant,proto3" json:"claimant,omitempty"`
	Pagination *query.PageRequest `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryListClaimsByClaimantRequest) Reset()         { *m = QueryListClaimsByClaimantRequest{} }
func (m *QueryListClaimsByClaimantRequest) String() string { return proto.CompactTextString(m) }
func (*QueryListClaimsByClaimantRequest) ProtoMessage()    {}
func (*QueryListClaimsByClaimantRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_66d8745efa1200b5, []int{6}
}
func (m *QueryListClaimsByClaimantRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryListClaimsByClaimantRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryListClaimsByClaimantRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryListClaimsByClaimantRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryListClaimsByClaimantRequest.Merge(m, src)
}
func (m *QueryListClaimsByClaimantRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryListClaimsByClaimantRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryListClaimsByClaimantRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryListClaimsByClaimantRequest proto.InternalMessageInfo

func (m *QueryListClaimsByClaimantRequest) GetClaimant() string {
	if m != nil {
		return m.Claimant
	}
	return ""
}

func (m *QueryListClaimsByClaimantRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryListClaimsByClaimantResponse struct {
	Claims     []ArbitrationClaim  `protobuf:"bytes,1,rep,name=claims,proto3" json:"claims"`
	Pagination *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryListClaimsByClaimantResponse) Reset()         { *m = QueryListClaimsByClaimantResponse{} }
func (m *QueryListClaimsByClaimantResponse) String() string { return proto.CompactTextString(m) }
func (*QueryListClaimsByClaimantResponse) ProtoMessage()    {}
func (*QueryListClaimsByClaimantResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_66d8745efa1200b5, []int{7}
}
func (m *QueryListClaimsByClaimantResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryListClaimsByClaimantResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryListClaimsByClaimantResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryListClaimsByClaimantResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryListClaimsByClaimantResponse.Merge(m, src)
}
func (m *QueryListClaimsByClaimantResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryListClaimsByClaimantResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryListClaimsByClaimantResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryListClaimsByClaimantResponse proto.InternalMessageInfo

func (m *QueryListClaimsByClaimantResponse) GetClaims() []ArbitrationClaim {
	if m != nil {
		return m.Claims
	}
	return nil
}

func (m *QueryListClaimsByClaimantResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryGetClaimRequest)(nil), "aequitas.claims.v1.QueryGetClaimRequest")
	proto.RegisterType((*QueryGetClaimResponse)(nil), "aequitas.claims.v1.QueryGetClaimResponse")
	proto.RegisterType((*QueryListClaimsRequest)(nil), "aequitas.claims.v1.QueryListClaimsRequest")
	proto.RegisterType((*QueryListClaimsResponse)(nil), "aequitas.claims.v1.QueryListClaimsResponse")
	proto.RegisterType((*QueryListClaimsByDefendantRequest)(nil), "aequitas.claims.v1.QueryListClaimsByDefendantRequest")
	proto.RegisterType((*QueryListClaimsByDefendantResponse)(nil), "aequitas.claims.v1.QueryListClaimsByDefendantResponse")
	proto.RegisterType((*QueryListClaimsByClaimantRequest)(nil), "aequitas.claims.v1.QueryListClaimsByClaimantRequest")
	proto.RegisterType((*QueryListClaimsByClaimantResponse)(nil), "aequitas.claims.v1.QueryListClaimsByClaimantResponse")
}

func init() { proto.RegisterFile("aequitas/claims/v1/query.proto", fileDescriptor_66d8745efa1200b5) }

var fileDescriptor_66d8745efa1200b5 = []byte{
	// 606 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x95, 0xcf, 0x6f, 0x12, 0x41,
	0x14, 0xc7, 0x19, 0x94, 0xa6, 0x4e, 0x8d, 0x87, 0x09, 0xd5, 0x66, 0xd3, 0x2c, 0xb0, 0x31, 0x6d,
	0xad, 0xc9, 0x8e, 0xb4, 0xd2, 0x8b, 0x17, 0xa1, 0xd5, 0xc6, 0xa8, 0xb1, 0xee, 0x4d, 0x2f, 0x3a,
	0xb0, 0xe3, 0x3a, 0x49, 0xd9, 0x01, 0x66, 0x20, 0x12, 0xc2, 0xc5, 0x83, 0xd1, 0x8b, 0x31, 0xf1,
	0x3f, 0xf0, 0xe0, 0x59, 0xcf, 0x1e, 0xbd, 0xf4, 0xd8, 0xc4, 0x8b, 0x27, 0x63, 0xc0, 0x3f, 0xc4,
	0x30, 0x3b, 0x0b, 0x14, 0x16, 0x04, 0xd3, 0x43, 0x4f, 0x0c, 0x6f, 0xde, 0x8f, 0xcf, 0xfb, 0x0e,
	0xef, 0x01, 0x4d, 0x42, 0xab, 0x75, 0x26, 0x89, 0xc0, 0xa5, 0x43, 0xc2, 0xca, 0x02, 0x37, 0xb2,
	0xb8, 0x5a, 0xa7, 0xb5, 0xa6, 0x5d, 0xa9, 0x71, 0xc9, 0x11, 0x0a, 0xef, 0xed, 0xe0, 0xde, 0x6e,
	0x64, 0x8d, 0x55, 0x8f, 0x73, 0xef, 0x90, 0x62, 0x52, 0x61, 0x98, 0xf8, 0x3e, 0x97, 0x44, 0x32,
	0xee, 0x8b, 0x20, 0xc2, 0xd8, 0x2c, 0x71, 0x51, 0xe6, 0x02, 0x17, 0x89, 0xa0, 0x41, 0x2a, 0xdc,
	0xc8, 0x16, 0xa9, 0x24, 0x59, 0x5c, 0x21, 0x1e, 0xf3, 0x95, 0xb3, 0xf6, 0x4d, 0x7a, 0xdc, 0xe3,
	0xea, 0x88, 0x7b, 0x27, 0x6d, 0x4d, 0x45, 0x30, 0xe9, 0xea, 0xca, 0xc1, 0x5a, 0x83, 0xc9, 0xc7,
	0xbd, 0xc4, 0xfb, 0x54, 0xee, 0xf6, 0xec, 0x0e, 0xad, 0xd6, 0xa9, 0x90, 0xe8, 0x12, 0x8c, 0x33,
	0x77, 0x05, 0xa4, 0xc1, 0xc6, 0x05, 0x27, 0xce, 0x5c, 0xeb, 0x09, 0x5c, 0x1e, 0xf1, 0x13, 0x15,
	0xee, 0x0b, 0x8a, 0x6e, 0xc3, 0x84, 0x4a, 0xa8, 0x7c, 0x97, 0xb6, 0xae, 0xda, 0xe3, 0x5d, 0xda,
	0xf9, 0x5a, 0x91, 0xc9, 0x9a, 0xa2, 0x55, 0xc1, 0x85, 0xf3, 0x47, 0xbf, 0x52, 0x31, 0x27, 0x08,
	0xb4, 0x9e, 0xc3, 0xcb, 0x2a, 0xf5, 0x03, 0x26, 0x82, 0xdc, 0x22, 0x84, 0xb8, 0x0b, 0xe1, 0xa0,
	0x4f, 0x5d, 0x60, 0xcd, 0x0e, 0x44, 0xb1, 0x7b, 0xa2, 0xd8, 0x81, 0xbe, 0x5a, 0x14, 0xfb, 0x80,
	0x78, 0x54, 0xc7, 0x3a, 0x43, 0x91, 0xd6, 0x67, 0x00, 0xaf, 0x8c, 0x95, 0xd0, 0xfc, 0x05, 0xb8,
	0x10, 0x80, 0xae, 0x80, 0xf4, 0xb9, 0x39, 0x1b, 0xd0, 0x91, 0x68, 0xff, 0x04, 0x67, 0x5c, 0x71,
	0xae, 0xff, 0x93, 0x33, 0x00, 0x38, 0x01, 0xfa, 0x1e, 0xc0, 0xcc, 0x08, 0x68, 0xa1, 0xb9, 0x47,
	0x5f, 0x50, 0xdf, 0x25, 0xbe, 0x0c, 0x65, 0xc9, 0xc0, 0x8b, 0x6e, 0x68, 0x7b, 0xd6, 0x7f, 0xa5,
	0xa5, 0xbe, 0xed, 0x9e, 0x3b, 0xa2, 0x5c, 0xfc, 0xbf, 0x95, 0xfb, 0x0a, 0xa0, 0x35, 0x0d, 0xe8,
	0x2c, 0x8a, 0xf8, 0x06, 0xc0, 0xf4, 0x18, 0xb3, 0xfa, 0x1c, 0xd2, 0xd0, 0x80, 0x8b, 0x25, 0x6d,
	0xd2, 0xfa, 0xf5, 0xbf, 0x9f, 0x9a, 0x78, 0x5f, 0xa2, 0x5e, 0x73, 0x00, 0x72, 0x06, 0xb5, 0xdb,
	0xfa, 0x94, 0x80, 0x09, 0x85, 0x8c, 0xde, 0x02, 0xb8, 0x18, 0x0e, 0x3b, 0xda, 0x88, 0x62, 0x8a,
	0xda, 0x1b, 0xc6, 0xb5, 0x19, 0x3c, 0x83, 0xba, 0xd6, 0xfa, 0xeb, 0x1f, 0x7f, 0x3e, 0xc6, 0x33,
	0x28, 0x85, 0x27, 0x2e, 0x29, 0xdc, 0x62, 0x6e, 0x1b, 0xbd, 0x03, 0x10, 0x0e, 0x24, 0x44, 0x9b,
	0x13, 0x4b, 0x8c, 0x6d, 0x10, 0xe3, 0xfa, 0x4c, 0xbe, 0x1a, 0xc8, 0x52, 0x40, 0xab, 0xc8, 0x98,
	0x0c, 0x84, 0xbe, 0x03, 0xb8, 0x1c, 0x39, 0x0b, 0x28, 0x37, 0x43, 0xa9, 0xf1, 0x61, 0x36, 0x76,
	0xe6, 0x0d, 0xd3, 0xb0, 0xb7, 0x14, 0x6c, 0x0e, 0x6d, 0x4f, 0x51, 0xaf, 0xbf, 0x11, 0x70, 0x6b,
	0x78, 0x61, 0xb4, 0xd1, 0x37, 0x00, 0x93, 0x51, 0x3f, 0x4a, 0x74, 0x73, 0x26, 0x9a, 0x91, 0x61,
	0x32, 0x72, 0x73, 0x46, 0xe9, 0x16, 0x76, 0x54, 0x0b, 0x37, 0x90, 0x3d, 0xa5, 0x85, 0x70, 0x28,
	0x71, 0x2b, 0x3c, 0xb5, 0x0b, 0xf7, 0x8f, 0x3a, 0x26, 0x38, 0xee, 0x98, 0xe0, 0x77, 0xc7, 0x04,
	0x1f, 0xba, 0x66, 0xec, 0xb8, 0x6b, 0xc6, 0x7e, 0x76, 0xcd, 0xd8, 0xd3, 0xac, 0xc7, 0xe4, 0xcb,
	0x7a, 0xd1, 0x2e, 0xf1, 0x32, 0xde, 0xad, 0x51, 0xbe, 0x97, 0x7f, 0xf8, 0x08, 0x3b, 0x77, 0x0e,
	0xf2, 0xce, 0xa0, 0xc4, 0xab, 0x30, 0xb5, 0x6c, 0x56, 0xa8, 0x28, 0x2e, 0xa8, 0xff, 0xc1, 0xed,
	0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0xfe, 0x7d, 0xdb, 0x4b, 0xbe, 0x07, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// GetClaim queries a claim by ID
	GetClaim(ctx context.Context, in *QueryGetClaimRequest, opts ...grpc.CallOption) (*QueryGetClaimResponse, error)
	// ListClaims queries all claims with pagination
	ListClaims(ctx context.Context, in *QueryListClaimsRequest, opts ...grpc.CallOption) (*QueryListClaimsResponse, error)
	// ListClaimsByDefendant queries claims by defendant ID
	ListClaimsByDefendant(ctx context.Context, in *QueryListClaimsByDefendantRequest, opts ...grpc.CallOption) (*QueryListClaimsByDefendantResponse, error)
	// ListClaimsByClaimant queries claims by claimant address
	ListClaimsByClaimant(ctx context.Context, in *QueryListClaimsByClaimantRequest, opts ...grpc.CallOption) (*QueryListClaimsByClaimantResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) GetClaim(ctx context.Context, in *QueryGetClaimRequest, opts ...grpc.CallOption) (*QueryGetClaimResponse, error) {
	out := new(QueryGetClaimResponse)
	err := c.cc.Invoke(ctx, "/aequitas.claims.v1.Query/GetClaim", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ListClaims(ctx context.Context, in *QueryListClaimsRequest, opts ...grpc.CallOption) (*QueryListClaimsResponse, error) {
	out := new(QueryListClaimsResponse)
	err := c.cc.Invoke(ctx, "/aequitas.claims.v1.Query/ListClaims", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ListClaimsByDefendant(ctx context.Context, in *QueryListClaimsByDefendantRequest, opts ...grpc.CallOption) (*QueryListClaimsByDefendantResponse, error) {
	out := new(QueryListClaimsByDefendantResponse)
	err := c.cc.Invoke(ctx, "/aequitas.claims.v1.Query/ListClaimsByDefendant", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ListClaimsByClaimant(ctx context.Context, in *QueryListClaimsByClaimantRequest, opts ...grpc.CallOption) (*QueryListClaimsByClaimantResponse, error) {
	out := new(QueryListClaimsByClaimantResponse)
	err := c.cc.Invoke(ctx, "/aequitas.claims.v1.Query/ListClaimsByClaimant", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// GetClaim queries a claim by ID
	GetClaim(context.Context, *QueryGetClaimRequest) (*QueryGetClaimResponse, error)
	// ListClaims queries all claims with pagination
	ListClaims(context.Context, *QueryListClaimsRequest) (*QueryListClaimsResponse, error)
	// ListClaimsByDefendant queries claims by defendant ID
	ListClaimsByDefendant(context.Context, *QueryListClaimsByDefendantRequest) (*QueryListClaimsByDefendantResponse, error)
	// ListClaimsByClaimant queries claims by claimant address
	ListClaimsByClaimant(context.Context, *QueryListClaimsByClaimantRequest) (*QueryListClaimsByClaimantResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) GetClaim(ctx context.Context, req *QueryGetClaimRequest) (*QueryGetClaimResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetClaim not implemented")
}
func (*UnimplementedQueryServer) ListClaims(ctx context.Context, req *QueryListClaimsRequest) (*QueryListClaimsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListClaims not implemented")
}
func (*UnimplementedQueryServer) ListClaimsByDefendant(ctx context.Context, req *QueryListClaimsByDefendantRequest) (*QueryListClaimsByDefendantResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListClaimsByDefendant not implemented")
}
func (*UnimplementedQueryServer) ListClaimsByClaimant(ctx context.Context, req *QueryListClaimsByClaimantRequest) (*QueryListClaimsByClaimantResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListClaimsByClaimant not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_GetClaim_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetClaimRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetClaim(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/aequitas.claims.v1.Query/GetClaim",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetClaim(ctx, req.(*QueryGetClaimRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ListClaims_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryListClaimsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ListClaims(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/aequitas.claims.v1.Query/ListClaims",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ListClaims(ctx, req.(*QueryListClaimsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ListClaimsByDefendant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryListClaimsByDefendantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ListClaimsByDefendant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/aequitas.claims.v1.Query/ListClaimsByDefendant",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ListClaimsByDefendant(ctx, req.(*QueryListClaimsByDefendantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ListClaimsByClaimant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryListClaimsByClaimantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ListClaimsByClaimant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/aequitas.claims.v1.Query/ListClaimsByClaimant",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ListClaimsByClaimant(ctx, req.(*QueryListClaimsByClaimantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var Query_serviceDesc = _Query_serviceDesc
var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "aequitas.claims.v1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetClaim",
			Handler:    _Query_GetClaim_Handler,
		},
		{
			MethodName: "ListClaims",
			Handler:    _Query_ListClaims_Handler,
		},
		{
			MethodName: "ListClaimsByDefendant",
			Handler:    _Query_ListClaimsByDefendant_Handler,
		},
		{
			MethodName: "ListClaimsByClaimant",
			Handler:    _Query_ListClaimsByClaimant_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "aequitas/claims/v1/query.proto",
}

func (m *QueryGetClaimRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetClaimRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetClaimRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Id) > 0 {
		i -= len(m.Id)
		copy(dAtA[i:], m.Id)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Id)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetClaimResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetClaimResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetClaimResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Claim.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryListClaimsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryListClaimsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryListClaimsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryListClaimsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryListClaimsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryListClaimsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Claims) > 0 {
		for iNdEx := len(m.Claims) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Claims[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryListClaimsByDefendantRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryListClaimsByDefendantRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryListClaimsByDefendantRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.DefendantId) > 0 {
		i -= len(m.DefendantId)
		copy(dAtA[i:], m.DefendantId)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.DefendantId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryListClaimsByDefendantResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryListClaimsByDefendantResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryListClaimsByDefendantResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Claims) > 0 {
		for iNdEx := len(m.Claims) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Claims[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryListClaimsByClaimantRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryListClaimsByClaimantRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryListClaimsByClaimantRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Claimant) > 0 {
		i -= len(m.Claimant)
		copy(dAtA[i:], m.Claimant)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Claimant)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryListClaimsByClaimantResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryListClaimsByClaimantResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryListClaimsByClaimantResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Claims) > 0 {
		for iNdEx := len(m.Claims) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Claims[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryGetClaimRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Id)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetClaimResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Claim.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryListClaimsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryListClaimsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Claims) > 0 {
		for _, e := range m.Claims {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryListClaimsByDefendantRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.DefendantId)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryListClaimsByDefendantResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Claims) > 0 {
		for _, e := range m.Claims {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryListClaimsByClaimantRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Claimant)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryListClaimsByClaimantResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Claims) > 0 {
		for _, e := range m.Claims {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryGetClaimRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetClaimRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetClaimRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetClaimResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetClaimResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetClaimResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Claim", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Claim.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryListClaimsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryListClaimsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryListClaimsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryListClaimsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryListClaimsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryListClaimsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Claims", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Claims = append(m.Claims, ArbitrationClaim{})
			if err := m.Claims[len(m.Claims)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryListClaimsByDefendantRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryListClaimsByDefendantRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryListClaimsByDefendantRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DefendantId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DefendantId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryListClaimsByDefendantResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryListClaimsByDefendantResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryListClaimsByDefendantResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Claims", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Claims = append(m.Claims, ArbitrationClaim{})
			if err := m.Claims[len(m.Claims)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryListClaimsByClaimantRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryListClaimsByClaimantRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryListClaimsByClaimantRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Claimant", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Claimant = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryListClaimsByClaimantResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryListClaimsByClaimantResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryListClaimsByClaimantResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Claims", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Claims = append(m.Claims, ArbitrationClaim{})
			if err := m.Claims[len(m.Claims)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
