// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: aequitas/distribution/v1/query.proto

package types

import (
	context "context"
	fmt "fmt"
	query "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type QueryGetDescendantRequest struct {
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
}

func (m *QueryGetDescendantRequest) Reset()         { *m = QueryGetDescendantRequest{} }
func (m *QueryGetDescendantRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetDescendantRequest) ProtoMessage()    {}
func (*QueryGetDescendantRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_160408124d85d75a, []int{0}
}
func (m *QueryGetDescendantRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetDescendantRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetDescendantRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetDescendantRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetDescendantRequest.Merge(m, src)
}
func (m *QueryGetDescendantRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetDescendantRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetDescendantRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetDescendantRequest proto.InternalMessageInfo

func (m *QueryGetDescendantRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type QueryGetDescendantResponse struct {
	Descendant DescendantRegistration `protobuf:"bytes,1,opt,name=descendant,proto3" json:"descendant"`
}

func (m *QueryGetDescendantResponse) Reset()         { *m = QueryGetDescendantResponse{} }
func (m *QueryGetDescendantResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetDescendantResponse) ProtoMessage()    {}
func (*QueryGetDescendantResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_160408124d85d75a, []int{1}
}
func (m *QueryGetDescendantResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetDescendantResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetDescendantResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetDescendantResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetDescendantResponse.Merge(m, src)
}
func (m *QueryGetDescendantResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetDescendantResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetDescendantResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetDescendantResponse proto.InternalMessageInfo

func (m *QueryGetDescendantResponse) GetDescendant() DescendantRegistration {
	if m != nil {
		return m.Descendant
	}
	return DescendantRegistration{}
}

type QueryListDescendantsRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryListDescendantsRequest) Reset()         { *m = QueryListDescendantsRequest{} }
func (m *QueryListDescendantsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryListDescendantsRequest) ProtoMessage()    {}
func (*QueryListDescendantsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_160408124d85d75a, []int{2}
}
func (m *QueryListDescendantsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryListDescendantsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryListDescendantsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryListDescendantsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryListDescendantsRequest.Merge(m, src)
}
func (m *QueryListDescendantsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryListDescendantsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryListDescendantsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryListDescendantsRequest proto.InternalMessageInfo

func (m *QueryListDescendantsRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryListDescendantsResponse struct {
	Descendants []DescendantRegistration `protobuf:"bytes,1,rep,name=descendants,proto3" json:"descendants"`
	Pagination  *query.PageResponse      `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryListDescendantsResponse) Reset()         { *m = QueryListDescendantsResponse{} }
func (m *QueryListDescendantsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryListDescendantsResponse) ProtoMessage()    {}
func (*QueryListDescendantsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_160408124d85d75a, []int{3}
}
func (m *QueryListDescendantsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryListDescendantsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryListDescendantsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryListDescendantsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryListDescendantsResponse.Merge(m, src)
}
func (m *QueryListDescendantsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryListDescendantsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryListDescendantsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryListDescendantsResponse proto.InternalMessageInfo

func (m *QueryListDescendantsResponse) GetDescendants() []DescendantRegistration {
	if m != nil {
		return m.Descendants
	}
	return nil
}

func (m *QueryListDescendantsResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryListDistributionsRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryListDistributionsRequest) Reset()         { *m = QueryListDistributionsRequest{} }
func (m *QueryListDistributionsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryListDistributionsRequest) ProtoMessage()    {}
func (*QueryListDistributionsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_160408124d85d75a, []int{4}
}
func (m *QueryListDistributionsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryListDistributionsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryListDistributionsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryListDistributionsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryListDistributionsRequest.Merge(m, src)
}
func (m *QueryListDistributionsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryListDistributionsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryListDistributionsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryListDistributionsRequest proto.InternalMessageInfo

func (m *QueryListDistributionsRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryListDistributionsResponse struct {
	Distributions []Distribution      `protobuf:"bytes,1,rep,name=distributions,proto3" json:"distributions"`
	Pagination    *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryListDistributionsResponse) Reset()         { *m = QueryListDistributionsResponse{} }
func (m *QueryListDistributionsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryListDistributionsResponse) ProtoMessage()    {}
func (*QueryListDistributionsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_160408124d85d75a, []int{5}
}
func (m *QueryListDistributionsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryListDistributionsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryListDistributionsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryListDistributionsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryListDistributionsResponse.Merge(m, src)
}
func (m *QueryListDistributionsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryListDistributionsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryListDistributionsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryListDistributionsResponse proto.InternalMessageInfo

func (m *QueryListDistributionsResponse) GetDistributions() []Distribution {
	if m != nil {
		return m.Distributions
	}
	return nil
}

func (m *QueryListDistributionsResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryGetDescendantRequest)(nil), "aequitas.distribution.v1.QueryGetDescendantRequest")
	proto.RegisterType((*QueryGetDescendantResponse)(nil), "aequitas.distribution.v1.QueryGetDescendantResponse")
	proto.RegisterType((*QueryListDescendantsRequest)(nil), "aequitas.distribution.v1.QueryListDescendantsRequest")
	proto.RegisterType((*QueryListDescendantsResponse)(nil), "aequitas.distribution.v1.QueryListDescendantsResponse")
	proto.RegisterType((*QueryListDistributionsRequest)(nil), "aequitas.distribution.v1.QueryListDistributionsRequest")
	proto.RegisterType((*QueryListDistributionsResponse)(nil), "aequitas.distribution.v1.QueryListDistributionsResponse")
}

func init() {
	proto.RegisterFile("aequitas/distribution/v1/query.proto", fileDescriptor_160408124d85d75a)
}

var fileDescriptor_160408124d85d75a = []byte{
	// 539 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x94, 0xbd, 0x6e, 0xd4, 0x40,
	0x14, 0x85, 0x77, 0x42, 0x00, 0x71, 0xa3, 0x08, 0x31, 0xa2, 0x58, 0x4c, 0x30, 0xc8, 0x82, 0x2c,
	0x3f, 0x62, 0x06, 0x27, 0x84, 0xa5, 0x4d, 0x08, 0xa4, 0x01, 0x91, 0xb8, 0x40, 0x88, 0x6e, 0xbc,
	0x1e, 0x19, 0x4b, 0xc4, 0xe3, 0xf5, 0x8c, 0x57, 0x44, 0x88, 0x86, 0x27, 0x40, 0xe2, 0x29, 0xa8,
	0x28, 0x28, 0xa8, 0x28, 0xe8, 0x52, 0x46, 0xa2, 0xa1, 0x42, 0x68, 0x97, 0x07, 0x41, 0x1e, 0xcf,
	0x62, 0x1b, 0xd6, 0x64, 0x57, 0xa4, 0xf3, 0xcf, 0x3d, 0xf7, 0x7e, 0xe7, 0xf8, 0x8e, 0xe1, 0x32,
	0xe3, 0xfd, 0x2c, 0x52, 0x4c, 0xd2, 0x20, 0x92, 0x2a, 0x8d, 0xfc, 0x4c, 0x45, 0x22, 0xa6, 0x03,
	0x97, 0xf6, 0x33, 0x9e, 0xee, 0x91, 0x24, 0x15, 0x4a, 0xe0, 0xf6, 0xb8, 0x8a, 0x54, 0xab, 0xc8,
	0xc0, 0xb5, 0x96, 0x42, 0x21, 0xc2, 0x17, 0x9c, 0xb2, 0x24, 0xa2, 0x2c, 0x8e, 0x85, 0x62, 0xf9,
	0x1b, 0x59, 0xe8, 0xac, 0xeb, 0x3d, 0x21, 0x77, 0x85, 0xa4, 0x3e, 0x93, 0xbc, 0x68, 0x48, 0x07,
	0xae, 0xcf, 0x15, 0x73, 0x69, 0xc2, 0xc2, 0x28, 0xd6, 0xc5, 0xa6, 0xf6, 0x6c, 0x28, 0x42, 0xa1,
	0x2f, 0x69, 0x7e, 0x65, 0x9e, 0xde, 0x68, 0xe4, 0xab, 0x91, 0xe8, 0x62, 0x67, 0x0d, 0xce, 0xed,
	0xe4, 0x43, 0xb6, 0xb8, 0xda, 0xe4, 0xb2, 0xc7, 0xe3, 0x80, 0xc5, 0xca, 0xe3, 0xfd, 0x8c, 0x4b,
	0x85, 0xdb, 0x70, 0x92, 0x05, 0x41, 0xca, 0xa5, 0x6c, 0xa3, 0x4b, 0xe8, 0xea, 0x29, 0x6f, 0x7c,
	0xeb, 0x28, 0xb0, 0x26, 0xc9, 0x64, 0x22, 0x62, 0xc9, 0xf1, 0x13, 0x80, 0xe0, 0xf7, 0x53, 0x2d,
	0x5d, 0x58, 0xb9, 0x45, 0x9a, 0x02, 0x21, 0xd5, 0x0e, 0x61, 0xfe, 0x4e, 0x7b, 0xdc, 0x98, 0xdf,
	0xff, 0x7e, 0xb1, 0xe5, 0x55, 0x3a, 0x39, 0x1c, 0xce, 0xeb, 0xa9, 0x0f, 0x23, 0x59, 0x19, 0x2b,
	0xc7, 0xb8, 0x0f, 0x00, 0xca, 0x88, 0xcc, 0xd8, 0x65, 0x52, 0xe4, 0x49, 0xf2, 0x3c, 0x49, 0xf1,
	0x81, 0x4c, 0x9e, 0x64, 0x9b, 0x85, 0xdc, 0x68, 0xbd, 0x8a, 0xd2, 0xf9, 0x82, 0x60, 0x69, 0xf2,
	0x1c, 0xe3, 0xef, 0x29, 0x2c, 0x94, 0x54, 0x79, 0x36, 0xc7, 0xfe, 0xc3, 0x60, 0xb5, 0x15, 0xde,
	0xaa, 0x59, 0x98, 0xd3, 0x16, 0x3a, 0x87, 0x5a, 0x28, 0xb0, 0x6a, 0x1e, 0x42, 0xb8, 0x50, 0x5a,
	0xa8, 0xe0, 0x1c, 0x79, 0x58, 0x9f, 0x11, 0xd8, 0x4d, 0x93, 0x4c, 0x5c, 0x1e, 0x2c, 0x56, 0x13,
	0x19, 0x07, 0xb6, 0xfc, 0x8f, 0xc0, 0x2a, 0xf7, 0x26, 0xa6, 0x7a, 0x8b, 0x23, 0x0b, 0x6a, 0xe5,
	0xfd, 0x3c, 0x1c, 0xd7, 0xfc, 0xf8, 0x23, 0x82, 0xc5, 0xda, 0x3e, 0xe3, 0xd5, 0x66, 0xc2, 0xc6,
	0x43, 0x63, 0xdd, 0x9e, 0x4d, 0x54, 0x20, 0x39, 0xdd, 0x37, 0x5f, 0x7f, 0xbe, 0x9b, 0x73, 0x31,
	0xa5, 0xcd, 0xa7, 0xb7, 0xdc, 0x13, 0xfa, 0xca, 0x1c, 0xc4, 0xd7, 0xf8, 0x03, 0x82, 0xd3, 0x7f,
	0xec, 0x29, 0x5e, 0x3b, 0x04, 0x61, 0xf2, 0xf9, 0xb1, 0xee, 0xcc, 0x2a, 0x33, 0xec, 0x37, 0x35,
	0x7b, 0x07, 0x5f, 0x99, 0x8a, 0x1d, 0x7f, 0x42, 0x70, 0xe6, 0xaf, 0x65, 0xc1, 0xdd, 0x69, 0x86,
	0x4f, 0x58, 0x64, 0xeb, 0xee, 0xec, 0x42, 0xc3, 0x4d, 0x35, 0xf7, 0x35, 0xdc, 0xa1, 0x53, 0xfd,
	0x31, 0xe5, 0xc6, 0xce, 0xfe, 0xd0, 0x46, 0x07, 0x43, 0x1b, 0xfd, 0x18, 0xda, 0xe8, 0xed, 0xc8,
	0x6e, 0x1d, 0x8c, 0xec, 0xd6, 0xb7, 0x91, 0xdd, 0x7a, 0xd6, 0x0d, 0x23, 0xf5, 0x3c, 0xf3, 0x49,
	0x4f, 0xec, 0xd2, 0x7b, 0x29, 0x17, 0x9b, 0xeb, 0x8f, 0x1e, 0x53, 0xef, 0xfe, 0xf6, 0xba, 0x57,
	0xf6, 0x7e, 0x59, 0xef, 0xae, 0xf6, 0x12, 0x2e, 0xfd, 0x13, 0xfa, 0x37, 0xbc, 0xfa, 0x2b, 0x00,
	0x00, 0xff, 0xff, 0xd0, 0x9b, 0xad, 0x88, 0x55, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// GetDescendant queries a descendant registration by address
	GetDescendant(ctx context.Context, in *QueryGetDescendantRequest, opts ...grpc.CallOption) (*QueryGetDescendantResponse, error)
	// ListDescendants queries all registered descendants
	ListDescendants(ctx context.Context, in *QueryListDescendantsRequest, opts ...grpc.CallOption) (*QueryListDescendantsResponse, error)
	// ListDistributions queries all distributions
	ListDistributions(ctx context.Context, in *QueryListDistributionsRequest, opts ...grpc.CallOption) (*QueryListDistributionsResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) GetDescendant(ctx context.Context, in *QueryGetDescendantRequest, opts ...grpc.CallOption) (*QueryGetDescendantResponse, error) {
	out := new(QueryGetDescendantResponse)
	err := c.cc.Invoke(ctx, "/aequitas.distribution.v1.Query/GetDescendant", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ListDescendants(ctx context.Context, in *QueryListDescendantsRequest, opts ...grpc.CallOption) (*QueryListDescendantsResponse, error) {
	out := new(QueryListDescendantsResponse)
	err := c.cc.Invoke(ctx, "/aequitas.distribution.v1.Query/ListDescendants", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ListDistributions(ctx context.Context, in *QueryListDistributionsRequest, opts ...grpc.CallOption) (*QueryListDistributionsResponse, error) {
	out := new(QueryListDistributionsResponse)
	err := c.cc.Invoke(ctx, "/aequitas.distribution.v1.Query/ListDistributions", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// GetDescendant queries a descendant registration by address
	GetDescendant(context.Context, *QueryGetDescendantRequest) (*QueryGetDescendantResponse, error)
	// ListDescendants queries all registered descendants
	ListDescendants(context.Context, *QueryListDescendantsRequest) (*QueryListDescendantsResponse, error)
	// ListDistributions queries all distributions
	ListDistributions(context.Context, *QueryListDistributionsRequest) (*QueryListDistributionsResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) GetDescendant(ctx context.Context, req *QueryGetDescendantRequest) (*QueryGetDescendantResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDescendant not implemented")
}
func (*UnimplementedQueryServer) ListDescendants(ctx context.Context, req *QueryListDescendantsRequest) (*QueryListDescendantsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListDescendants not implemented")
}
func (*UnimplementedQueryServer) ListDistributions(ctx context.Context, req *QueryListDistributionsRequest) (*QueryListDistributionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListDistributions not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_GetDescendant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetDescendantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetDescendant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/aequitas.distribution.v1.Query/GetDescendant",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetDescendant(ctx, req.(*QueryGetDescendantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ListDescendants_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryListDescendantsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ListDescendants(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/aequitas.distribution.v1.Query/ListDescendants",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ListDescendants(ctx, req.(*QueryListDescendantsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ListDistributions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryListDistributionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ListDistributions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/aequitas.distribution.v1.Query/ListDistributions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ListDistributions(ctx, req.(*QueryListDistributionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var Query_serviceDesc = _Query_serviceDesc
var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "aequitas.distribution.v1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetDescendant",
			Handler:    _Query_GetDescendant_Handler,
		},
		{
			MethodName: "ListDescendants",
			Handler:    _Query_ListDescendants_Handler,
		},
		{
			MethodName: "ListDistributions",
			Handler:    _Query_ListDistributions_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "aequitas/distribution/v1/query.proto",
}

func (m *QueryGetDescendantRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetDescendantRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetDescendantRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetDescendantResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetDescendantResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetDescendantResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Descendant.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryListDescendantsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryListDescendantsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryListDescendantsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryListDescendantsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryListDescendantsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryListDescendantsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Descendants) > 0 {
		for iNdEx := len(m.Descendants) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Descendants[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryListDistributionsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryListDistributionsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryListDistributionsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryListDistributionsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryListDistributionsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryListDistributionsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Distributions) > 0 {
		for iNdEx := len(m.Distributions) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Distributions[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryGetDescendantRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetDescendantResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Descendant.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryListDescendantsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryListDescendantsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Descendants) > 0 {
		for _, e := range m.Descendants {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryListDistributionsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryListDistributionsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Distributions) > 0 {
		for _, e := range m.Distributions {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryGetDescendantRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetDescendantRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetDescendantRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetDescendantResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetDescendantResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetDescendantResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Descendant", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Descendant.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryListDescendantsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryListDescendantsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryListDescendantsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryListDescendantsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryListDescendantsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryListDescendantsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Descendants", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Descendants = append(m.Descendants, DescendantRegistration{})
			if err := m.Descendants[len(m.Descendants)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryListDistributionsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryListDistributionsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryListDistributionsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryListDistributionsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryListDistributionsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryListDistributionsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Distributions", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Distributions = append(m.Distributions, Distribution{})
			if err := m.Distributions[len(m.Distributions)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
