// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: aequitas/distribution/v1/tx.proto

package types

import (
	context "context"
	cosmossdk_io_math "cosmossdk.io/math"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MsgRegisterDescendant struct {
	Applicant  string `protobuf:"bytes,1,opt,name=applicant,proto3" json:"applicant,omitempty"`
	LineageCid string `protobuf:"bytes,2,opt,name=lineage_cid,json=lineageCid,proto3" json:"lineage_cid,omitempty"`
}

func (m *MsgRegisterDescendant) Reset()         { *m = MsgRegisterDescendant{} }
func (m *MsgRegisterDescendant) String() string { return proto.CompactTextString(m) }
func (*MsgRegisterDescendant) ProtoMessage()    {}
func (*MsgRegisterDescendant) Descriptor() ([]byte, []int) {
	return fileDescriptor_b509fdec62041204, []int{0}
}
func (m *MsgRegisterDescendant) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRegisterDescendant) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRegisterDescendant.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRegisterDescendant) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRegisterDescendant.Merge(m, src)
}
func (m *MsgRegisterDescendant) XXX_Size() int {
	return m.Size()
}
func (m *MsgRegisterDescendant) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRegisterDescendant.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRegisterDescendant proto.InternalMessageInfo

type MsgRegisterDescendantResponse struct {
	Approved        bool   `protobuf:"varint,1,opt,name=approved,proto3" json:"approved,omitempty"`
	VerificationCid string `protobuf:"bytes,2,opt,name=verification_cid,json=verificationCid,proto3" json:"verification_cid,omitempty"`
}

func (m *MsgRegisterDescendantResponse) Reset()         { *m = MsgRegisterDescendantResponse{} }
func (m *MsgRegisterDescendantResponse) String() string { return proto.CompactTextString(m) }
func (*MsgRegisterDescendantResponse) ProtoMessage()    {}
func (*MsgRegisterDescendantResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b509fdec62041204, []int{1}
}
func (m *MsgRegisterDescendantResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRegisterDescendantResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRegisterDescendantResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRegisterDescendantResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRegisterDescendantResponse.Merge(m, src)
}
func (m *MsgRegisterDescendantResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgRegisterDescendantResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRegisterDescendantResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRegisterDescendantResponse proto.InternalMessageInfo

func (m *MsgRegisterDescendantResponse) GetApproved() bool {
	if m != nil {
		return m.Approved
	}
	return false
}

func (m *MsgRegisterDescendantResponse) GetVerificationCid() string {
	if m != nil {
		return m.VerificationCid
	}
	return ""
}

type MsgScheduleDistribution struct {
	Authority       string                `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	Type            DistributionType      `protobuf:"varint,2,opt,name=type,proto3,enum=aequitas.distribution.v1.DistributionType" json:"type,omitempty"`
	TotalAmount     cosmossdk_io_math.Int `protobuf:"bytes,3,opt,name=total_amount,json=totalAmount,proto3,customtype=cosmossdk.io/math.Int" json:"total_amount"`
	ScheduledTime   int64                 `protobuf:"varint,4,opt,name=scheduled_time,json=scheduledTime,proto3" json:"scheduled_time,omitempty"`
	SourceDefendant string                `protobuf:"bytes,5,opt,name=source_defendant,json=sourceDefendant,proto3" json:"source_defendant,omitempty"`
}

func (m *MsgScheduleDistribution) Reset()         { *m = MsgScheduleDistribution{} }
func (m *MsgScheduleDistribution) String() string { return proto.CompactTextString(m) }
func (*MsgScheduleDistribution) ProtoMessage()    {}
func (*MsgScheduleDistribution) Descriptor() ([]byte, []int) {
	return fileDescriptor_b509fdec62041204, []int{2}
}
func (m *MsgScheduleDistribution) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgScheduleDistribution) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgScheduleDistribution.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgScheduleDistribution) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgScheduleDistribution.Merge(m, src)
}
func (m *MsgScheduleDistribution) XXX_Size() int {
	return m.Size()
}
func (m *MsgScheduleDistribution) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgScheduleDistribution.DiscardUnknown(m)
}

var xxx_messageInfo_MsgScheduleDistribution proto.InternalMessageInfo

type MsgScheduleDistributionResponse struct {
	DistributionId string `protobuf:"bytes,1,opt,name=distribution_id,json=distributionId,proto3" json:"distribution_id,omitempty"`
}

func (m *MsgScheduleDistributionResponse) Reset()         { *m = MsgScheduleDistributionResponse{} }
func (m *MsgScheduleDistributionResponse) String() string { return proto.CompactTextString(m) }
func (*MsgScheduleDistributionResponse) ProtoMessage()    {}
func (*MsgScheduleDistributionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b509fdec62041204, []int{3}
}
func (m *MsgScheduleDistributionResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgScheduleDistributionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgScheduleDistributionResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgScheduleDistributionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgScheduleDistributionResponse.Merge(m, src)
}
func (m *MsgScheduleDistributionResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgScheduleDistributionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgScheduleDistributionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgScheduleDistributionResponse proto.InternalMessageInfo

func (m *MsgScheduleDistributionResponse) GetDistributionId() string {
	if m != nil {
		return m.DistributionId
	}
	return ""
}

type MsgExecuteDistribution struct {
	Authority      string `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	DistributionId string `protobuf:"bytes,2,opt,name=distribution_id,json=distributionId,proto3" json:"distribution_id,omitempty"`
}

func (m *MsgExecuteDistribution) Reset()         { *m = MsgExecuteDistribution{} }
func (m *MsgExecuteDistribution) String() string { return proto.CompactTextString(m) }
func (*MsgExecuteDistribution) ProtoMessage()    {}
func (*MsgExecuteDistribution) Descriptor() ([]byte, []int) {
	return fileDescriptor_b509fdec62041204, []int{4}
}
func (m *MsgExecuteDistribution) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgExecuteDistribution) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgExecuteDistribution.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgExecuteDistribution) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgExecuteDistribution.Merge(m, src)
}
func (m *MsgExecuteDistribution) XXX_Size() int {
	return m.Size()
}
func (m *MsgExecuteDistribution) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgExecuteDistribution.DiscardUnknown(m)
}

var xxx_messageInfo_MsgExecuteDistribution proto.InternalMessageInfo

type MsgExecuteDistributionResponse struct {
	RecipientsCount  int64                 `protobuf:"varint,1,opt,name=recipients_count,json=recipientsCount,proto3" json:"recipients_count,omitempty"`
	TotalDistributed cosmossdk_io_math.Int `protobuf:"bytes,2,opt,name=total_distributed,json=totalDistributed,proto3,customtype=cosmossdk.io/math.Int" json:"total_distributed"`
}

func (m *MsgExecuteDistributionResponse) Reset()         { *m = MsgExecuteDistributionResponse{} }
func (m *MsgExecuteDistributionResponse) String() string { return proto.CompactTextString(m) }
func (*MsgExecuteDistributionResponse) ProtoMessage()    {}
func (*MsgExecuteDistributionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b509fdec62041204, []int{5}
}
func (m *MsgExecuteDistributionResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgExecuteDistributionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgExecuteDistributionResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgExecuteDistributionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgExecuteDistributionResponse.Merge(m, src)
}
func (m *MsgExecuteDistributionResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgExecuteDistributionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgExecuteDistributionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgExecuteDistributionResponse proto.InternalMessageInfo

func (m *MsgExecuteDistributionResponse) GetRecipientsCount() int64 {
	if m != nil {
		return m.RecipientsCount
	}
	return 0
}

func init() {
	proto.RegisterType((*MsgRegisterDescendant)(nil), "aequitas.distribution.v1.MsgRegisterDescendant")
	proto.RegisterType((*MsgRegisterDescendantResponse)(nil), "aequitas.distribution.v1.MsgRegisterDescendantResponse")
	proto.RegisterType((*MsgScheduleDistribution)(nil), "aequitas.distribution.v1.MsgScheduleDistribution")
	proto.RegisterType((*MsgScheduleDistributionResponse)(nil), "aequitas.distribution.v1.MsgScheduleDistributionResponse")
	proto.RegisterType((*MsgExecuteDistribution)(nil), "aequitas.distribution.v1.MsgExecuteDistribution")
	proto.RegisterType((*MsgExecuteDistributionResponse)(nil), "aequitas.distribution.v1.MsgExecuteDistributionResponse")
}

func init() { proto.RegisterFile("aequitas/distribution/v1/tx.proto", fileDescriptor_b509fdec62041204) }

var fileDescriptor_b509fdec62041204 = []byte{
	// 683 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x54, 0xcf, 0x4f, 0xd4, 0x40,
	0x18, 0xdd, 0x61, 0xc1, 0xc0, 0xa0, 0x80, 0x95, 0x1f, 0xb5, 0x89, 0x5d, 0xdc, 0xc4, 0xc8, 0x8f,
	0xd0, 0x0a, 0x26, 0xa2, 0x1e, 0x4c, 0x96, 0x5d, 0x0e, 0x98, 0xac, 0x3f, 0x0a, 0x07, 0xe3, 0xa5,
	0x29, 0x9d, 0xa1, 0x3b, 0x71, 0xdb, 0xa9, 0x9d, 0xe9, 0x06, 0x2e, 0x46, 0x8d, 0x07, 0x8e, 0x7a,
	0xf2, 0xca, 0xc5, 0x3b, 0x07, 0xfe, 0x08, 0x12, 0x2f, 0x84, 0x93, 0xf1, 0x40, 0x0c, 0x1c, 0xf0,
	0xcf, 0x30, 0x9d, 0x76, 0xbb, 0xc5, 0x74, 0x89, 0x9b, 0x78, 0x6b, 0xbf, 0x7e, 0xef, 0x7b, 0xef,
	0x7b, 0xaf, 0x33, 0xf0, 0xb6, 0x85, 0xdf, 0x86, 0x84, 0x5b, 0x4c, 0x47, 0x84, 0xf1, 0x80, 0x6c,
	0x86, 0x9c, 0x50, 0x4f, 0x6f, 0x2d, 0xea, 0x7c, 0x5b, 0xf3, 0x03, 0xca, 0xa9, 0x24, 0xb7, 0x5b,
	0xb4, 0x6c, 0x8b, 0xd6, 0x5a, 0x54, 0xa6, 0x6c, 0xca, 0x5c, 0xca, 0x74, 0x97, 0x39, 0x11, 0xc2,
	0x65, 0x4e, 0x0c, 0x51, 0xc6, 0x1d, 0xea, 0x50, 0xf1, 0xa8, 0x47, 0x4f, 0x49, 0xf5, 0x66, 0xdc,
	0x6e, 0xc6, 0x1f, 0xe2, 0x97, 0xe4, 0xd3, 0x7c, 0x57, 0x19, 0x17, 0x38, 0x45, 0x73, 0x79, 0x17,
	0xc0, 0x89, 0x3a, 0x73, 0x0c, 0xec, 0x10, 0xc6, 0x71, 0x50, 0xc3, 0xcc, 0xc6, 0x1e, 0xb2, 0x3c,
	0x2e, 0x3d, 0x80, 0x43, 0x96, 0xef, 0x37, 0x89, 0x6d, 0x79, 0x5c, 0x06, 0xd3, 0x60, 0x66, 0x68,
	0x45, 0x3e, 0x3e, 0x58, 0x18, 0x4f, 0xb8, 0x2a, 0x08, 0x05, 0x98, 0xb1, 0x75, 0x1e, 0x10, 0xcf,
	0x31, 0x3a, 0xad, 0x52, 0x09, 0x0e, 0x37, 0x89, 0x87, 0x2d, 0x07, 0x9b, 0x36, 0x41, 0x72, 0x5f,
	0x84, 0x34, 0x60, 0x52, 0xaa, 0x12, 0xf4, 0x78, 0x72, 0x77, 0xaf, 0x54, 0xf8, 0xbd, 0x57, 0x2a,
	0x7c, 0x3c, 0xdf, 0x9f, 0xeb, 0x00, 0xcb, 0x5b, 0xf0, 0x56, 0xae, 0x12, 0x03, 0x33, 0x9f, 0x7a,
	0x0c, 0x4b, 0x0a, 0x1c, 0xb4, 0x7c, 0x3f, 0xa0, 0x2d, 0x8c, 0x84, 0xa0, 0x41, 0x23, 0x7d, 0x97,
	0x66, 0xe1, 0x58, 0x0b, 0x07, 0x64, 0x8b, 0xd8, 0x56, 0xb4, 0x5d, 0x86, 0x7a, 0x34, 0x5b, 0xaf,
	0x12, 0x54, 0xfe, 0xde, 0x07, 0xa7, 0xea, 0xcc, 0x59, 0xb7, 0x1b, 0x18, 0x85, 0x4d, 0x5c, 0xcb,
	0x98, 0x22, 0x96, 0x0e, 0x79, 0x83, 0x06, 0x84, 0xef, 0xfc, 0xc3, 0xd2, 0xed, 0x56, 0xe9, 0x09,
	0xec, 0xe7, 0x3b, 0x3e, 0x16, 0x94, 0x23, 0x4b, 0x73, 0x5a, 0xb7, 0x98, 0xb5, 0x2c, 0xdb, 0xc6,
	0x8e, 0x8f, 0x0d, 0x81, 0x93, 0x9e, 0xc1, 0xab, 0x9c, 0x72, 0xab, 0x69, 0x5a, 0x2e, 0x0d, 0x3d,
	0x2e, 0x17, 0x05, 0xf5, 0xfc, 0xe1, 0x49, 0xa9, 0xf0, 0xf3, 0xa4, 0x34, 0x11, 0xd3, 0x33, 0xf4,
	0x46, 0x23, 0x54, 0x77, 0x2d, 0xde, 0xd0, 0xd6, 0x3c, 0x7e, 0x7c, 0xb0, 0x00, 0x13, 0x5d, 0x6b,
	0x1e, 0x37, 0x86, 0xc5, 0x80, 0x8a, 0xc0, 0x4b, 0x77, 0xe0, 0x08, 0x4b, 0xf6, 0x43, 0x26, 0x27,
	0x2e, 0x96, 0xfb, 0xa7, 0xc1, 0x4c, 0xd1, 0xb8, 0x96, 0x56, 0x37, 0x88, 0x8b, 0x23, 0xd7, 0x18,
	0x0d, 0x03, 0x1b, 0x9b, 0x08, 0x6f, 0xc5, 0x6e, 0xcb, 0x03, 0xb1, 0x6b, 0x71, 0xbd, 0xd6, 0x2e,
	0xff, 0x9d, 0x5a, 0x7b, 0xf3, 0xf2, 0x53, 0x58, 0xea, 0x62, 0x66, 0x9a, 0xdb, 0x5d, 0x38, 0x9a,
	0xb5, 0xc1, 0x24, 0x71, 0x7c, 0x43, 0xc6, 0x48, 0xb6, 0xbc, 0x86, 0xca, 0x5f, 0x00, 0x9c, 0xac,
	0x33, 0x67, 0x75, 0x1b, 0xdb, 0x21, 0xff, 0x3f, 0xc1, 0xe4, 0x70, 0xf7, 0xe5, 0x71, 0x77, 0xdd,
	0xef, 0x1b, 0x80, 0x6a, 0xbe, 0xa6, 0x74, 0xbf, 0x59, 0x38, 0x16, 0x60, 0x9b, 0xf8, 0x04, 0x7b,
	0x9c, 0x99, 0xb6, 0x08, 0x10, 0x08, 0xbb, 0x47, 0x3b, 0xf5, 0xaa, 0xc8, 0xe5, 0x15, 0xbc, 0x1e,
	0xe7, 0x9c, 0xb2, 0xe3, 0x44, 0x50, 0x6f, 0x61, 0x8f, 0x89, 0x29, 0xb5, 0xce, 0x90, 0xa5, 0xaf,
	0x45, 0x58, 0xac, 0x33, 0x47, 0x7a, 0x07, 0xa5, 0x9c, 0xc3, 0xac, 0x77, 0xff, 0x23, 0x73, 0xcf,
	0x9c, 0xb2, 0xdc, 0x23, 0x20, 0x35, 0xe3, 0x13, 0x80, 0xe3, 0xb9, 0x47, 0x6b, 0xf1, 0xd2, 0x89,
	0x79, 0x10, 0xe5, 0x51, 0xcf, 0x90, 0x54, 0xc6, 0x07, 0x00, 0x6f, 0xe4, 0xfd, 0x47, 0xf7, 0x2e,
	0x1d, 0x99, 0x83, 0x50, 0x1e, 0xf6, 0x8a, 0x68, 0x6b, 0x50, 0x06, 0xde, 0x9f, 0xef, 0xcf, 0x81,
	0x95, 0x97, 0x87, 0xa7, 0x2a, 0x38, 0x3a, 0x55, 0xc1, 0xaf, 0x53, 0x15, 0x7c, 0x3e, 0x53, 0x0b,
	0x47, 0x67, 0x6a, 0xe1, 0xc7, 0x99, 0x5a, 0x78, 0xbd, 0xec, 0x10, 0xde, 0x08, 0x37, 0x35, 0x9b,
	0xba, 0x7a, 0x35, 0xc0, 0xb4, 0x56, 0xa9, 0x3f, 0xd7, 0x8d, 0xd5, 0x17, 0x15, 0x43, 0x4f, 0xef,
	0xf0, 0xed, 0x8b, 0xb7, 0x78, 0x74, 0x5b, 0xb0, 0xcd, 0x2b, 0xe2, 0xf2, 0xbe, 0xff, 0x27, 0x00,
	0x00, 0xff, 0xff, 0x7a, 0xc4, 0xfc, 0x2b, 0x72, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	// RegisterDescendant registers a verified descendant
	RegisterDescendant(ctx context.Context, in *MsgRegisterDescendant, opts ...grpc.CallOption) (*MsgRegisterDescendantResponse, error)
	// ScheduleDistribution schedules a reparations distribution
	ScheduleDistribution(ctx context.Context, in *MsgScheduleDistribution, opts ...grpc.CallOption) (*MsgScheduleDistributionResponse, error)
	// ExecuteDistribution executes a scheduled distribution
	ExecuteDistribution(ctx context.Context, in *MsgExecuteDistribution, opts ...grpc.CallOption) (*MsgExecuteDistributionResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) RegisterDescendant(ctx context.Context, in *MsgRegisterDescendant, opts ...grpc.CallOption) (*MsgRegisterDescendantResponse, error) {
	out := new(MsgRegisterDescendantResponse)
	err := c.cc.Invoke(ctx, "/aequitas.distribution.v1.Msg/RegisterDescendant", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) ScheduleDistribution(ctx context.Context, in *MsgScheduleDistribution, opts ...grpc.CallOption) (*MsgScheduleDistributionResponse, error) {
	out := new(MsgScheduleDistributionResponse)
	err := c.cc.Invoke(ctx, "/aequitas.distribution.v1.Msg/ScheduleDistribution", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) ExecuteDistribution(ctx context.Context, in *MsgExecuteDistribution, opts ...grpc.CallOption) (*MsgExecuteDistributionResponse, error) {
	out := new(MsgExecuteDistributionResponse)
	err := c.cc.Invoke(ctx, "/aequitas.distribution.v1.Msg/ExecuteDistribution", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	// RegisterDescendant registers a verified descendant
	RegisterDescendant(context.Context, *MsgRegisterDescendant) (*MsgRegisterDescendantResponse, error)
	// ScheduleDistribution schedules a reparations distribution
	ScheduleDistribution(context.Context, *MsgScheduleDistribution) (*MsgScheduleDistributionResponse, error)
	// ExecuteDistribution executes a scheduled distribution
	ExecuteDistribution(context.Context, *MsgExecuteDistribution) (*MsgExecuteDistributionResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) RegisterDescendant(ctx context.Context, req *MsgRegisterDescendant) (*MsgRegisterDescendantResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterDescendant not implemented")
}
func (*UnimplementedMsgServer) ScheduleDistribution(ctx context.Context, req *MsgScheduleDistribution) (*MsgScheduleDistributionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ScheduleDistribution not implemented")
}
func (*UnimplementedMsgServer) ExecuteDistribution(ctx context.Context, req *MsgExecuteDistribution) (*MsgExecuteDistributionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExecuteDistribution not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_RegisterDescendant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgRegisterDescendant)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).RegisterDescendant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/aequitas.distribution.v1.Msg/RegisterDescendant",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).RegisterDescendant(ctx, req.(*MsgRegisterDescendant))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_ScheduleDistribution_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgScheduleDistribution)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).ScheduleDistribution(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/aequitas.distribution.v1.Msg/ScheduleDistribution",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).ScheduleDistribution(ctx, req.(*MsgScheduleDistribution))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_ExecuteDistribution_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgExecuteDistribution)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).ExecuteDistribution(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/aequitas.distribution.v1.Msg/ExecuteDistribution",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).ExecuteDistribution(ctx, req.(*MsgExecuteDistribution))
	}
	return interceptor(ctx, in, info, handler)
}

var Msg_serviceDesc = _Msg_serviceDesc
var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "aequitas.distribution.v1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterDescendant",
			Handler:    _Msg_RegisterDescendant_Handler,
		},
		{
			MethodName: "ScheduleDistribution",
			Handler:    _Msg_ScheduleDistribution_Handler,
		},
		{
			MethodName: "ExecuteDistribution",
			Handler:    _Msg_ExecuteDistribution_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "aequitas/distribution/v1/tx.proto",
}

func (m *MsgRegisterDescendant) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRegisterDescendant) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRegisterDescendant) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.LineageCid) > 0 {
		i -= len(m.LineageCid)
		copy(dAtA[i:], m.LineageCid)
		i = encodeVarintTx(dAtA, i, uint64(len(m.LineageCid)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Applicant) > 0 {
		i -= len(m.Applicant)
		copy(dAtA[i:], m.Applicant)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Applicant)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgRegisterDescendantResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRegisterDescendantResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRegisterDescendantResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.VerificationCid) > 0 {
		i -= len(m.VerificationCid)
		copy(dAtA[i:], m.VerificationCid)
		i = encodeVarintTx(dAtA, i, uint64(len(m.VerificationCid)))
		i--
		dAtA[i] = 0x12
	}
	if m.Approved {
		i--
		if m.Approved {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *MsgScheduleDistribution) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgScheduleDistribution) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgScheduleDistribution) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.SourceDefendant) > 0 {
		i -= len(m.SourceDefendant)
		copy(dAtA[i:], m.SourceDefendant)
		i = encodeVarintTx(dAtA, i, uint64(len(m.SourceDefendant)))
		i--
		dAtA[i] = 0x2a
	}
	if m.ScheduledTime != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.ScheduledTime))
		i--
		dAtA[i] = 0x20
	}
	{
		size := m.TotalAmount.Size()
		i -= size
		if _, err := m.TotalAmount.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	if m.Type != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Type))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Authority) > 0 {
		i -= len(m.Authority)
		copy(dAtA[i:], m.Authority)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Authority)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgScheduleDistributionResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgScheduleDistributionResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgScheduleDistributionResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.DistributionId) > 0 {
		i -= len(m.DistributionId)
		copy(dAtA[i:], m.DistributionId)
		i = encodeVarintTx(dAtA, i, uint64(len(m.DistributionId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgExecuteDistribution) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgExecuteDistribution) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgExecuteDistribution) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.DistributionId) > 0 {
		i -= len(m.DistributionId)
		copy(dAtA[i:], m.DistributionId)
		i = encodeVarintTx(dAtA, i, uint64(len(m.DistributionId)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Authority) > 0 {
		i -= len(m.Authority)
		copy(dAtA[i:], m.Authority)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Authority)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgExecuteDistributionResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgExecuteDistributionResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgExecuteDistributionResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.TotalDistributed.Size()
		i -= size
		if _, err := m.TotalDistributed.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if m.RecipientsCount != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.RecipientsCount))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgRegisterDescendant) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Applicant)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.LineageCid)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgRegisterDescendantResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Approved {
		n += 2
	}
	l = len(m.VerificationCid)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgScheduleDistribution) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Authority)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Type != 0 {
		n += 1 + sovTx(uint64(m.Type))
	}
	l = m.TotalAmount.Size()
	n += 1 + l + sovTx(uint64(l))
	if m.ScheduledTime != 0 {
		n += 1 + sovTx(uint64(m.ScheduledTime))
	}
	l = len(m.SourceDefendant)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgScheduleDistributionResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.DistributionId)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgExecuteDistribution) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Authority)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.DistributionId)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgExecuteDistributionResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.RecipientsCount != 0 {
		n += 1 + sovTx(uint64(m.RecipientsCount))
	}
	l = m.TotalDistributed.Size()
	n += 1 + l + sovTx(uint64(l))
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgRegisterDescendant) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRegisterDescendant: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRegisterDescendant: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Applicant", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Applicant = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LineageCid", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.LineageCid = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgRegisterDescendantResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRegisterDescendantResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRegisterDescendantResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Approved", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Approved = bool(v != 0)
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field VerificationCid", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.VerificationCid = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgScheduleDistribution) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgScheduleDistribution: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgScheduleDistribution: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Authority", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Authority = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Type", wireType)
			}
			m.Type = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Type |= DistributionType(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalAmount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.TotalAmount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ScheduledTime", wireType)
			}
			m.ScheduledTime = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ScheduledTime |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SourceDefendant", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SourceDefendant = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgScheduleDistributionResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgScheduleDistributionResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgScheduleDistributionResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DistributionId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DistributionId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgExecuteDistribution) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgExecuteDistribution: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgExecuteDistribution: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Authority", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Authority = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DistributionId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DistributionId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgExecuteDistributionResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgExecuteDistributionResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgExecuteDistributionResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RecipientsCount", wireType)
			}
			m.RecipientsCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RecipientsCount |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalDistributed", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.TotalDistributed.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
