# AEQUITAS ZONE - Digital Sovereign Nation Funding
# $50,000 = 15 Months of Sovereign Infrastructure | Not a Token Sale

github: CreoDAMO
patreon: 
open_collective: aequitas-zone
ko_fi: 
tidelift: 
community_bridge: 
liberapay: 
issuehunt: 
lfx_crowdfunding: 
polar: 
buy_me_a_coffee: 
thanks_dev: 
custom:
  - 'https://github.com/sponsors/CreoDAMO'
  - 'https://www.paypal.com/pool/9jI7K6ro7c'
  - 'https://cash.app/f/POOL?id=gn58jvl3'
  - 'https://aequitasprotocol.zone/donate'
